# Generated by Django 5.1.15 on 2026-02-12 14:49

import apps.accounts.managers
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentActionPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_key', models.CharField(db_index=True, max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_agent_action_permission',
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, help_text="Shareable slug segment used to route requests to this agent (e.g. 'agentnameai').", max_length=160)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('tone', models.CharField(blank=True, max_length=60)),
                ('traits', models.JSONField(blank=True, default=list)),
                ('escalation_rule', models.CharField(blank=True, max_length=60)),
                ('selected_kpis', models.JSONField(blank=True, default=list, help_text='List of KPI identifiers guiding the agent response strategy.')),
                ('custom_kpis', models.JSONField(blank=True, default=list, help_text='Custom KPIs defined by the business to specialize agent performance.')),
                ('allow_custom_kpi_weighting', models.BooleanField(default=False, help_text='Allow orchestrator to prioritize custom KPIs ahead of default ones.')),
                ('mcp_default_approval_mode', models.CharField(blank=True, choices=[('auto', 'Auto-approve all'), ('approve_writes', 'Approve write operations'), ('approve_all', 'Approve all operations')], help_text='Optional default approval mode for external MCP tools (overrides connection defaults when set).', max_length=24, null=True)),
                ('mcp_gateway_mode', models.BooleanField(blank=True, help_text='Optional override for MCP gateway mode. When enabled, the agent uses a small gateway tool surface for external MCP tools instead of inlining every remote tool schema into the LLM prompt.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('active', 'Active')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_agent_profile',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=120)),
                ('industry_key', models.CharField(blank=True, max_length=64)),
                ('line_of_business', models.JSONField(blank=True, default=list)),
                ('line_of_business_custom', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('website', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True, help_text='Public slug used to route to the chat portal (derived from the business name).', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active')], default='draft', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_business_profile',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RegistrationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.CharField(default='form', max_length=32)),
                ('steps_completed', models.PositiveSmallIntegerField(default=0)),
                ('total_steps', models.PositiveSmallIntegerField(default=4)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts_registration_session',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TenantMemoryConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_hot_period_days', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_warm_period_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_archive_after_days', models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(0)])),
                ('custom_rules', models.JSONField(blank=True, default=dict)),
                ('minimum_retention_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_retention_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('purge_enabled', models.BooleanField(default=True)),
                ('legal_hold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_tenant_memory_configuration',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='TenantMemoryConfigurationAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('preset_applied', 'Preset applied'), ('deleted', 'Deleted')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_tenant_memory_configuration_audit_event',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('disabled', 'Disabled')], default='pending', max_length=32)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
