# Generated by Django 5.1.15 on 2026-02-12 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='allowed_collections',
            field=models.ManyToManyField(blank=True, help_text='Knowledge collections this agent is permitted to use during conversations.', related_name='permitted_agents', through='knowledge.AgentCollectionAccess', to='knowledge.knowledgecollection'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='allowed_documents',
            field=models.ManyToManyField(blank=True, help_text='Knowledge uploads this agent is permitted to use during conversations.', related_name='permitted_agents', through='knowledge.AgentKnowledgeAccess', to='knowledge.knowledgeupload'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentactionpermission',
            name='agent_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_permissions', to='accounts.agentprofile'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='business_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='registrationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='registration_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='accounts.registrationsession'),
        ),
        migrations.AddField(
            model_name='tenantmemoryconfiguration',
            name='business_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_config', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='tenantmemoryconfigurationauditevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_config_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantmemoryconfigurationauditevent',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_config_audit_events', to='accounts.businessprofile'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['public_id'], name='user_public_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'created_at'], name='user_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentactionpermission',
            index=models.Index(fields=['action_key'], name='agent_action_key_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentactionpermission',
            unique_together={('agent_profile', 'action_key')},
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['user', 'status'], name='agent_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['status', 'updated_at'], name='agent_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['business_profile', 'slug'], name='agent_business_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('business_profile', 'slug'), name='agent_unique_business_slug'),
        ),
        migrations.AddIndex(
            model_name='registrationsession',
            index=models.Index(fields=['user'], name='registration_user_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationsession',
            index=models.Index(fields=['is_complete', 'updated_at'], name='registration_status_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['user', 'status'], name='business_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['industry'], name='business_industry_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['slug'], name='business_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('slug',), name='business_slug_unique'),
        ),
        migrations.AddIndex(
            model_name='tenantmemoryconfigurationauditevent',
            index=models.Index(fields=['business_profile', 'occurred_at'], name='memcfg_audit_bp_time_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmemoryconfigurationauditevent',
            index=models.Index(fields=['actor_user', 'occurred_at'], name='memcfg_audit_actor_time_idx'),
        ),
    ]
