# Generated by Django 5.1.13 on 2025-11-06 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=120)),
                ('industry_key', models.CharField(blank=True, max_length=64)),
                ('line_of_business', models.JSONField(blank=True, default=list)),
                ('line_of_business_custom', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='accounts.registrationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_business_profile',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='business_user_status_idx'), models.Index(fields=['industry'], name='business_industry_idx')],
            },
        ),
    ]
