# Generated by Django 5.1.15 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="allowed_documents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Knowledge uploads this agent is permitted to use during conversations.",
                related_name="permitted_agents",
                through="knowledge.AgentKnowledgeAccess",
                to="knowledge.knowledgeupload",
            ),
        ),
    ]
