# Generated by Django 5.1.13 on 2025-11-06 02:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_businessprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('tone', models.CharField(blank=True, max_length=60)),
                ('traits', models.JSONField(blank=True, default=list)),
                ('escalation_rule', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('active', 'Active')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='accounts.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_agent_profile',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='agent_user_status_idx'), models.Index(fields=['status', 'updated_at'], name='agent_status_updated_idx')],
            },
        ),
    ]
