# Generated by Django 5.1.15 on 2026-02-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='allowed_collections',
        ),
    ]
