# Generated by Django 5.1.14 on 2026-05-12 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def promote_existing_main_agents(apps, schema_editor):
    AgentProfile = apps.get_model("accounts", "AgentProfile")
    BusinessProfile = apps.get_model("accounts", "BusinessProfile")
    for business in BusinessProfile.objects.all().only("id"):
        first_agent = (
            AgentProfile.objects.filter(business_profile_id=business.id)
            .exclude(status="archived")
            .order_by("created_at", "id")
            .first()
        )
        if first_agent is None:
            continue
        AgentProfile.objects.filter(id=first_agent.id).update(
            agent_type="main",
            can_manage_tasks=True,
            can_manage_departments=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agentprofile_existing_db_workforce_shape'),
        ('knowledge', '0006_fix_table_row_evidence_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='agent_type',
            field=models.CharField(choices=[('main', 'Main Agent'), ('department_lead', 'Department Lead'), ('specialist', 'Specialist'), ('background', 'Background Agent')], db_index=True, default='specialist', max_length=32),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='can_manage_departments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='can_manage_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='manager_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_agents', to='accounts.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='permission_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AgentDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], db_index=True, default='active', max_length=24)),
                ('instructions', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_departments', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_departments', to=settings.AUTH_USER_MODEL)),
                ('lead_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_departments', to='accounts.agentprofile')),
            ],
            options={
                'db_table': 'accounts_agent_department',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='accounts.agentdepartment'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['business_profile', 'agent_type'], name='agent_business_type_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['department', 'status'], name='agent_dept_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['manager_agent', 'status'], name='agent_manager_status_idx'),
        ),
        migrations.RunPython(promote_existing_main_agents, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='agentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('agent_type', 'main'), ('status', 'active')), fields=('business_profile', 'agent_type'), name='agent_unique_active_main'),
        ),
        migrations.AddIndex(
            model_name='agentdepartment',
            index=models.Index(fields=['business_profile', 'status'], name='dept_business_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdepartment',
            index=models.Index(fields=['business_profile', 'slug'], name='dept_business_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentdepartment',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('business_profile', 'slug'), name='dept_unique_business_slug'),
        ),
    ]
