# Generated by Django 5.1.13 on 2025-11-06 02:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=40)),
                ('url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_uploads', to='accounts.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_knowledge_upload',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['business_profile', 'resource_type'], name='upload_business_type_idx'), models.Index(fields=['status', 'updated_at'], name='upload_status_updated_idx')],
            },
        ),
    ]
