# Generated by Django 5.1.14 on 2026-05-12 15:53

import django.db.models.deletion
from django.db import migrations, models


def promote_existing_main_agents(apps, schema_editor):
    AgentProfile = apps.get_model("accounts", "AgentProfile")
    BusinessProfile = apps.get_model("accounts", "BusinessProfile")
    for business in BusinessProfile.objects.all().only("id"):
        first_agent = (
            AgentProfile.objects.filter(business_profile_id=business.id)
            .exclude(status="archived")
            .order_by("created_at", "id")
            .first()
        )
        if first_agent is None:
            continue
        AgentProfile.objects.filter(id=first_agent.id).update(
            agent_type="main",
            can_manage_tasks=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agentprofile_existing_db_workforce_shape'),
        ('knowledge', '0006_fix_table_row_evidence_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='agent_type',
            field=models.CharField(choices=[('main', 'Main Agent'), ('specialist', 'Specialist'), ('background', 'Background Agent')], db_index=True, default='specialist', max_length=32),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='can_manage_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='manager_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_agents', to='accounts.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='permission_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['business_profile', 'agent_type'], name='agent_business_type_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['manager_agent', 'status'], name='agent_manager_status_idx'),
        ),
        migrations.RunPython(promote_existing_main_agents, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='agentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('agent_type', 'main'), ('status', 'active')), fields=('business_profile', 'agent_type'), name='agent_unique_active_main'),
        ),
    ]
