# Generated by Django 5.1.14 on 2025-11-06 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_knowledgeupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='allow_custom_kpi_weighting',
            field=models.BooleanField(default=False, help_text='Allow orchestrator to prioritize custom KPIs ahead of default ones.'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='custom_kpis',
            field=models.JSONField(blank=True, default=list, help_text='Custom KPIs defined by the business to specialize agent performance.'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='selected_kpis',
            field=models.JSONField(blank=True, default=list, help_text='List of KPI identifiers guiding the agent response strategy.'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='slug',
            field=models.SlugField(blank=True, help_text="Shareable slug segment used to route requests to this agent (e.g. 'agentnameai').", max_length=160),
        ),
        migrations.CreateModel(
            name='AgentKnowledgeAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional context about why access was granted.')),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_access_rules', to='accounts.agentprofile')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_knowledge_grants', to=settings.AUTH_USER_MODEL)),
                ('knowledge_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_access_rules', to='accounts.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_agent_knowledge_access',
                'ordering': ('-granted_at',),
            },
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='allowed_documents',
            field=models.ManyToManyField(blank=True, help_text='Knowledge uploads this agent is permitted to use during conversations.', related_name='permitted_agents', through='accounts.AgentKnowledgeAccess', to='accounts.knowledgeupload'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['business_profile', 'slug'], name='agent_business_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('business_profile', 'slug'), name='agent_unique_business_slug'),
        ),
        migrations.AddConstraint(
            model_name='agentknowledgeaccess',
            constraint=models.UniqueConstraint(fields=('agent_profile', 'knowledge_upload'), name='agent_knowledge_unique'),
        ),
    ]
