# Generated by Django 5.1.13 on 2025-11-06 16:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_agentprofile_allow_custom_kpi_weighting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('ingested', 'Ingested'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('archived', 'Archived'), ('restored', 'Restored')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_knowledge_audit_event',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('agents', 'Agents Only'), ('business', 'Entire Business')], default='private', max_length=32)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_knowledge_collection',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCollectionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_knowledge_collection_link',
                'ordering': ('position', 'added_at'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('ingest', 'Initial Ingest'), ('rebuild', 'Rebuild'), ('delete', 'Delete'), ('sync', 'Sync')], max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_knowledge_ingestion_job',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, default='', max_length=160)),
                ('integration_type', models.CharField(choices=[('custom', 'Custom'), ('notion', 'Notion'), ('google_drive', 'Google Drive'), ('zendesk', 'Zendesk'), ('hubspot', 'HubSpot'), ('slack', 'Slack'), ('confluence', 'Confluence')], default='custom', max_length=32)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('syncing', 'Syncing'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='connected', max_length=32)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_knowledge_integration',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('storage_path', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=128)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_file',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_text',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('normalized_host', models.CharField(blank=True, default='', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_url',
            },
        ),
        migrations.RemoveIndex(
            model_name='knowledgeupload',
            name='upload_business_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgeupload',
            name='upload_status_updated_idx',
        ),
        migrations.RemoveField(
            model_name='knowledgeupload',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='knowledgeupload',
            name='url',
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='category',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='checksum_sha256',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='created_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_contributions', to='accounts.agentprofile'),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='ingestion_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='ingestion_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='language',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='last_ingested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='legacy_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='retention_policy',
            field=models.JSONField(blank=True, default=dict, help_text='Optional rules for expiry or redaction.'),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='size_bytes',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='source_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('link', 'External Link'), ('text', 'Manual Entry'), ('integration', 'Integration Sync'), ('embed', 'Embedded Content')], db_column='resource_type', default='file', max_length=32),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='source_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='token_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('internal', 'Internal'), ('shared', 'Shared')], default='private', max_length=32),
        ),
        migrations.AlterField(
            model_name='knowledgeupload',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='knowledgeupload',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='knowledgeupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('active', 'Active'), ('failed', 'Failed'), ('archived', 'Archived')], default='pending', max_length=32),
        ),
        migrations.AlterModelTable(
            name='agentknowledgeaccess',
            table='accounts_agent_knowledge_grant',
        ),
        migrations.AddField(
            model_name='knowledgeauditevent',
            name='actor_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_audit_events', to='accounts.agentprofile'),
        ),
        migrations.AddField(
            model_name='knowledgeauditevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgeauditevent',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_audit_events', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='knowledgeauditevent',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='accounts.knowledgeupload'),
        ),
        migrations.AddField(
            model_name='knowledgecollection',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_collections', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='knowledgecollection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgecollectionlink',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_collection_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgecollectionlink',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='accounts.knowledgecollection'),
        ),
        migrations.AddField(
            model_name='knowledgecollectionlink',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_links', to='accounts.knowledgeupload'),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='knowledge_uploads', through='accounts.KnowledgeCollectionLink', to='accounts.knowledgecollection'),
        ),
        migrations.AddField(
            model_name='knowledgeingestionjob',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_jobs', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='knowledgeingestionjob',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='accounts.knowledgeupload'),
        ),
        migrations.AddField(
            model_name='knowledgeintegration',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_integrations', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='knowledgeintegration',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgeupload',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='accounts.knowledgeintegration'),
        ),
        migrations.AddIndex(
            model_name='knowledgeupload',
            index=models.Index(fields=['business_profile', 'status'], name='upload_business_status_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeupload',
            index=models.Index(fields=['business_profile', 'source_type'], name='upload_business_source_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeupload',
            index=models.Index(fields=['business_profile', 'slug'], name='upload_business_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeupload',
            index=models.Index(fields=['integration', 'status'], name='upload_integration_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeupload',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('business_profile', 'slug'), name='knowledge_unique_business_slug'),
        ),
        migrations.AddField(
            model_name='knowledgeuploadfile',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_detail', to='accounts.knowledgeupload'),
        ),
        migrations.AddField(
            model_name='knowledgeuploadtext',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_detail', to='accounts.knowledgeupload'),
        ),
        migrations.AddField(
            model_name='knowledgeuploadurl',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_detail', to='accounts.knowledgeupload'),
        ),
        migrations.AddIndex(
            model_name='knowledgeauditevent',
            index=models.Index(fields=['upload', 'action'], name='knowledge_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgecollection',
            index=models.Index(fields=['business_profile', 'slug'], name='knowledge_coll_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgecollection',
            index=models.Index(fields=['business_profile', 'visibility'], name='knowledge_coll_vis_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgecollection',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('business_profile', 'slug'), name='knowledge_coll_slug_uniq'),
        ),
        migrations.AddConstraint(
            model_name='knowledgecollectionlink',
            constraint=models.UniqueConstraint(fields=('collection', 'upload'), name='knowledge_coll_upload_uniq'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestionjob',
            index=models.Index(fields=['business_profile', 'status'], name='knowledge_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestionjob',
            index=models.Index(fields=['upload', 'job_type'], name='knowledge_job_type_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeintegration',
            index=models.Index(fields=['business_profile', 'integration_type'], name='knowledge_integration_type_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeintegration',
            index=models.Index(fields=['business_profile', 'slug'], name='knowledge_integration_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeintegration',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('business_profile', 'slug'), name='knowledge_integr_slug_uniq'),
        ),
    ]
