# Generated by Django 5.1.13 on 2025-11-06 23:28

from django.db import migrations, models
from django.utils.text import slugify


def populate_business_slugs(apps, schema_editor):
    BusinessProfile = apps.get_model("accounts", "BusinessProfile")
    existing = set(BusinessProfile.objects.exclude(slug="").values_list("slug", flat=True))
    for profile in BusinessProfile.objects.all().order_by("created_at"):
        if profile.slug:
            continue
        base_slug = slugify(profile.name) or "business"
        candidate = base_slug
        suffix = 2
        while candidate in existing:
            candidate = f"{base_slug}-{suffix}"
            suffix += 1
        profile.slug = candidate
        profile.save(update_fields=["slug"])
        existing.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_knowledgeauditevent_knowledgecollection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='slug',
            field=models.SlugField(blank=True, help_text='Public slug used to route to the chat portal (derived from the business name).', max_length=160),
        ),
        migrations.RunPython(populate_business_slugs, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['slug'], name='business_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('slug',), name='business_slug_unique'),
        ),
    ]
