# Generated by Django 5.1.13 on 2025-11-07 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_businessprofile_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentActionPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_key', models.CharField(db_index=True, max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_permissions', to='accounts.agentprofile')),
            ],
            options={
                'db_table': 'accounts_agent_action_permission',
                'indexes': [models.Index(fields=['action_key'], name='agent_action_key_idx')],
                'unique_together': {('agent_profile', 'action_key')},
            },
        ),
    ]
