# Generated by Django 5.1.13 on 2025-11-07 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_agentactionpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeupload',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='KnowledgeUploadChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='accounts.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_chunk',
                'ordering': ('upload_id', 'chunk_index'),
                'constraints': [models.UniqueConstraint(fields=('upload', 'chunk_index'), name='knowledge_chunk_unique_index')],
            },
        ),
    ]
