# Generated by Django 5.1.13 on 2025-11-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_knowledgeupload_chunk_count_knowledgeuploadchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeuploadchunk',
            name='embedding',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
