# Generated by Django 5.1.13 on 2025-11-08 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_knowledgeuploadchunk_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeUploadPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('width', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('rotation', models.IntegerField(default=0)),
                ('text_density', models.FloatField(default=0.0)),
                ('has_ocr_content', models.BooleanField(default=False)),
                ('content_type', models.CharField(blank=True, default='', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='accounts.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_page',
                'ordering': ('upload_id', 'page_number'),
                'indexes': [models.Index(fields=['upload', 'page_number'], name='knowledge_page_idx')],
                'constraints': [models.UniqueConstraint(fields=['upload', 'page_number'], name='knowledge_page_unique_number')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadPageBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('list', 'List'), ('table', 'Table'), ('figure', 'Figure'), ('image', 'Image'), ('footer', 'Footer'), ('header', 'Header'), ('ocr_only', 'OCR Text'), ('other', 'Other')], default='paragraph', max_length=32)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True, default='')),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('section_heading', models.CharField(blank=True, default='', max_length=255)),
                ('heading_path', models.JSONField(blank=True, default=list)),
                ('detected_language', models.CharField(blank=True, default='', max_length=32)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='accounts.knowledgeuploadpage')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_blocks', to='accounts.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_page_block',
                'ordering': ('page_id', 'order_index'),
                'indexes': [models.Index(fields=['upload', 'block_type'], name='knowledge_block_type_idx'), models.Index(fields=['page', 'block_type'], name='knowledge_block_page_idx')],
                'constraints': [models.UniqueConstraint(fields=['page', 'order_index'], name='knowledge_block_unique_order')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('section_heading', models.CharField(blank=True, default='', max_length=255)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('column_schema', models.JSONField(blank=True, default=list, help_text='Ordered schema describing each detected column.')),
                ('data_dictionary', models.JSONField(blank=True, default=dict, help_text='Optional metadata describing column semantics/normalization.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='accounts.knowledgeuploadpage')),
                ('source_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='accounts.knowledgeuploadpageblock')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='accounts.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_table',
                'ordering': ('upload_id', 'order_index'),
                'indexes': [models.Index(fields=['upload', 'order_index'], name='knowledge_table_upload_idx'), models.Index(fields=['page', 'order_index'], name='knowledge_table_page_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadTableRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='accounts.knowledgeuploadtable')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_table_row',
                'ordering': ('table_id', 'row_index'),
                'constraints': [models.UniqueConstraint(fields=['table', 'row_index'], name='knowledge_table_row_unique_index')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadTableCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_index', models.PositiveIntegerField()),
                ('column_key', models.CharField(blank=True, default='', max_length=160)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('normalized_value', models.JSONField(blank=True, default=dict, help_text='Parsed/typed representation (e.g., amount, currency).')),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='accounts.knowledgeuploadtablerow')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='accounts.knowledgeuploadtable')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_table_cell',
                'ordering': ('table_id', 'row_id', 'column_index'),
                'indexes': [models.Index(fields=['table', 'column_index'], name='knowledge_cell_column_idx')],
                'constraints': [models.UniqueConstraint(fields=['row', 'column_index'], name='knowledge_cell_unique_row_column')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_code', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('detected_by', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='accounts.knowledgeuploadpage')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='accounts.knowledgeuploadtable')),
                ('table_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='accounts.knowledgeuploadtablecell')),
                ('table_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='accounts.knowledgeuploadtablerow')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='accounts.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_issue',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['upload', 'severity'], name='knowledge_issue_severity_idx'), models.Index(fields=['table', 'issue_code'], name='knowledge_issue_table_idx')],
            },
        ),
    ]
