# Generated by Django 5.1.14 on 2025-11-13 17:27

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_knowledge_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeuploadchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
