# Generated by Django 5.1.14 on 2025-11-13 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_update_ingestion_job_choices'),
        ('conversations', '0002_conversationfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDriftSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_kind', models.CharField(choices=[('ingestion', 'Ingestion'), ('retrieval', 'Retrieval')], max_length=24)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_samples', to='accounts.businessprofile')),
            ],
            options={
                'db_table': 'accounts_knowledge_drift_sample',
                'ordering': ('-observed_at',),
                'indexes': [models.Index(fields=['business_profile', 'sample_kind', 'observed_at'], name='knowledge_drift_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFeedbackCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('expected_behavior', models.CharField(choices=[('alias_exact', 'Alias Path'), ('hybrid', 'Hybrid Search'), ('not_found', 'Not Found')], default='alias_exact', max_length=24)),
                ('expected_entities', models.JSONField(blank=True, default=list)),
                ('expected_aliases', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(default='feedback', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_cases', to='accounts.businessprofile')),
                ('conversation_feedback', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_case', to='conversations.conversationfeedback')),
            ],
            options={
                'db_table': 'accounts_knowledge_feedback_case',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['business_profile', 'is_active'], name='knowledge_feedback_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='RAGEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], default='pass', max_length=8)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('latencies', models.JSONField(blank=True, default=dict)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('violations', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='accounts.businessprofile')),
            ],
            options={
                'db_table': 'accounts_rag_evaluation_run',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['business_profile', 'slug'], name='rag_eval_business_slug_idx'), models.Index(fields=['status', 'created_at'], name='rag_eval_status_idx')],
            },
        ),
    ]
