# Generated by Django 5.1.14 on 2025-12-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_knowledge_ingestion_job_retries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeauditevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('ingested', 'Ingested'), ('read', 'Read'), ('exported', 'Exported'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('archived', 'Archived'), ('restored', 'Restored')], max_length=32),
        ),
    ]
