# Generated by Django 5.1.15 on 2026-01-05 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_refresh_chunk_embedding_index_partitioned'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCollectionAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional context about why access was granted.')),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_access_rules', to='accounts.agentprofile')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_access_rules', to='accounts.knowledgecollection')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_collection_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_agent_collection_grant',
                'ordering': ('-granted_at',),
            },
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='allowed_collections',
            field=models.ManyToManyField(blank=True, help_text='Knowledge collections this agent is permitted to use during conversations.', related_name='permitted_agents', through='accounts.AgentCollectionAccess', to='accounts.knowledgecollection'),
        ),
        migrations.AddConstraint(
            model_name='agentcollectionaccess',
            constraint=models.UniqueConstraint(fields=('agent_profile', 'collection'), name='agent_collection_unique'),
        ),
    ]
