# Generated by Django 5.1.15 on 2026-01-05 18:10

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def backfill_upload_snapshot(apps, schema_editor) -> None:
    KnowledgeAuditEvent = apps.get_model("accounts", "KnowledgeAuditEvent")
    KnowledgeAuditEvent.objects.filter(upload_id_snapshot__isnull=True).update(upload_id_snapshot=F("upload_id"))


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_agent_collection_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgeauditevent",
            name="upload_id_snapshot",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Snapshot of the upload UUID for retention when the upload is deleted.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeauditevent",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to="accounts.knowledgeupload",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeauditevent",
            index=models.Index(fields=["upload_id_snapshot", "action"], name="kn_audit_upid_action_idx"),
        ),
        migrations.RunPython(backfill_upload_snapshot, migrations.RunPython.noop),
    ]

