# Generated by Django 5.1.13 on 2026-01-09 12:59

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
import re
from django.db import migrations, models


def normalize_column_name(name: str) -> str:
    """
    Normalize column name for consistent matching.
    Matches the logic in apps.rag.table_semantics.normalize_column_name
    """
    if not name:
        return ""
    # Lowercase
    result = name.lower().strip()
    # Remove parenthetical content like "(EGP)" or "(USD)"
    result = re.sub(r'\s*\([^)]*\)\s*', ' ', result)
    # Replace special chars with spaces
    result = re.sub(r'[_\-/\\]+', ' ', result)
    # Collapse whitespace
    result = re.sub(r'\s+', ' ', result).strip()
    # Replace spaces with underscores for consistent token matching
    result = result.replace(' ', '_')
    return result


def populate_table_columns(apps, schema_editor):
    """
    Populate KnowledgeTableColumn from existing KnowledgeUploadTable.column_schema.
    """
    KnowledgeUploadTable = apps.get_model("accounts", "KnowledgeUploadTable")
    KnowledgeTableColumn = apps.get_model("accounts", "KnowledgeTableColumn")
    
    batch_size = 1000
    columns_to_create = []
    
    for table in KnowledgeUploadTable.objects.select_related(
        "upload", "upload__business_profile"
    ).iterator(chunk_size=500):
        column_schema = table.column_schema or []
        if not isinstance(column_schema, list):
            continue
        
        for idx, col_name in enumerate(column_schema):
            if not col_name:
                continue
            col_str = str(col_name).strip()
            if not col_str:
                continue
            
            columns_to_create.append(
                KnowledgeTableColumn(
                    table=table,
                    upload=table.upload,
                    business_profile=table.upload.business_profile,
                    column_index=idx,
                    column_name=col_str[:255],
                    column_normalized=normalize_column_name(col_str)[:255],
                )
            )
            
            if len(columns_to_create) >= batch_size:
                KnowledgeTableColumn.objects.bulk_create(
                    columns_to_create,
                    ignore_conflicts=True,
                )
                columns_to_create = []
    
    if columns_to_create:
        KnowledgeTableColumn.objects.bulk_create(
            columns_to_create,
            ignore_conflicts=True,
        )


def reverse_populate_table_columns(apps, schema_editor):
    """Reverse: delete all KnowledgeTableColumn records."""
    KnowledgeTableColumn = apps.get_model("accounts", "KnowledgeTableColumn")
    KnowledgeTableColumn.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_knowledge_audit_event_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeTableColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_index', models.PositiveIntegerField()),
                ('column_name', models.CharField(max_length=255)),
                ('column_normalized', models.CharField(db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_columns', to='accounts.businessprofile')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='accounts.knowledgeuploadtable')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_columns', to='accounts.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_table_column',
                'ordering': ('table_id', 'column_index'),
                'indexes': [
                    models.Index(fields=['business_profile', 'column_normalized'], name='knowledge_table_col_biz_idx'),
                    django.contrib.postgres.indexes.GinIndex(fields=['column_normalized'], name='knowledge_table_col_norm_trgm', opclasses=['gin_trgm_ops']),
                    django.contrib.postgres.indexes.GinIndex(fields=['column_name'], name='knowledge_table_col_name_trgm', opclasses=['gin_trgm_ops']),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('table', 'column_index'), name='knowledge_table_column_unique_index'),
                ],
            },
        ),
        migrations.RunPython(
            populate_table_columns,
            reverse_code=reverse_populate_table_columns,
        ),
    ]
