# Generated by Django 5.1.14 on 2026-01-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_knowledge_table_column'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Fix accounts_knowledge_upload_page
            ALTER TABLE accounts_knowledge_upload_page
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_upload_id_71f59c0b_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_page
            ADD CONSTRAINT accounts_knowledge_u_upload_id_71f59c0b_fk_accounts_
            FOREIGN KEY (upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_page_block
            ALTER TABLE accounts_knowledge_upload_page_block
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_upload_id_16e5acaa_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_page_block
            ADD CONSTRAINT accounts_knowledge_u_upload_id_16e5acaa_fk_accounts_
            FOREIGN KEY (upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_file
            ALTER TABLE accounts_knowledge_upload_file
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_upload_id_24ec81d1_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_file
            ADD CONSTRAINT accounts_knowledge_u_upload_id_24ec81d1_fk_accounts_
            FOREIGN KEY (upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_url
            ALTER TABLE accounts_knowledge_upload_url
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_upload_id_8f5dbc4f_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_url
            ADD CONSTRAINT accounts_knowledge_u_upload_id_8f5dbc4f_fk_accounts_
            FOREIGN KEY (upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_text
            ALTER TABLE accounts_knowledge_upload_text
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_upload_id_0db85baf_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_text
            ADD CONSTRAINT accounts_knowledge_u_upload_id_0db85baf_fk_accounts_
            FOREIGN KEY (upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_table
            ALTER TABLE accounts_knowledge_upload_table
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_upload_id_c9448029_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_table
            ADD CONSTRAINT accounts_knowledge_u_upload_id_c9448029_fk_accounts_
            FOREIGN KEY (upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_issue
            ALTER TABLE accounts_knowledge_upload_issue
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_upload_id_cb0c0324_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_issue
            ADD CONSTRAINT accounts_knowledge_u_upload_id_cb0c0324_fk_accounts_
            FOREIGN KEY (upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_entity
            ALTER TABLE accounts_knowledge_entity
            DROP CONSTRAINT IF EXISTS accounts_knowledge_e_upload_id_8c58596a_fk_accounts_;
            ALTER TABLE accounts_knowledge_entity
            ADD CONSTRAINT accounts_knowledge_e_upload_id_8c58596a_fk_accounts_
            FOREIGN KEY (upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_ingestion_job
            ALTER TABLE accounts_knowledge_ingestion_job
            DROP CONSTRAINT IF EXISTS accounts_knowledge_i_upload_id_1bbfba9e_fk_accounts_;
            ALTER TABLE accounts_knowledge_ingestion_job
            ADD CONSTRAINT accounts_knowledge_i_upload_id_1bbfba9e_fk_accounts_
            FOREIGN KEY (upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_table_column
            ALTER TABLE accounts_knowledge_table_column
            DROP CONSTRAINT IF EXISTS accounts_knowledge_t_upload_id_15b07111_fk_accounts_;
            ALTER TABLE accounts_knowledge_table_column
            ADD CONSTRAINT accounts_knowledge_t_upload_id_15b07111_fk_accounts_
            FOREIGN KEY (upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_agent_knowledge_grant
            ALTER TABLE accounts_agent_knowledge_grant
            DROP CONSTRAINT IF EXISTS accounts_agent_knowl_knowledge_upload_id_70351ebb_fk_accounts_;
            ALTER TABLE accounts_agent_knowledge_grant
            ADD CONSTRAINT accounts_agent_knowl_knowledge_upload_id_70351ebb_fk_accounts_
            FOREIGN KEY (knowledge_upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_collection_link
            ALTER TABLE accounts_knowledge_collection_link
            DROP CONSTRAINT IF EXISTS accounts_knowledge_c_upload_id_99f15fb9_fk_accounts_;
            ALTER TABLE accounts_knowledge_collection_link
            ADD CONSTRAINT accounts_knowledge_c_upload_id_99f15fb9_fk_accounts_
            FOREIGN KEY (upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_identifier_column (CASCADE)
            ALTER TABLE accounts_identifier_column
            DROP CONSTRAINT IF EXISTS accounts_identifier__upload_id_0792a3f0_fk_accounts_;
            ALTER TABLE accounts_identifier_column
            ADD CONSTRAINT accounts_identifier__upload_id_0792a3f0_fk_accounts_
            FOREIGN KEY (upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_audit_event (SET NULL)
            ALTER TABLE accounts_knowledge_audit_event
            DROP CONSTRAINT IF EXISTS accounts_knowledge_a_upload_id_4ec232b3_fk_accounts_;
            ALTER TABLE accounts_knowledge_audit_event
            ADD CONSTRAINT accounts_knowledge_a_upload_id_4ec232b3_fk_accounts_
            FOREIGN KEY (upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
            -- Note: Reverse SQL omitted for brevity, but would restore NO ACTION behavior
            """,
        ),
    ]
