# Generated by Django 5.1.14 on 2026-01-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_fix_knowledge_upload_page_cascade'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Clean up orphaned data first
            DELETE FROM accounts_knowledge_table_column
            WHERE table_id NOT IN (SELECT id FROM accounts_knowledge_upload_table);

            DELETE FROM accounts_knowledge_upload_table_row
            WHERE table_id NOT IN (SELECT id FROM accounts_knowledge_upload_table);

            DELETE FROM accounts_knowledge_upload_table_cell
            WHERE table_id NOT IN (SELECT id FROM accounts_knowledge_upload_table);

            DELETE FROM accounts_knowledge_upload_table_cell
            WHERE row_id NOT IN (SELECT id FROM accounts_knowledge_upload_table_row);

            DELETE FROM accounts_knowledge_alias
            WHERE entity_id NOT IN (SELECT id FROM accounts_knowledge_entity);

            DELETE FROM accounts_agent_collection_grant
            WHERE collection_id NOT IN (SELECT id FROM accounts_knowledge_collection);

            DELETE FROM accounts_knowledge_collection_link
            WHERE collection_id NOT IN (SELECT id FROM accounts_knowledge_collection);

            -- Fix accounts_knowledge_upload_table_row -> accounts_knowledge_upload_table (CASCADE)
            ALTER TABLE accounts_knowledge_upload_table_row
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_table_id_10fba0e7_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_table_row
            ADD CONSTRAINT accounts_knowledge_u_table_id_10fba0e7_fk_accounts_
            FOREIGN KEY (table_id) REFERENCES accounts_knowledge_upload_table(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_table_cell -> accounts_knowledge_upload_table (CASCADE)
            ALTER TABLE accounts_knowledge_upload_table_cell
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_table_id_e8a8c0d0_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_table_cell
            ADD CONSTRAINT accounts_knowledge_u_table_id_e8a8c0d0_fk_accounts_
            FOREIGN KEY (table_id) REFERENCES accounts_knowledge_upload_table(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_table_cell -> accounts_knowledge_upload_table_row (CASCADE)
            ALTER TABLE accounts_knowledge_upload_table_cell
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_row_id_f57fde25_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_table_cell
            ADD CONSTRAINT accounts_knowledge_u_row_id_f57fde25_fk_accounts_
            FOREIGN KEY (row_id) REFERENCES accounts_knowledge_upload_table_row(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_table_column -> accounts_knowledge_upload_table (CASCADE)
            ALTER TABLE accounts_knowledge_table_column
            DROP CONSTRAINT IF EXISTS accounts_knowledge_t_table_id_f7ff1bc4_fk_accounts_;
            ALTER TABLE accounts_knowledge_table_column
            ADD CONSTRAINT accounts_knowledge_t_table_id_f7ff1bc4_fk_accounts_
            FOREIGN KEY (table_id) REFERENCES accounts_knowledge_upload_table(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_issue -> accounts_knowledge_upload_page (SET NULL)
            ALTER TABLE accounts_knowledge_upload_issue
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_page_id_e35b3a46_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_issue
            ADD CONSTRAINT accounts_knowledge_u_page_id_e35b3a46_fk_accounts_
            FOREIGN KEY (page_id) REFERENCES accounts_knowledge_upload_page(id)
            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_issue -> accounts_knowledge_upload_table (SET NULL)
            ALTER TABLE accounts_knowledge_upload_issue
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_table_id_87602aad_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_issue
            ADD CONSTRAINT accounts_knowledge_u_table_id_87602aad_fk_accounts_
            FOREIGN KEY (table_id) REFERENCES accounts_knowledge_upload_table(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_issue -> accounts_knowledge_upload_table_cell (SET NULL)
            ALTER TABLE accounts_knowledge_upload_issue
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_table_cell_id_2e88c3f9_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_issue
            ADD CONSTRAINT accounts_knowledge_u_table_cell_id_2e88c3f9_fk_accounts_
            FOREIGN KEY (table_cell_id) REFERENCES accounts_knowledge_upload_table_cell(id)
            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_issue -> accounts_knowledge_upload_table_row (SET NULL)
            ALTER TABLE accounts_knowledge_upload_issue
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_table_row_id_b25494cb_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_issue
            ADD CONSTRAINT accounts_knowledge_u_table_row_id_b25494cb_fk_accounts_
            FOREIGN KEY (table_row_id) REFERENCES accounts_knowledge_upload_table_row(id)
            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_page_block -> accounts_knowledge_upload_page (CASCADE)
            ALTER TABLE accounts_knowledge_upload_page_block
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_page_id_ae77d50f_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_page_block
            ADD CONSTRAINT accounts_knowledge_u_page_id_ae77d50f_fk_accounts_
            FOREIGN KEY (page_id) REFERENCES accounts_knowledge_upload_page(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_table -> accounts_knowledge_upload_page (SET NULL)
            ALTER TABLE accounts_knowledge_upload_table
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_page_id_380d2508_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_table
            ADD CONSTRAINT accounts_knowledge_u_page_id_380d2508_fk_accounts_
            FOREIGN KEY (page_id) REFERENCES accounts_knowledge_upload_page(id)
            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload_table -> accounts_knowledge_upload_page_block (SET NULL)
            ALTER TABLE accounts_knowledge_upload_table
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_source_block_id_c40608e3_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload_table
            ADD CONSTRAINT accounts_knowledge_u_source_block_id_c40608e3_fk_accounts_
            FOREIGN KEY (source_block_id) REFERENCES accounts_knowledge_upload_page_block(id)
            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_alias -> accounts_knowledge_entity (CASCADE)
            ALTER TABLE accounts_knowledge_alias
            DROP CONSTRAINT IF EXISTS accounts_knowledge_a_entity_id_2a2fc248_fk_accounts_;
            ALTER TABLE accounts_knowledge_alias
            ADD CONSTRAINT accounts_knowledge_a_entity_id_2a2fc248_fk_accounts_
            FOREIGN KEY (entity_id) REFERENCES accounts_knowledge_entity(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_agent_collection_grant -> accounts_knowledge_collection (CASCADE)
            ALTER TABLE accounts_agent_collection_grant
            DROP CONSTRAINT IF EXISTS accounts_agent_colle_collection_id_cdd684f3_fk_accounts_;
            ALTER TABLE accounts_agent_collection_grant
            ADD CONSTRAINT accounts_agent_colle_collection_id_cdd684f3_fk_accounts_
            FOREIGN KEY (collection_id) REFERENCES accounts_knowledge_collection(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_collection_link -> accounts_knowledge_collection (CASCADE)
            ALTER TABLE accounts_knowledge_collection_link
            DROP CONSTRAINT IF EXISTS accounts_knowledge_c_collection_id_18996203_fk_accounts_;
            ALTER TABLE accounts_knowledge_collection_link
            ADD CONSTRAINT accounts_knowledge_c_collection_id_18996203_fk_accounts_
            FOREIGN KEY (collection_id) REFERENCES accounts_knowledge_collection(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_integration_credential_event -> accounts_knowledge_integration (CASCADE)
            ALTER TABLE accounts_integration_credential_event
            DROP CONSTRAINT IF EXISTS accounts_integration_integration_id_6e55d2b8_fk_accounts_;
            ALTER TABLE accounts_integration_credential_event
            ADD CONSTRAINT accounts_integration_integration_id_6e55d2b8_fk_accounts_
            FOREIGN KEY (integration_id) REFERENCES accounts_knowledge_integration(id)
            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

            -- Fix accounts_knowledge_upload -> accounts_knowledge_integration (SET NULL)
            ALTER TABLE accounts_knowledge_upload
            DROP CONSTRAINT IF EXISTS accounts_knowledge_u_integration_id_d749cfb7_fk_accounts_;
            ALTER TABLE accounts_knowledge_upload
            ADD CONSTRAINT accounts_knowledge_u_integration_id_d749cfb7_fk_accounts_
            FOREIGN KEY (integration_id) REFERENCES accounts_knowledge_integration(id)
            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
