# Generated by Django 5.1.13 on 2026-01-17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_fix_all_cascade_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="McpConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, db_index=True, default="", max_length=160)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("marketplace", "Marketplace"), ("manual", "Manual")],
                        default="manual",
                        max_length=24,
                    ),
                ),
                (
                    "marketplace_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional identifier for a curated marketplace entry.",
                        max_length=80,
                    ),
                ),
                ("server_url", models.URLField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "Enabled"), ("disabled", "Disabled")],
                        default="enabled",
                        max_length=16,
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("none", "No auth"), ("bearer", "Bearer token"), ("header", "Custom header")],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("credentials_encrypted", models.TextField(blank=True, default="")),
                ("credentials_key_version", models.PositiveSmallIntegerField(default=1)),
                ("credentials_last_rotated_at", models.DateTimeField(blank=True, null=True)),
                ("credential_error_count", models.PositiveSmallIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_connections",
                        to="accounts.businessprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_mcp_connection",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="McpConnectionAuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "connection_id_snapshot",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Snapshot of the connection UUID for retention when the connection is deleted.",
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("enabled", "Enabled"),
                            ("disabled", "Disabled"),
                            ("agent_opted_out", "Agent Opted Out"),
                            ("agent_opted_in", "Agent Opted In"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(db_index=True, default=timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_audit_events",
                        to="accounts.businessprofile",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="accounts.mcpconnection",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_mcp_connection_audit_event",
                "ordering": ("-occurred_at",),
            },
        ),
        migrations.CreateModel(
            name="McpConnectionAgentOptOut",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("opted_out_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "agent_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_opt_outs",
                        to="accounts.agentprofile",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_opt_outs",
                        to="accounts.mcpconnection",
                    ),
                ),
                (
                    "opted_out_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_opt_out_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_mcp_connection_opt_out",
                "ordering": ("-opted_out_at",),
            },
        ),
        migrations.AddIndex(
            model_name="mcpconnection",
            index=models.Index(fields=["business_profile", "status"], name="mcp_conn_business_status_idx"),
        ),
        migrations.AddIndex(
            model_name="mcpconnection",
            index=models.Index(fields=["business_profile", "slug"], name="mcp_conn_business_slug_idx"),
        ),
        migrations.AddConstraint(
            model_name="mcpconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug", ""), _negated=True),
                fields=("business_profile", "slug"),
                name="mcp_conn_slug_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="mcpconnectionagentoptout",
            index=models.Index(fields=["connection", "opted_out_at"], name="mcp_conn_opt_out_idx"),
        ),
        migrations.AddIndex(
            model_name="mcpconnectionagentoptout",
            index=models.Index(fields=["agent_profile", "opted_out_at"], name="mcp_agent_opt_out_idx"),
        ),
        migrations.AddConstraint(
            model_name="mcpconnectionagentoptout",
            constraint=models.UniqueConstraint(fields=("connection", "agent_profile"), name="mcp_conn_agent_opt_out_unique"),
        ),
        migrations.AddIndex(
            model_name="mcpconnectionauditevent",
            index=models.Index(fields=["connection", "action"], name="mcp_audit_action_idx"),
        ),
        migrations.AddIndex(
            model_name="mcpconnectionauditevent",
            index=models.Index(fields=["connection_id_snapshot", "action"], name="mcp_audit_snap_action_idx"),
        ),
    ]
