# Generated by ChatGPT on 2026-01-18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_mcp_connection_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpconnection",
            name="default_approval_mode",
            field=models.CharField(
                choices=[
                    ("auto", "Auto-approve all"),
                    ("approve_writes", "Approve write operations"),
                    ("approve_all", "Approve all operations"),
                ],
                default="approve_writes",
                help_text="Default approval behavior for tools from this connection.",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="McpConnectionToolSetting",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "tool_name",
                    models.CharField(
                        help_text="The remote tool name from the MCP server (e.g., 'create_issue').",
                        max_length=255,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("read", "Read (safe)"),
                            ("write", "Write (requires approval)"),
                            ("unknown", "Unknown (treat as write)"),
                        ],
                        default="unknown",
                        help_text="Classification: read (safe) or write (needs approval).",
                        max_length=16,
                    ),
                ),
                (
                    "approval_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("auto", "Auto-approve all"),
                            ("approve_writes", "Approve write operations"),
                            ("approve_all", "Approve all operations"),
                        ],
                        help_text="Override the connection default. NULL = inherit from connection.",
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable description of what this tool does.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_settings",
                        to="accounts.mcpconnection",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_mcp_connection_tool_setting",
                "ordering": ("tool_name",),
            },
        ),
        migrations.AddIndex(
            model_name="mcpconnectiontoolsetting",
            index=models.Index(fields=["connection", "operation_type"], name="mcp_tool_op_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="mcpconnectiontoolsetting",
            constraint=models.UniqueConstraint(
                fields=("connection", "tool_name"),
                name="mcp_tool_setting_unique",
            ),
        ),
    ]
