# Generated by Django 5.1.15 on 2026-01-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_mcp_connection_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpconnectionauditevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('enabled', 'Enabled'), ('disabled', 'Disabled'), ('agent_opted_out', 'Agent Opted Out'), ('agent_opted_in', 'Agent Opted In'), ('tool_approved', 'Tool Approved'), ('tool_denied', 'Tool Denied')], max_length=32),
        ),
    ]
