# Generated by Django 5.1.15 on 2026-01-18 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_mcpconnectionauditevent_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='mcp_default_approval_mode',
            field=models.CharField(blank=True, choices=[('auto', 'Auto-approve all'), ('approve_writes', 'Approve write operations'), ('approve_all', 'Approve all operations')], help_text='Optional default approval mode for external MCP tools (overrides connection defaults when set).', max_length=24, null=True),
        ),
        migrations.CreateModel(
            name='AgentMcpToolSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(help_text="The remote tool name from the MCP server (e.g., 'create_issue').", max_length=255)),
                ('operation_type', models.CharField(choices=[('read', 'Read (safe)'), ('write', 'Write (requires approval)'), ('unknown', 'Unknown (treat as write)')], default='unknown', help_text='Classification: read (safe) or write (needs approval).', max_length=16)),
                ('approval_mode', models.CharField(blank=True, choices=[('auto', 'Auto-approve all'), ('approve_writes', 'Approve write operations'), ('approve_all', 'Approve all operations')], help_text='Override the agent default for this tool. NULL = inherit.', max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tool_settings', to='accounts.agentprofile')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tool_settings', to='accounts.mcpconnection')),
            ],
            options={
                'db_table': 'accounts_agent_mcp_tool_setting',
                'ordering': ('tool_name',),
                'indexes': [models.Index(fields=['agent_profile', 'connection'], name='agt_mcp_tool_agent_conn_idx'), models.Index(fields=['connection', 'tool_name'], name='agt_mcp_tool_conn_tool_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent_profile', 'connection', 'tool_name'), name='agent_mcp_tool_setting_unique')],
            },
        ),
    ]
