# Generated by Django 5.1.15 on 2026-01-22 02:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_agentprofile_mcp_gateway_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('authorization_url', models.URLField(max_length=500)),
                ('token_url', models.URLField(max_length=500)),
                ('client_id', models.CharField(max_length=500)),
                ('client_secret_encrypted', models.TextField(blank=True, default='')),
                ('client_secret_key_version', models.PositiveSmallIntegerField(default=1)),
                ('client_secret_last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('client_secret_error_count', models.PositiveSmallIntegerField(default=0)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('marketplace_keys', models.JSONField(blank=True, default=list, help_text="Marketplace keys that should use this provider (e.g. ['gmail', 'google_drive']).")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_oauth_provider',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marketplace_key', models.CharField(max_length=100)),
                ('state_token', models.CharField(max_length=128, unique=True)),
                ('redirect_after', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to='accounts.businessprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to='accounts.oauthprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_oauth_state',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['expires_at'], name='oauth_state_expires_idx'), models.Index(fields=['provider', 'is_used'], name='oauth_state_provider_used_idx')],
            },
        ),
    ]
