# Generated by Django 5.1.15 on 2026-01-22 23:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_oauthprovider_oauthstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google (Gmail/Workspace)'), ('microsoft', 'Microsoft (Outlook/M365)')], max_length=16)),
                ('email_address', models.EmailField(blank=True, db_index=True, default='', max_length=255)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('error', 'Error')], default='disconnected', max_length=16)),
                ('send_mode', models.CharField(choices=[('draft_approval', 'Draft + approval'), ('auto_send', 'Auto-send')], default='draft_approval', help_text='Default send behavior for this connected mailbox.', max_length=24)),
                ('policy_config', models.JSONField(blank=True, default=dict)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('credentials_key_version', models.PositiveSmallIntegerField(default=1)),
                ('credentials_last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('credential_error_count', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='accounts.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_email_account',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentEmailAccountPolicyOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('send_mode', models.CharField(blank=True, choices=[('draft_approval', 'Draft + approval'), ('auto_send', 'Auto-send')], help_text='Override the email account default. NULL = inherit from EmailAccount.', max_length=24, null=True)),
                ('policy_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_policy_overrides', to='accounts.agentprofile')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_policy_overrides', to='accounts.emailaccount')),
            ],
            options={
                'db_table': 'accounts_agent_email_policy_override',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailAccountAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_account_id_snapshot', models.UUIDField(blank=True, db_index=True, help_text='Snapshot of the EmailAccount UUID for retention when the account is deleted.', null=True)),
                ('action', models.CharField(choices=[('connected', 'Connected'), ('updated', 'Updated'), ('disconnected', 'Disconnected'), ('error', 'Error')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_audit_events', to='accounts.agentprofile')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_audit_events', to=settings.AUTH_USER_MODEL)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_audit_events', to='accounts.businessprofile')),
                ('email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.emailaccount')),
            ],
            options={
                'db_table': 'accounts_email_account_audit_event',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailOAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_provider', models.CharField(choices=[('google', 'Google (Gmail/Workspace)'), ('microsoft', 'Microsoft (Outlook/M365)')], max_length=16)),
                ('state_token', models.CharField(max_length=128, unique=True)),
                ('redirect_after', models.URLField(blank=True, default='', max_length=500)),
                ('redirect_uri', models.URLField(blank=True, default='', max_length=500)),
                ('code_verifier', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_oauth_states', to='accounts.businessprofile')),
                ('provider', models.ForeignKey(help_text='OAuth provider configuration (e.g., google_email, microsoft_email).', on_delete=django.db.models.deletion.CASCADE, related_name='email_oauth_states', to='accounts.oauthprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_email_oauth_state',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['business_profile', 'status'], name='email_acct_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['business_profile', 'provider'], name='email_acct_biz_provider_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailaccount',
            constraint=models.UniqueConstraint(fields=('business_profile', 'user'), name='email_account_unique_user'),
        ),
        migrations.AddIndex(
            model_name='agentemailaccountpolicyoverride',
            index=models.Index(fields=['agent_profile', 'email_account'], name='agent_email_ov_agent_acct_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentemailaccountpolicyoverride',
            constraint=models.UniqueConstraint(fields=('agent_profile', 'email_account'), name='agent_email_policy_override_uniq'),
        ),
        migrations.AddIndex(
            model_name='emailaccountauditevent',
            index=models.Index(fields=['email_account', 'action'], name='email_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaccountauditevent',
            index=models.Index(fields=['email_account_id_snapshot', 'action'], name='email_audit_snap_action_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoauthstate',
            index=models.Index(fields=['expires_at'], name='email_oauth_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoauthstate',
            index=models.Index(fields=['provider', 'is_used'], name='email_oauth_prov_used_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoauthstate',
            index=models.Index(fields=['business_profile', 'email_provider'], name='email_oauth_biz_prov_idx'),
        ),
    ]
