# Generated by Django 5.1.15 on 2026-01-23 02:30

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_emailaccount_agentemailaccountpolicyoverride_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaccount",
            name="last_health_checked_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="EmailAccountHealthJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("trigger", models.CharField(blank=True, default="", max_length=48)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("run_after", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_account_health_jobs",
                        to="accounts.businessprofile",
                    ),
                ),
                (
                    "email_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_jobs",
                        to="accounts.emailaccount",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_email_account_health_job",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="emailaccounthealthjob",
            index=models.Index(fields=["status", "run_after"], name="email_health_run_after_idx"),
        ),
        migrations.AddIndex(
            model_name="emailaccounthealthjob",
            index=models.Index(fields=["status", "lease_expires_at"], name="email_health_lease_idx"),
        ),
        migrations.AddIndex(
            model_name="emailaccounthealthjob",
            index=models.Index(fields=["email_account", "status"], name="email_health_acct_status_idx"),
        ),
        migrations.AddIndex(
            model_name="emailaccounthealthjob",
            index=models.Index(fields=["business_profile", "status"], name="email_health_biz_status_idx"),
        ),
    ]

