# Generated by Django 5.1.15 on 2026-01-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_emailaccounthealthjob_and_last_health_checked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccountauditevent',
            name='action',
            field=models.CharField(choices=[('connected', 'Connected'), ('updated', 'Updated'), ('disconnected', 'Disconnected'), ('searched', 'Searched'), ('read_message', 'Read message'), ('read_thread', 'Read thread'), ('draft_created', 'Draft created'), ('send_requested', 'Send requested'), ('send_approved', 'Send approved'), ('send_denied', 'Send denied'), ('sent', 'Sent'), ('error', 'Error')], max_length=32),
        ),
    ]
