# Generated by ChatGPT on 2026-01-31

from __future__ import annotations

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0050_alter_emailaccountauditevent_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantMemoryConfiguration",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("default_hot_period_days", models.IntegerField(default=7)),
                ("default_warm_period_days", models.IntegerField(default=30)),
                ("default_archive_after_days", models.IntegerField(default=90)),
                ("custom_rules", models.JSONField(blank=True, default=dict)),
                ("minimum_retention_days", models.IntegerField(default=0)),
                ("maximum_retention_days", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_config",
                        to="accounts.businessprofile",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_tenant_memory_configuration",
                "ordering": ("-updated_at",),
            },
        ),
    ]
