# Generated by Django 5.1.15 on 2026-01-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_tenant_memory_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmemoryconfiguration',
            name='legal_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantmemoryconfiguration',
            name='purge_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
