# Generated by Django 5.1.15 on 2026-01-31 17:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_tenantmemoryconfiguration_legal_hold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmemoryconfiguration',
            name='default_archive_after_days',
            field=models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tenantmemoryconfiguration',
            name='default_hot_period_days',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tenantmemoryconfiguration',
            name='default_warm_period_days',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tenantmemoryconfiguration',
            name='maximum_retention_days',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tenantmemoryconfiguration',
            name='minimum_retention_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='TenantMemoryConfigurationAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('preset_applied', 'Preset applied'), ('deleted', 'Deleted')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_config_audit_events', to=settings.AUTH_USER_MODEL)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_config_audit_events', to='accounts.businessprofile')),
            ],
            options={
                'db_table': 'accounts_tenant_memory_configuration_audit_event',
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['business_profile', 'occurred_at'], name='memcfg_audit_bp_time_idx'), models.Index(fields=['actor_user', 'occurred_at'], name='memcfg_audit_actor_time_idx')],
            },
        ),
    ]
