# Generated by Django 5.1.15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_tenantmemoryconfiguration_default_archive_after_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('google_calendar', 'Google Calendar'), ('google_drive', 'Google Drive'), ('onedrive', 'OneDrive'), ('slack', 'Slack'), ('hubspot', 'HubSpot')], max_length=32)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('slack', 'Slack'), ('hubspot', 'HubSpot')], max_length=16)),
                ('account_identifier', models.CharField(blank=True, default='', help_text='Email address, workspace name, or other human-readable identifier.', max_length=320)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=320)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('error', 'Error')], default='disconnected', max_length=16)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('credentials_key_version', models.PositiveSmallIntegerField(default=1)),
                ('credentials_last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('credential_error_count', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_health_checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_accounts', to='accounts.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_integration_account',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='integrationaccount',
            constraint=models.UniqueConstraint(fields=('business_profile', 'user', 'integration_type'), name='integration_account_unique_user_type'),
        ),
        migrations.AddIndex(
            model_name='integrationaccount',
            index=models.Index(fields=['business_profile', 'status'], name='integ_acct_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationaccount',
            index=models.Index(fields=['business_profile', 'integration_type'], name='integ_acct_biz_type_idx'),
        ),
        migrations.CreateModel(
            name='IntegrationAccountAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_account_id_snapshot', models.UUIDField(blank=True, db_index=True, help_text='Snapshot of the IntegrationAccount UUID for retention when the account is deleted.', null=True)),
                ('action', models.CharField(choices=[('connected', 'Connected'), ('updated', 'Updated'), ('disconnected', 'Disconnected'), ('tool_called', 'Tool Called'), ('error', 'Error')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_audit_events', to='accounts.agentprofile')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_audit_events', to=settings.AUTH_USER_MODEL)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_audit_events', to='accounts.businessprofile')),
                ('integration_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.integrationaccount')),
            ],
            options={
                'db_table': 'accounts_integration_account_audit_event',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.AddIndex(
            model_name='integrationaccountauditevent',
            index=models.Index(fields=['integration_account', 'action'], name='integ_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationaccountauditevent',
            index=models.Index(fields=['integration_account_id_snapshot', 'action'], name='integ_audit_snap_action_idx'),
        ),
        migrations.CreateModel(
            name='IntegrationOAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('google_calendar', 'Google Calendar'), ('google_drive', 'Google Drive'), ('onedrive', 'OneDrive'), ('slack', 'Slack'), ('hubspot', 'HubSpot')], max_length=32)),
                ('state_token', models.CharField(max_length=128, unique=True)),
                ('redirect_after', models.URLField(blank=True, default='', max_length=500)),
                ('redirect_uri', models.URLField(blank=True, default='', max_length=500)),
                ('code_verifier', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_oauth_states', to='accounts.businessprofile')),
                ('provider', models.ForeignKey(help_text='OAuth provider configuration (e.g., google_calendar, slack_native).', on_delete=django.db.models.deletion.CASCADE, related_name='integration_oauth_states', to='accounts.oauthprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_integration_oauth_state',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='integrationoauthstate',
            index=models.Index(fields=['expires_at'], name='integ_oauth_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationoauthstate',
            index=models.Index(fields=['provider', 'is_used'], name='integ_oauth_prov_used_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationoauthstate',
            index=models.Index(fields=['business_profile', 'integration_type'], name='integ_oauth_biz_type_idx'),
        ),
    ]
