# Generated by Django 5.1.14 on 2026-05-17 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAssistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=24)),
                ('instructions', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_assistants', to='accounts.agentprofile')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_assistants', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_custom_assistants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistants_custom_assistant',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['business_profile', 'status'], name='asst_biz_status_idx'), models.Index(fields=['agent_profile', 'status'], name='asst_agent_status_idx'), models.Index(fields=['business_profile', 'created_at'], name='asst_biz_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent_profile', 'name'), name='asst_unique_agent_name')],
            },
        ),
    ]
