# Generated by Django 5.1.14 on 2026-05-17 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRunArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('file', 'File'), ('link', 'Link'), ('record', 'Record'), ('message', 'Message')], default='file', max_length=24)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True, default='')),
                ('reference_type', models.CharField(blank=True, default='', max_length=64)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'agent_runs_artifact',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentRunCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('approval', 'Approval'), ('user_input', 'User input'), ('child_run', 'Child run'), ('external', 'External')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=24)),
                ('title', models.CharField(blank=True, default='', max_length=240)),
                ('prompt', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resolution', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_runs_checkpoint',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentRunEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_index', models.PositiveIntegerField(help_text='Monotonic per-run ordering for deterministic playback.')),
                ('stream', models.CharField(choices=[('plan', 'Plan'), ('executed', 'Executed'), ('system', 'System')], default='system', max_length=16)),
                ('event_type', models.CharField(choices=[('progress', 'Progress'), ('needs_user', 'Needs user'), ('needs_approval', 'Needs approval'), ('needs_child', 'Needs child run'), ('result', 'Result'), ('error', 'Error'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], max_length=24)),
                ('label', models.CharField(blank=True, default='', max_length=240)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'agent_runs_event',
                'ordering': ('run_id', 'sequence_index'),
            },
        ),
        migrations.CreateModel(
            name='AgentRunNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('delivered', 'Delivered'), ('suppressed', 'Suppressed'), ('failed', 'Failed')], db_index=True, default='candidate', max_length=24)),
                ('kind', models.CharField(db_index=True, default='run_update', max_length=48)),
                ('priority', models.CharField(db_index=True, default='normal', max_length=24)),
                ('title', models.CharField(blank=True, default='', max_length=240)),
                ('body', models.TextField(blank=True, default='')),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_runs_notification',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_snapshot', models.JSONField(blank=True, default=dict, help_text='Immutable execution contract snapshot used for this run.')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('chat', 'Chat'), ('automation', 'Automation'), ('schedule', 'Schedule'), ('delegation', 'Delegation'), ('api', 'API')], default='chat', max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_user', 'Waiting for user'), ('waiting_approval', 'Waiting for approval'), ('waiting_child', 'Waiting for child run'), ('waiting_external', 'Waiting for external'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=24)),
                ('visibility', models.CharField(choices=[('initiator', 'Initiator'), ('managers', 'Managers'), ('workspace', 'Workspace')], default='initiator', max_length=24)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('run_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='accounts.agentprofile')),
            ],
            options={
                'db_table': 'agent_runs_agent_run',
                'ordering': ('-created_at',),
            },
        ),
    ]
