# Generated by Django 5.1.14 on 2026-05-17 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agent_runs', '0001_initial'),
        ('agentic_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='agentic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='agentic_tasks.agentictask'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='accounts.businessprofile'),
        ),
    ]
