# Generated by Django 5.1.14 on 2026-05-17 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agent_runs', '0002_initial'),
        ('automations', '0001_initial'),
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='Optional anchor conversation for chat-originated or automation-associated runs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='delegated_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_runs', to='accounts.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='execution_conversation',
            field=models.ForeignKey(blank=True, help_text='Isolated execution conversation for this run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_runs', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='parent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_runs', to='agent_runs.agentrun'),
        ),
        migrations.AddField(
            model_name='agentrunartifact',
            name='conversation_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_run_artifacts', to='conversations.conversationfile'),
        ),
        migrations.AddField(
            model_name='agentrunartifact',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='agent_runs.agentrun'),
        ),
        migrations.AddField(
            model_name='agentruncheckpoint',
            name='automation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkpoints', to='automations.automation'),
        ),
        migrations.AddField(
            model_name='agentruncheckpoint',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_run_checkpoints', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='agentruncheckpoint',
            name='child_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_checkpoints', to='agent_runs.agentrun'),
        ),
        migrations.AddField(
            model_name='agentruncheckpoint',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_run_checkpoints', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='agentruncheckpoint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_run_checkpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentruncheckpoint',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_agent_run_checkpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentruncheckpoint',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='agent_runs.agentrun'),
        ),
        migrations.AddField(
            model_name='agentrunevent',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agent_runs.agentrun'),
        ),
        migrations.AddField(
            model_name='agentrunnotification',
            name='agent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_run_notifications', to='accounts.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentrunnotification',
            name='automation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='automations.automation'),
        ),
        migrations.AddField(
            model_name='agentrunnotification',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_run_notifications', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='agentrunnotification',
            name='owner_agent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_run_notifications', to='accounts.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentrunnotification',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='agent_runs.agentrun'),
        ),
        migrations.AddField(
            model_name='agentrunnotification',
            name='target_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_run_notifications', to='conversations.conversation'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['business_profile', 'status'], name='run_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['agent_profile', 'status'], name='run_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', 'run_after'], name='run_status_run_after_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', 'lease_expires_at'], name='run_status_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['conversation', 'created_at'], name='run_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['business_profile', 'created_at'], name='run_biz_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['automation', 'created_at'], name='run_automation_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['parent_run', 'created_at'], name='run_parent_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunartifact',
            index=models.Index(fields=['run', 'created_at'], name='run_artifact_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunartifact',
            index=models.Index(fields=['run', 'kind'], name='run_artifact_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='agentruncheckpoint',
            index=models.Index(fields=['business_profile', 'status', 'updated_at'], name='checkpoint_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentruncheckpoint',
            index=models.Index(fields=['automation', 'status', 'updated_at'], name='checkpoint_auto_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentruncheckpoint',
            index=models.Index(fields=['run', 'status', 'created_at'], name='checkpoint_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentruncheckpoint',
            index=models.Index(fields=['status', 'expires_at'], name='checkpoint_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunevent',
            index=models.Index(fields=['run', 'sequence_index'], name='run_event_order_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunevent',
            index=models.Index(fields=['run', 'created_at'], name='run_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunevent',
            index=models.Index(fields=['run', 'event_type'], name='run_event_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentrunevent',
            constraint=models.UniqueConstraint(fields=('run', 'sequence_index'), name='run_event_unique_sequence'),
        ),
        migrations.AddIndex(
            model_name='agentrunnotification',
            index=models.Index(fields=['business_profile', 'status', 'created_at'], name='run_notif_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunnotification',
            index=models.Index(fields=['automation', 'created_at'], name='run_notif_automation_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunnotification',
            index=models.Index(fields=['run', 'created_at'], name='run_notif_run_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunnotification',
            index=models.Index(fields=['target_conversation', 'created_at'], name='run_notif_target_idx'),
        ),
    ]
