# Generated by Django 5.1.15 on 2026-02-12 14:49

import apps.integrations.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('authorization_url', models.URLField(max_length=500)),
                ('token_url', models.URLField(max_length=500)),
                ('client_id', models.CharField(max_length=500)),
                ('client_secret_encrypted', models.TextField(blank=True, default='')),
                ('client_secret_key_version', models.PositiveSmallIntegerField(default=1)),
                ('client_secret_last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('client_secret_error_count', models.PositiveSmallIntegerField(default=0)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('marketplace_keys', models.JSONField(blank=True, default=list, help_text="Marketplace keys that should use this provider (e.g. ['gmail', 'google_drive']).")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_oauth_provider',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google (Gmail/Workspace)'), ('microsoft', 'Microsoft (Outlook/M365)')], max_length=16)),
                ('email_address', models.EmailField(blank=True, db_index=True, default='', max_length=255)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('error', 'Error')], default='disconnected', max_length=16)),
                ('send_mode', models.CharField(choices=[('draft_approval', 'Draft + approval'), ('auto_send', 'Auto-send')], default='draft_approval', help_text='Default send behavior for this connected mailbox.', max_length=24)),
                ('policy_config', models.JSONField(blank=True, default=dict)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('credentials_key_version', models.PositiveSmallIntegerField(default=1)),
                ('credentials_last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('credential_error_count', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_health_checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='accounts.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_email_account',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentEmailAccountPolicyOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('send_mode', models.CharField(blank=True, choices=[('draft_approval', 'Draft + approval'), ('auto_send', 'Auto-send')], help_text='Override the email account default. NULL = inherit from EmailAccount.', max_length=24, null=True)),
                ('policy_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_policy_overrides', to='accounts.agentprofile')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_policy_overrides', to='integrations.emailaccount')),
            ],
            options={
                'db_table': 'accounts_agent_email_policy_override',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailAccountAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_account_id_snapshot', models.UUIDField(blank=True, db_index=True, help_text='Snapshot of the EmailAccount UUID for retention when the account is deleted.', null=True)),
                ('action', models.CharField(choices=[('connected', 'Connected'), ('updated', 'Updated'), ('disconnected', 'Disconnected'), ('searched', 'Searched'), ('read_message', 'Read message'), ('read_thread', 'Read thread'), ('draft_created', 'Draft created'), ('send_requested', 'Send requested'), ('send_approved', 'Send approved'), ('send_denied', 'Send denied'), ('sent', 'Sent'), ('error', 'Error')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_audit_events', to='accounts.agentprofile')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_audit_events', to=settings.AUTH_USER_MODEL)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_audit_events', to='accounts.businessprofile')),
                ('email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='integrations.emailaccount')),
            ],
            options={
                'db_table': 'accounts_email_account_audit_event',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailAccountHealthJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('trigger', models.CharField(blank=True, default='', max_length=48)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('run_after', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_account_health_jobs', to='accounts.businessprofile')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_jobs', to='integrations.emailaccount')),
            ],
            options={
                'db_table': 'accounts_email_account_health_job',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IntegrationAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('google_calendar', 'Google Calendar'), ('google_drive', 'Google Drive'), ('onedrive', 'OneDrive'), ('slack', 'Slack'), ('hubspot', 'HubSpot')], max_length=32)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('slack', 'Slack'), ('hubspot', 'HubSpot')], max_length=16)),
                ('account_identifier', models.CharField(blank=True, default='', help_text='Email address, workspace name, or other human-readable identifier.', max_length=320)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=320)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('error', 'Error')], default='disconnected', max_length=16)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('credentials_key_version', models.PositiveSmallIntegerField(default=1)),
                ('credentials_last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('credential_error_count', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_health_checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_accounts', to='accounts.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_integration_account',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IntegrationAccountAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_account_id_snapshot', models.UUIDField(blank=True, db_index=True, help_text='Snapshot of the IntegrationAccount UUID for retention when the account is deleted.', null=True)),
                ('action', models.CharField(choices=[('connected', 'Connected'), ('updated', 'Updated'), ('disconnected', 'Disconnected'), ('tool_called', 'Tool Called'), ('error', 'Error')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_audit_events', to='accounts.agentprofile')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_audit_events', to=settings.AUTH_USER_MODEL)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_audit_events', to='accounts.businessprofile')),
                ('integration_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'accounts_integration_account_audit_event',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, default='', max_length=160)),
                ('integration_type', models.CharField(choices=[('custom', 'Custom'), ('notion', 'Notion'), ('google_drive', 'Google Drive'), ('zendesk', 'Zendesk'), ('hubspot', 'HubSpot'), ('slack', 'Slack'), ('confluence', 'Confluence')], default='custom', max_length=32)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('syncing', 'Syncing'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='connected', max_length=32)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('credentials_key_version', models.PositiveSmallIntegerField(default=1)),
                ('credentials_last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('credential_error_count', models.PositiveSmallIntegerField(default=0)),
                ('settings', models.JSONField(blank=True, default=apps.integrations.models.default_knowledge_integration_settings)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_integrations', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_knowledge_integration',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredentialEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('refreshed', 'Refreshed'), ('error', 'Error'), ('cleared', 'Cleared'), ('rotation_required', 'Rotation Required')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_credential_events', to='accounts.businessprofile')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_credential_events', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_events', to='integrations.knowledgeintegration')),
            ],
            options={
                'db_table': 'accounts_integration_credential_event',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IntegrationOAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('google_calendar', 'Google Calendar'), ('google_drive', 'Google Drive'), ('onedrive', 'OneDrive'), ('slack', 'Slack'), ('hubspot', 'HubSpot')], max_length=32)),
                ('state_token', models.CharField(max_length=128, unique=True)),
                ('redirect_after', models.URLField(blank=True, default='', max_length=500)),
                ('redirect_uri', models.URLField(blank=True, default='', max_length=500)),
                ('code_verifier', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_oauth_states', to='accounts.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_oauth_states', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='OAuth provider configuration (e.g., google_calendar, slack_native).', on_delete=django.db.models.deletion.CASCADE, related_name='integration_oauth_states', to='integrations.oauthprovider')),
            ],
            options={
                'db_table': 'accounts_integration_oauth_state',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailOAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_provider', models.CharField(choices=[('google', 'Google (Gmail/Workspace)'), ('microsoft', 'Microsoft (Outlook/M365)')], max_length=16)),
                ('state_token', models.CharField(max_length=128, unique=True)),
                ('redirect_after', models.URLField(blank=True, default='', max_length=500)),
                ('redirect_uri', models.URLField(blank=True, default='', max_length=500)),
                ('code_verifier', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_oauth_states', to='accounts.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_oauth_states', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='OAuth provider configuration (e.g., google_email, microsoft_email).', on_delete=django.db.models.deletion.CASCADE, related_name='email_oauth_states', to='integrations.oauthprovider')),
            ],
            options={
                'db_table': 'accounts_email_oauth_state',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marketplace_key', models.CharField(max_length=100)),
                ('state_token', models.CharField(max_length=128, unique=True)),
                ('redirect_after', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to='accounts.businessprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to='integrations.oauthprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_oauth_state',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['business_profile', 'status'], name='email_acct_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['business_profile', 'provider'], name='email_acct_biz_provider_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailaccount',
            constraint=models.UniqueConstraint(fields=('business_profile', 'user'), name='email_account_unique_user'),
        ),
        migrations.AddIndex(
            model_name='agentemailaccountpolicyoverride',
            index=models.Index(fields=['agent_profile', 'email_account'], name='agent_email_ov_agent_acct_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentemailaccountpolicyoverride',
            constraint=models.UniqueConstraint(fields=('agent_profile', 'email_account'), name='agent_email_policy_override_uniq'),
        ),
        migrations.AddIndex(
            model_name='emailaccountauditevent',
            index=models.Index(fields=['email_account', 'action'], name='email_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaccountauditevent',
            index=models.Index(fields=['email_account_id_snapshot', 'action'], name='email_audit_snap_action_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaccounthealthjob',
            index=models.Index(fields=['status', 'run_after'], name='email_health_run_after_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaccounthealthjob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='email_health_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaccounthealthjob',
            index=models.Index(fields=['email_account', 'status'], name='email_health_acct_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaccounthealthjob',
            index=models.Index(fields=['business_profile', 'status'], name='email_health_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationaccount',
            index=models.Index(fields=['business_profile', 'status'], name='integ_acct_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationaccount',
            index=models.Index(fields=['business_profile', 'integration_type'], name='integ_acct_biz_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationaccount',
            constraint=models.UniqueConstraint(fields=('business_profile', 'user', 'integration_type'), name='integration_account_unique_user_type'),
        ),
        migrations.AddIndex(
            model_name='integrationaccountauditevent',
            index=models.Index(fields=['integration_account', 'action'], name='integ_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationaccountauditevent',
            index=models.Index(fields=['integration_account_id_snapshot', 'action'], name='integ_audit_snap_action_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeintegration',
            index=models.Index(fields=['business_profile', 'integration_type'], name='knowledge_integration_type_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeintegration',
            index=models.Index(fields=['business_profile', 'slug'], name='knowledge_integration_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeintegration',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('business_profile', 'slug'), name='knowledge_integr_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='integrationcredentialevent',
            index=models.Index(fields=['integration', 'event_type'], name='integration_cred_evt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationoauthstate',
            index=models.Index(fields=['expires_at'], name='integ_oauth_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationoauthstate',
            index=models.Index(fields=['provider', 'is_used'], name='integ_oauth_prov_used_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationoauthstate',
            index=models.Index(fields=['business_profile', 'integration_type'], name='integ_oauth_biz_type_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoauthstate',
            index=models.Index(fields=['expires_at'], name='email_oauth_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoauthstate',
            index=models.Index(fields=['provider', 'is_used'], name='email_oauth_prov_used_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoauthstate',
            index=models.Index(fields=['business_profile', 'email_provider'], name='email_oauth_biz_prov_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthstate',
            index=models.Index(fields=['expires_at'], name='oauth_state_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthstate',
            index=models.Index(fields=['provider', 'is_used'], name='oauth_state_provider_used_idx'),
        ),
    ]
