# Generated by Django 5.1.13 on 2025-11-06 23:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_businessprofile_slug_and_more'),
        ('cases', '0002_case_customer_alter_case_customer_reference_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, max_length=96, unique=True)),
                ('channel', models.CharField(choices=[('web_widget', 'Web Widget'), ('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('api', 'API'), ('email', 'Email'), ('other', 'Other')], default='web_widget', max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('live', 'Live'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed'), ('expired', 'Expired')], default='new', max_length=24)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('first_customer_message_at', models.DateTimeField(blank=True, null=True)),
                ('first_ai_message_at', models.DateTimeField(blank=True, null=True)),
                ('csat_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('csat_comment', models.TextField(blank=True)),
                ('csat_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='accounts.agentprofile')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.businessprofile')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='cases.case')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='customers.customer')),
            ],
            options={
                'db_table': 'conversations_conversation',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ConversationExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extraction_type', models.CharField(choices=[('case', 'Case'), ('lead', 'Lead'), ('appointment', 'Appointment'), ('escalation', 'Escalation'), ('complaint', 'Complaint'), ('note', 'Note')], max_length=24)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='conversations.conversation')),
            ],
            options={
                'db_table': 'conversations_conversation_extraction',
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('ai', 'AI'), ('system', 'System')], max_length=16)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'db_table': 'conversations_conversation_message',
                'ordering': ('sent_at', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business_profile', 'status'], name='conv_business_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business_profile', 'last_activity_at'], name='conv_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationextraction',
            index=models.Index(fields=['conversation', 'extraction_type'], name='conv_extract_type_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'sent_at'], name='conv_message_time_idx'),
        ),
    ]
