# Generated by Django 5.1.14 on 2026-05-17 14:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('automations', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, max_length=96, unique=True)),
                ('channel', models.CharField(choices=[('web_widget', 'Web Widget'), ('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('api', 'API'), ('email', 'Email'), ('other', 'Other')], default='web_widget', max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('live', 'Live'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed'), ('expired', 'Expired')], default='new', max_length=24)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('first_customer_message_at', models.DateTimeField(blank=True, null=True)),
                ('first_ai_message_at', models.DateTimeField(blank=True, null=True)),
                ('csat_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('csat_comment', models.TextField(blank=True)),
                ('csat_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='accounts.agentprofile')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.businessprofile')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations_conversation',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='CompactedHistorySegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_range', models.CharField(max_length=64)),
                ('start_message_id', models.UUIDField()),
                ('end_message_id', models.UUIDField()),
                ('start_message_sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_message_sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('summary', models.TextField()),
                ('full_messages', models.JSONField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('extracted_facts', models.JSONField(blank=True, default=dict)),
                ('extracted_decisions', models.JSONField(blank=True, default=dict)),
                ('token_count_original', models.IntegerField()),
                ('token_count_summary', models.IntegerField()),
                ('compression_ratio', models.FloatField()),
                ('compacted_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compacted_segments', to='conversations.conversation')),
            ],
            options={
                'db_table': 'conversations_compacted_history_segment',
                'ordering': ('-compacted_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=24)),
                ('subject', models.CharField(blank=True, default='', max_length=240)),
                ('question', models.TextField(blank=True, default='')),
                ('context_refs', models.JSONField(blank=True, default=list, help_text='Structured context references (no raw dumps).')),
                ('resolution', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_requests', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_requests', to=settings.AUTH_USER_MODEL)),
                ('from_agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_requests_sent', to='accounts.agentprofile')),
                ('to_agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_requests_received', to='accounts.agentprofile')),
                ('conversation', models.ForeignKey(blank=True, help_text='Optional anchor conversation for context and traceability.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_requests', to='conversations.conversation')),
            ],
            options={
                'db_table': 'conversations_agent_request',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConversationExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extraction_type', models.CharField(choices=[('case', 'Case'), ('lead', 'Lead'), ('appointment', 'Appointment'), ('escalation', 'Escalation'), ('complaint', 'Complaint'), ('note', 'Note')], max_length=24)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='conversations.conversation')),
            ],
            options={
                'db_table': 'conversations_conversation_extraction',
            },
        ),
        migrations.CreateModel(
            name='ConversationFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('upload', 'Upload'), ('artifact', 'Artifact')], default='upload', max_length=24)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=24)),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('ai', 'AI'), ('system', 'System')], default='customer', max_length=16)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('storage_path', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=128)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_files', to='accounts.businessprofile')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='conversations.conversation')),
            ],
            options={
                'db_table': 'conversations_conversation_file',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConversationFileChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_file_chunks', to='accounts.businessprofile')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_chunks', to='conversations.conversation')),
                ('conversation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='conversations.conversationfile')),
            ],
            options={
                'db_table': 'conversations_conversation_file_chunk',
                'ordering': ('conversation_file_id', 'chunk_index'),
            },
        ),
        migrations.CreateModel(
            name='ConversationMaintenanceJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('compact_history', 'Compact History')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=24)),
                ('run_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=10)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_maintenance_jobs', to='accounts.businessprofile')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_jobs', to='conversations.conversation')),
            ],
            options={
                'db_table': 'conversations_conversation_maintenance_job',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('ai', 'AI'), ('system', 'System')], max_length=16)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_blocks', models.JSONField(blank=True, default=list)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'db_table': 'conversations_conversation_message',
                'ordering': ('sent_at', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ConversationFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('not_found_incorrect', 'Not Found Incorrect'), ('other', 'Other')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='conversations.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='conversations.conversationmessage')),
            ],
            options={
                'db_table': 'conversations_conversation_feedback',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MemoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('workspace', 'Workspace'), ('agent', 'Agent'), ('automation', 'Automation'), ('run', 'Run'), ('conversation', 'Conversation'), ('crm_contact', 'CRM contact'), ('crm_company', 'CRM company')], db_index=True, default='workspace', max_length=32)),
                ('kind', models.CharField(choices=[('fact', 'Fact'), ('preference', 'Preference'), ('policy', 'Policy'), ('decision', 'Decision'), ('instruction', 'Instruction'), ('relationship', 'Relationship'), ('state_note', 'State note'), ('artifact_ref', 'Artifact reference'), ('extracted_data', 'Extracted data')], db_index=True, default='fact', max_length=32)),
                ('key', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('content', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], db_index=True, default='shared', max_length=16)),
                ('sensitivity', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive'), ('secret', 'Secret')], db_index=True, default='normal', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_review', 'Pending review'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=24)),
                ('source_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_items', to='accounts.agentprofile')),
                ('automation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_items', to='automations.automation')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_items', to='accounts.businessprofile')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_items', to='conversations.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memory_items', to=settings.AUTH_USER_MODEL)),
                ('crm_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_items', to='crm.crmcompany')),
                ('crm_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_items', to='crm.crmcontact')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_memory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations_memory_item',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='MemoryAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('promoted', 'Promoted')], max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_audit_events', to=settings.AUTH_USER_MODEL)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_audit_events', to='accounts.businessprofile')),
                ('memory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='conversations.memoryitem')),
            ],
            options={
                'db_table': 'conversations_memory_audit_event',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='PortalTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('streaming', 'Streaming'), ('waiting_approval', 'Waiting approval'), ('finalizing', 'Finalizing'), ('finalized', 'Finalized'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='streaming', max_length=24)),
                ('last_event_seq', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('run_after', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_turns', to='accounts.agentprofile')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_turns', to='conversations.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_turns', to='conversations.conversationmessage')),
            ],
            options={
                'db_table': 'conversations_portal_turn',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ConversationToolApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=128)),
                ('remote_tool_name', models.CharField(blank=True, default='', max_length=128)),
                ('tool_call_id', models.CharField(blank=True, default='', max_length=128)),
                ('event_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_approvals', to='conversations.conversation')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn_approvals', to='conversations.portalturn')),
            ],
            options={
                'db_table': 'conversations_conversation_tool_approval',
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='PortalTurnEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='conversations.portalturn')),
            ],
            options={
                'db_table': 'conversations_portal_turn_event',
                'ordering': ('seq',),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business_profile', 'status'], name='conv_business_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business_profile', 'last_activity_at'], name='conv_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['owner_user', 'business_profile', 'last_activity_at'], name='conv_owner_biz_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='compactedhistorysegment',
            index=models.Index(fields=['conversation', 'compacted_at'], name='conv_compacted_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='compactedhistorysegment',
            constraint=models.UniqueConstraint(fields=('conversation', 'start_message_id', 'end_message_id'), name='uniq_compacted_history_segment_bounds'),
        ),
        migrations.AddIndex(
            model_name='agentrequest',
            index=models.Index(fields=['business_profile', 'status'], name='agent_request_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrequest',
            index=models.Index(fields=['to_agent_profile', 'status'], name='agent_request_to_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrequest',
            index=models.Index(fields=['from_agent_profile', 'created_at'], name='agent_request_from_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrequest',
            index=models.Index(fields=['business_profile', 'created_at'], name='agent_request_biz_created_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationextraction',
            index=models.Index(fields=['conversation', 'extraction_type'], name='conv_extract_type_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfile',
            index=models.Index(fields=['business_profile', 'created_at'], name='conv_file_biz_created_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfile',
            index=models.Index(fields=['conversation', 'created_at'], name='conv_file_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfile',
            index=models.Index(fields=['conversation', 'kind'], name='conv_file_conv_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfilechunk',
            index=models.Index(fields=['conversation_file', 'chunk_index'], name='conv_file_chunk_window_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfilechunk',
            index=models.Index(fields=['conversation', 'chunk_index'], name='conv_file_chunk_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfilechunk',
            index=models.Index(fields=['business_profile', 'conversation'], name='conv_file_chunk_biz_conv_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationfilechunk',
            constraint=models.UniqueConstraint(fields=('conversation_file', 'chunk_index'), name='conv_file_chunk_unique_index'),
        ),
        migrations.AddIndex(
            model_name='conversationmaintenancejob',
            index=models.Index(fields=['business_profile', 'status'], name='job_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmaintenancejob',
            index=models.Index(fields=['status', 'run_after'], name='job_status_run_after_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmaintenancejob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='job_status_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmaintenancejob',
            index=models.Index(fields=['conversation', 'created_at'], name='job_conv_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmaintenancejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('conversation', 'kind'), name='uniq_active_conversation_maintenance_job'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'sent_at'], name='conv_message_time_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfeedback',
            index=models.Index(fields=['conversation', 'feedback_type'], name='conv_feedback_type_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['business_profile', 'status', 'visibility'], name='mem_biz_status_vis_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['business_profile', 'scope', 'status'], name='memory_biz_scope_status_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['agent_profile', 'status', 'updated_at'], name='memory_agent_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['automation', 'status', 'updated_at'], name='mem_auto_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['conversation', 'created_at'], name='memory_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['crm_contact', 'status'], name='memory_contact_status_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['crm_company', 'status'], name='memory_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryauditevent',
            index=models.Index(fields=['business_profile', 'occurred_at'], name='memory_audit_biz_time_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryauditevent',
            index=models.Index(fields=['memory_item', 'occurred_at'], name='memory_audit_item_time_idx'),
        ),
        migrations.AddIndex(
            model_name='portalturn',
            index=models.Index(fields=['conversation', 'status'], name='portal_turn_conv_status_idx'),
        ),
        migrations.AddIndex(
            model_name='portalturn',
            index=models.Index(fields=['status', 'run_after'], name='portal_turn_status_run_idx'),
        ),
        migrations.AddIndex(
            model_name='portalturn',
            index=models.Index(fields=['status', 'lease_expires_at'], name='portal_turn_status_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='portalturn',
            index=models.Index(fields=['conversation', 'created_at'], name='portal_turn_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationtoolapproval',
            index=models.Index(fields=['conversation', 'status'], name='conv_tool_approval_status_idx'),
        ),
        migrations.AddIndex(
            model_name='portalturnevent',
            index=models.Index(fields=['turn', 'created_at'], name='portal_turn_event_time_idx'),
        ),
        migrations.AddIndex(
            model_name='portalturnevent',
            index=models.Index(fields=['turn', 'type'], name='portal_turn_event_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='portalturnevent',
            constraint=models.UniqueConstraint(fields=('turn', 'seq'), name='portal_turn_event_seq_unique'),
        ),
    ]
