# Generated by Django 5.1.15 on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
        ("mcp", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE conversations_conversation_tool_approval
                    ADD COLUMN IF NOT EXISTS connection_id uuid NULL;

                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint c
                            JOIN pg_attribute a
                              ON a.attrelid = c.conrelid
                             AND a.attnum = ANY(c.conkey)
                            WHERE c.conrelid = 'conversations_conversation_tool_approval'::regclass
                              AND c.contype = 'f'
                              AND a.attname = 'connection_id'
                        ) THEN
                            ALTER TABLE conversations_conversation_tool_approval
                            ADD CONSTRAINT conv_tool_approval_connection_fk
                            FOREIGN KEY (connection_id)
                            REFERENCES accounts_mcp_connection(id)
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                    END $$;

                    CREATE INDEX IF NOT EXISTS conv_tool_approval_conn_idx
                    ON conversations_conversation_tool_approval (connection_id, status);
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="conversationtoolapproval",
                    name="connection",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_approvals",
                        to="mcp.mcpconnection",
                    ),
                ),
                migrations.AddIndex(
                    model_name="conversationtoolapproval",
                    index=models.Index(fields=["connection", "status"], name="conv_tool_approval_conn_idx"),
                ),
            ],
        ),
    ]
