# Generated by Django 5.1.15 on 2026-02-12 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('conversations', '0001_initial'),
        ('mcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationtoolapproval',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_approvals', to='mcp.mcpconnection'),
        ),
        migrations.AddField(
            model_name='conversationtoolapproval',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_approvals', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='identifierevent',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier_events', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='identifierevent',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identifier_events', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='portalturn',
            name='agent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_turns', to='accounts.agentprofile'),
        ),
        migrations.AddField(
            model_name='portalturn',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_turns', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='portalturn',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_turns', to='conversations.conversationmessage'),
        ),
        migrations.AddField(
            model_name='conversationtoolapproval',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn_approvals', to='conversations.portalturn'),
        ),
        migrations.AddField(
            model_name='portalturnevent',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='conversations.portalturn'),
        ),
        migrations.AddIndex(
            model_name='agentrunevent',
            index=models.Index(fields=['run', 'sequence_index'], name='run_event_order_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunevent',
            index=models.Index(fields=['run', 'created_at'], name='run_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunevent',
            index=models.Index(fields=['run', 'event_type'], name='run_event_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentrunevent',
            constraint=models.UniqueConstraint(fields=('run', 'sequence_index'), name='run_event_unique_sequence'),
        ),
        migrations.AddIndex(
            model_name='agentrunmemoryitem',
            index=models.Index(fields=['run', 'created_at'], name='run_memory_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunmemoryitem',
            index=models.Index(fields=['run', 'kind'], name='run_memory_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunspec',
            index=models.Index(fields=['business_profile', 'status'], name='run_spec_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunspec',
            index=models.Index(fields=['agent_profile', 'status'], name='run_spec_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunspec',
            index=models.Index(fields=['business_profile', 'created_at'], name='run_spec_biz_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentrunspec',
            constraint=models.UniqueConstraint(fields=('agent_profile', 'name'), name='run_spec_unique_agent_name'),
        ),
        migrations.AddIndex(
            model_name='agentwatcherdedupekey',
            index=models.Index(fields=['watcher', 'created_at'], name='watcher_dedupe_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentwatcherdedupekey',
            index=models.Index(fields=['business_profile', 'created_at'], name='watcher_dedupe_biz_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentwatcherdedupekey',
            constraint=models.UniqueConstraint(fields=('watcher', 'dedupe_key'), name='watcher_dedupe_unique_key'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business_profile', 'status'], name='conv_business_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business_profile', 'last_activity_at'], name='conv_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='compactedhistorysegment',
            index=models.Index(fields=['conversation', 'compacted_at'], name='conv_compacted_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='compactedhistorysegment',
            constraint=models.UniqueConstraint(fields=('conversation', 'start_message_id', 'end_message_id'), name='uniq_compacted_history_segment_bounds'),
        ),
        migrations.AddIndex(
            model_name='agentwatcher',
            index=models.Index(fields=['business_profile', 'status'], name='watcher_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentwatcher',
            index=models.Index(fields=['agent_profile', 'status'], name='watcher_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentwatcher',
            index=models.Index(fields=['status', 'next_poll_at'], name='watcher_status_next_poll_idx'),
        ),
        migrations.AddIndex(
            model_name='agentwatcher',
            index=models.Index(fields=['status', 'lease_expires_at'], name='watcher_status_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentwatcher',
            constraint=models.UniqueConstraint(fields=('agent_profile', 'name'), name='watcher_unique_agent_name'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['business_profile', 'status'], name='run_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['agent_profile', 'status'], name='run_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', 'run_after'], name='run_status_run_after_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', 'lease_expires_at'], name='run_status_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['conversation', 'created_at'], name='run_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['business_profile', 'created_at'], name='run_biz_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrequest',
            index=models.Index(fields=['business_profile', 'status'], name='agent_request_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrequest',
            index=models.Index(fields=['to_agent_profile', 'status'], name='agent_request_to_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrequest',
            index=models.Index(fields=['from_agent_profile', 'created_at'], name='agent_request_from_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrequest',
            index=models.Index(fields=['business_profile', 'created_at'], name='agent_request_biz_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentautomation',
            index=models.Index(fields=['business_profile', 'status'], name='automation_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentautomation',
            index=models.Index(fields=['agent_profile', 'status'], name='automation_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentautomation',
            index=models.Index(fields=['status', 'next_trigger_at'], name='automation_status_next_idx'),
        ),
        migrations.AddIndex(
            model_name='agentautomation',
            index=models.Index(fields=['business_profile', 'created_at'], name='automation_biz_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentautomation',
            constraint=models.UniqueConstraint(fields=('agent_profile', 'name'), name='automation_unique_agent_name'),
        ),
        migrations.AddIndex(
            model_name='conversationextraction',
            index=models.Index(fields=['conversation', 'extraction_type'], name='conv_extract_type_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfile',
            index=models.Index(fields=['business_profile', 'created_at'], name='conv_file_biz_created_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfile',
            index=models.Index(fields=['conversation', 'created_at'], name='conv_file_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfile',
            index=models.Index(fields=['conversation', 'kind'], name='conv_file_conv_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunartifact',
            index=models.Index(fields=['run', 'created_at'], name='run_artifact_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunartifact',
            index=models.Index(fields=['run', 'kind'], name='run_artifact_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfilechunk',
            index=models.Index(fields=['conversation_file', 'chunk_index'], name='conv_file_chunk_window_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfilechunk',
            index=models.Index(fields=['conversation', 'chunk_index'], name='conv_file_chunk_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfilechunk',
            index=models.Index(fields=['business_profile', 'conversation'], name='conv_file_chunk_biz_conv_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationfilechunk',
            constraint=models.UniqueConstraint(fields=('conversation_file', 'chunk_index'), name='conv_file_chunk_unique_index'),
        ),
        migrations.AddIndex(
            model_name='conversationmaintenancejob',
            index=models.Index(fields=['business_profile', 'status'], name='job_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmaintenancejob',
            index=models.Index(fields=['status', 'run_after'], name='job_status_run_after_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmaintenancejob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='job_status_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmaintenancejob',
            index=models.Index(fields=['conversation', 'created_at'], name='job_conv_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmaintenancejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('conversation', 'kind'), name='uniq_active_conversation_maintenance_job'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'sent_at'], name='conv_message_time_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationfeedback',
            index=models.Index(fields=['conversation', 'feedback_type'], name='conv_feedback_type_idx'),
        ),
        migrations.AddIndex(
            model_name='identifierevent',
            index=models.Index(fields=['business_profile', 'status'], name='identifier_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='identifierevent',
            index=models.Index(fields=['business_profile', 'created_at'], name='identifier_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='portalturn',
            index=models.Index(fields=['conversation', 'status'], name='portal_turn_conv_status_idx'),
        ),
        migrations.AddIndex(
            model_name='portalturn',
            index=models.Index(fields=['status', 'run_after'], name='portal_turn_status_run_idx'),
        ),
        migrations.AddIndex(
            model_name='portalturn',
            index=models.Index(fields=['status', 'lease_expires_at'], name='portal_turn_status_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='portalturn',
            index=models.Index(fields=['conversation', 'created_at'], name='portal_turn_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationtoolapproval',
            index=models.Index(fields=['conversation', 'status'], name='conv_tool_approval_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationtoolapproval',
            index=models.Index(fields=['connection', 'status'], name='conv_tool_approval_conn_idx'),
        ),
        migrations.AddIndex(
            model_name='portalturnevent',
            index=models.Index(fields=['turn', 'created_at'], name='portal_turn_event_time_idx'),
        ),
        migrations.AddIndex(
            model_name='portalturnevent',
            index=models.Index(fields=['turn', 'type'], name='portal_turn_event_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='portalturnevent',
            constraint=models.UniqueConstraint(fields=('turn', 'seq'), name='portal_turn_event_seq_unique'),
        ),
    ]
