# Generated by Django 5.1.14 on 2025-11-13 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('not_found_incorrect', 'Not Found Incorrect'), ('other', 'Other')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='conversations.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='conversations.conversationmessage')),
            ],
            options={
                'db_table': 'conversations_conversation_feedback',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['conversation', 'feedback_type'], name='conv_feedback_type_idx')],
            },
        ),
    ]
