# Generated by Django 5.1.14 on 2026-05-12 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_workflow_departments(apps, schema_editor):
    AgentWorkflow = apps.get_model("conversations", "AgentWorkflow")
    for workflow in AgentWorkflow.objects.filter(department__isnull=True).select_related("agent_profile"):
        department_id = getattr(workflow.agent_profile, "department_id", None)
        if department_id:
            AgentWorkflow.objects.filter(id=workflow.id).update(department_id=department_id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agentprofile_agent_type_and_more'),
        ('conversations', '0004_existing_db_drop_old_run_snapshot_requirement'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentworkflow',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='accounts.agentdepartment'),
        ),
        migrations.RunPython(backfill_workflow_departments, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='agentworkflow',
            index=models.Index(fields=['department', 'status'], name='workflow_dept_status_idx'),
        ),
    ]
