# Generated by Codex on 2026-05-13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_agentprofile_agent_type_and_more"),
        ("conversations", "0004_existing_db_drop_old_run_snapshot_requirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentworkflow",
            name="autonomy_mode",
            field=models.CharField(
                choices=[
                    ("suggest_only", "Suggest only"),
                    ("draft_for_approval", "Draft for approval"),
                    ("autonomous_with_policy", "Autonomous with policy"),
                    ("full_autonomy_explicit", "Full autonomy explicit"),
                ],
                db_index=True,
                default="draft_for_approval",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="agentworkflow",
            name="notification_config",
            field=models.JSONField(blank=True, default=dict, help_text="Delivery preferences for workflow notifications. Ownership stays separate from delivery."),
        ),
        migrations.AddField(
            model_name="agentworkflow",
            name="review_mode",
            field=models.CharField(
                choices=[("none", "None"), ("on_risk", "On risk"), ("always", "Always")],
                db_index=True,
                default="on_risk",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="AgentRunNotification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("candidate", "Candidate"), ("delivered", "Delivered"), ("suppressed", "Suppressed"), ("failed", "Failed")], db_index=True, default="candidate", max_length=24)),
                ("kind", models.CharField(db_index=True, default="run_update", max_length=48)),
                ("priority", models.CharField(db_index=True, default="normal", max_length=24)),
                ("title", models.CharField(blank=True, default="", max_length=240)),
                ("body", models.TextField(blank=True, default="")),
                ("dedupe_key", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent_profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_run_notifications", to="accounts.agentprofile")),
                ("business_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_run_notifications", to="accounts.businessprofile")),
                ("owner_agent_profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="owned_run_notifications", to="accounts.agentprofile")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="conversations.agentrun")),
                ("target_conversation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_run_notifications", to="conversations.conversation")),
                ("workflow", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications", to="conversations.agentworkflow")),
            ],
            options={
                "db_table": "conversations_agent_run_notification",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="agentrunnotification",
            index=models.Index(fields=["business_profile", "status", "created_at"], name="run_notif_biz_status_idx"),
        ),
        migrations.AddIndex(
            model_name="agentrunnotification",
            index=models.Index(fields=["workflow", "created_at"], name="run_notif_workflow_idx"),
        ),
        migrations.AddIndex(
            model_name="agentrunnotification",
            index=models.Index(fields=["run", "created_at"], name="run_notif_run_idx"),
        ),
        migrations.AddIndex(
            model_name="agentrunnotification",
            index=models.Index(fields=["target_conversation", "created_at"], name="run_notif_target_idx"),
        ),
    ]
