# Generated by Django 5.1.13 on 2026-01-22 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_conversation_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationfile',
            name='size_bytes',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
