# Generated by Django 5.1.13 on 2026-01-28 00:00

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_alter_emailaccountauditevent_action"),
        ("conversations", "0007_alter_conversationfile_size_bytes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRunSpec",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "business_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_run_specs",
                        to="accounts.businessprofile",
                    ),
                ),
                (
                    "agent_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_specs",
                        to="accounts.agentprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_run_specs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("archived", "Archived")],
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("initiator", "Initiator"), ("managers", "Managers"), ("workspace", "Workspace")],
                        default="initiator",
                        max_length=24,
                    ),
                ),
                (
                    "spec",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Serialized RunSpec payload (goal, tools, constraints, output schema, approvals).",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "conversations_agent_run_spec",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["business_profile", "status"], name="run_spec_biz_status_idx"),
                    models.Index(fields=["agent_profile", "status"], name="run_spec_agent_status_idx"),
                    models.Index(fields=["business_profile", "created_at"], name="run_spec_biz_created_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="agentrunspec",
            constraint=models.UniqueConstraint(fields=("agent_profile", "name"), name="run_spec_unique_agent_name"),
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "business_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="accounts.businessprofile",
                    ),
                ),
                (
                    "agent_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="accounts.agentprofile",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional anchor conversation (chat-originated run or automation thread).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="conversations.agentrunspec",
                    ),
                ),
                (
                    "run_spec_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Immutable RunSpec snapshot used for this run (copied from run_spec at creation time).",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[("chat", "Chat"), ("automation", "Automation"), ("watcher", "Watcher"), ("api", "API")],
                        default="chat",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("waiting_user", "Waiting for user"),
                            ("waiting_approval", "Waiting for approval"),
                            ("waiting_external", "Waiting for external"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=24,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("initiator", "Initiator"), ("managers", "Managers"), ("workspace", "Workspace")],
                        default="initiator",
                        max_length=24,
                    ),
                ),
                (
                    "plan",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Planner output (intended steps). This is separate from executed logs.",
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict, help_text="Final structured result payload (if any).")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("run_after", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "conversations_agent_run",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["business_profile", "status"], name="run_biz_status_idx"),
                    models.Index(fields=["agent_profile", "status"], name="run_agent_status_idx"),
                    models.Index(fields=["status", "run_after"], name="run_status_run_after_idx"),
                    models.Index(fields=["status", "lease_expires_at"], name="run_status_lease_idx"),
                    models.Index(fields=["conversation", "created_at"], name="run_conv_created_idx"),
                    models.Index(fields=["business_profile", "created_at"], name="run_biz_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentRunEvent",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="conversations.agentrun",
                    ),
                ),
                (
                    "sequence_index",
                    models.PositiveIntegerField(help_text="Monotonic per-run ordering for deterministic playback."),
                ),
                (
                    "stream",
                    models.CharField(
                        choices=[("plan", "Plan"), ("executed", "Executed"), ("system", "System")],
                        default="system",
                        max_length=16,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("progress", "Progress"),
                            ("needs_user", "Needs user"),
                            ("needs_approval", "Needs approval"),
                            ("result", "Result"),
                            ("error", "Error"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=24,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=240)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "conversations_agent_run_event",
                "ordering": ("run_id", "sequence_index"),
                "indexes": [
                    models.Index(fields=["run", "sequence_index"], name="run_event_order_idx"),
                    models.Index(fields=["run", "created_at"], name="run_event_created_idx"),
                    models.Index(fields=["run", "event_type"], name="run_event_type_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="agentrunevent",
            constraint=models.UniqueConstraint(fields=("run", "sequence_index"), name="run_event_unique_sequence"),
        ),
        migrations.CreateModel(
            name="AgentRunArtifact",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="conversations.agentrun",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("file", "File"), ("link", "Link"), ("record", "Record"), ("message", "Message")],
                        default="file",
                        max_length=24,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                (
                    "conversation_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_run_artifacts",
                        to="conversations.conversationfile",
                    ),
                ),
                ("url", models.URLField(blank=True, default="")),
                ("reference_type", models.CharField(blank=True, default="", max_length=64)),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "conversations_agent_run_artifact",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["run", "created_at"], name="run_artifact_created_idx"),
                    models.Index(fields=["run", "kind"], name="run_artifact_kind_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentRunMemoryItem",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_items",
                        to="conversations.agentrun",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("fact", "Fact"), ("sop", "SOP"), ("decision", "Decision"), ("note", "Note")],
                        max_length=24,
                    ),
                ),
                ("key", models.CharField(blank=True, db_index=True, default="", max_length=160)),
                ("content", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agent_run_memory_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "conversations_agent_run_memory_item",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["run", "created_at"], name="run_memory_created_idx"),
                    models.Index(fields=["run", "kind"], name="run_memory_kind_idx"),
                ],
            },
        ),
    ]

