# Generated by Django 5.1.13 on 2026-01-28 00:00

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_alter_emailaccountauditevent_action"),
        ("conversations", "0008_agent_runs_core_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAutomation",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "business_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_automations",
                        to="accounts.businessprofile",
                    ),
                ),
                (
                    "agent_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automations",
                        to="accounts.agentprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agent_automations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automations",
                        to="conversations.agentrunspec",
                    ),
                ),
                (
                    "run_spec_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Immutable RunSpec snapshot used when spawning runs from this automation.",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional automation thread conversation used as the default destination for results.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_automations",
                        to="conversations.conversation",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("initiator", "Initiator"), ("managers", "Managers"), ("workspace", "Workspace")],
                        default="initiator",
                        max_length=24,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("cron", "Cron"), ("webhook", "Webhook"), ("manual", "Manual")],
                        default="cron",
                        max_length=24,
                    ),
                ),
                ("trigger_config", models.JSONField(blank=True, default=dict)),
                (
                    "destination_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Destination policy (automation thread, notifications) for spawned runs.",
                    ),
                ),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("next_trigger_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "conversations_agent_automation",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["business_profile", "status"], name="automation_biz_status_idx"),
                    models.Index(fields=["agent_profile", "status"], name="automation_agent_status_idx"),
                    models.Index(fields=["status", "next_trigger_at"], name="automation_status_next_idx"),
                    models.Index(fields=["business_profile", "created_at"], name="automation_biz_created_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="agentautomation",
            constraint=models.UniqueConstraint(fields=("agent_profile", "name"), name="automation_unique_agent_name"),
        ),
    ]

