# Generated by Django 5.1.13 on 2026-01-28 00:00

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_alter_emailaccountauditevent_action"),
        ("conversations", "0009_agent_automation_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRequest",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("in_progress", "In progress"), ("resolved", "Resolved")],
                        db_index=True,
                        default="open",
                        max_length=24,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=240)),
                ("question", models.TextField(blank=True, default="")),
                (
                    "context_refs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured context references (no raw dumps).",
                    ),
                ),
                ("resolution", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_requests",
                        to="accounts.businessprofile",
                    ),
                ),
                (
                    "from_agent_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_requests_sent",
                        to="accounts.agentprofile",
                    ),
                ),
                (
                    "to_agent_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_requests_received",
                        to="accounts.agentprofile",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional anchor conversation for context and traceability.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_requests",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional originating AgentRun (for background tasks that need another agent).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_requests",
                        to="conversations.agentrun",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agent_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conversations_agent_request",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["business_profile", "status"], name="agent_request_biz_status_idx"),
                    models.Index(fields=["to_agent_profile", "status"], name="agent_request_to_status_idx"),
                    models.Index(fields=["from_agent_profile", "created_at"], name="agent_request_from_created_idx"),
                    models.Index(fields=["business_profile", "created_at"], name="agent_request_biz_created_idx"),
                ],
            },
        ),
    ]

