# Generated by Django 5.1.13 on 2026-01-28 00:00

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_alter_emailaccountauditevent_action"),
        ("conversations", "0010_agent_request_inbox"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentWatcher",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("run_spec_snapshot", models.JSONField(blank=True, default=dict, help_text="Immutable RunSpec snapshot used when spawning runs from this watcher.")),
                ("name", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("paused", "Paused"), ("archived", "Archived")],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("initiator", "Initiator"), ("managers", "Managers"), ("workspace", "Workspace")],
                        default="initiator",
                        max_length=24,
                    ),
                ),
                (
                    "watcher_type",
                    models.CharField(
                        choices=[("email_inbox", "Email inbox")],
                        default="email_inbox",
                        max_length=24,
                    ),
                ),
                ("watch_config", models.JSONField(blank=True, default=dict)),
                ("poll_interval_seconds", models.PositiveIntegerField(default=300, help_text="Minimum seconds between polls.")),
                ("max_events_per_poll", models.PositiveSmallIntegerField(default=5)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                ("next_poll_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("error_count", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_watchers",
                        to="accounts.businessprofile",
                    ),
                ),
                (
                    "agent_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="accounts.agentprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agent_watchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="watchers",
                        to="conversations.agentrunspec",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional destination conversation used as the default thread for watcher runs.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_watchers",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "email_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Email account used by email-based watchers.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_watchers",
                        to="accounts.emailaccount",
                    ),
                ),
            ],
            options={
                "db_table": "conversations_agent_watcher",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["business_profile", "status"], name="watcher_biz_status_idx"),
                    models.Index(fields=["agent_profile", "status"], name="watcher_agent_status_idx"),
                    models.Index(fields=["status", "next_poll_at"], name="watcher_status_next_poll_idx"),
                    models.Index(fields=["status", "lease_expires_at"], name="watcher_status_lease_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="agentwatcher",
            constraint=models.UniqueConstraint(fields=("agent_profile", "name"), name="watcher_unique_agent_name"),
        ),
        migrations.CreateModel(
            name="AgentWatcherDedupeKey",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("dedupe_key", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "business_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_watcher_dedupe_keys",
                        to="accounts.businessprofile",
                    ),
                ),
                (
                    "watcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dedupe_keys",
                        to="conversations.agentwatcher",
                    ),
                ),
            ],
            options={
                "db_table": "conversations_agent_watcher_dedupe_key",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["watcher", "created_at"], name="watcher_dedupe_created_idx"),
                    models.Index(fields=["business_profile", "created_at"], name="watcher_dedupe_biz_created_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="agentwatcherdedupekey",
            constraint=models.UniqueConstraint(fields=("watcher", "dedupe_key"), name="watcher_dedupe_unique_key"),
        ),
    ]

