# Generated by Django 5.1.13 on 2026-01-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0011_agent_watchers_polling"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentwatcher",
            name="destination_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Destination policy (watcher thread, notifications) for spawned runs.",
            ),
        ),
    ]

