# Generated by ChatGPT on 2026-01-29

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0012_agent_watcher_destination_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="execution_conversation",
            field=models.ForeignKey(
                blank=True,
                help_text="Isolated execution conversation for this run.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="execution_runs",
                to="conversations.conversation",
            ),
        ),
    ]
