# Generated by ChatGPT on 2026-01-31

from __future__ import annotations

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0013_agent_run_execution_conversation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompactedHistorySegment",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compacted_segments",
                        to="conversations.conversation",
                    ),
                ),
                ("segment_range", models.CharField(max_length=64)),
                ("start_message_id", models.UUIDField()),
                ("end_message_id", models.UUIDField()),
                ("summary", models.TextField()),
                ("full_messages", models.JSONField()),
                ("extracted_facts", models.JSONField(blank=True, default=dict)),
                ("extracted_decisions", models.JSONField(blank=True, default=dict)),
                ("token_count_original", models.IntegerField()),
                ("token_count_summary", models.IntegerField()),
                ("compression_ratio", models.FloatField()),
                ("compacted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "conversations_compacted_history_segment",
                "ordering": ("-compacted_at",),
                "indexes": [models.Index(fields=["conversation", "compacted_at"], name="conv_compacted_at_idx")],
            },
        ),
    ]
