# Generated by ChatGPT on 2026-01-31

from __future__ import annotations

from django.conf import settings
from django.db import migrations
from pgvector.django import VectorField


VECTOR_DIM = getattr(settings, "EMBED_DIM", 384)

EXTENSIONS_SQL = ["CREATE EXTENSION IF NOT EXISTS vector"]

INDEX_SQL = [
    """
    CREATE INDEX IF NOT EXISTS conversations_compacted_segment_embedding_hnsw
    ON conversations_compacted_history_segment
    USING hnsw (embedding vector_cosine_ops)
    """,
]


def create_extensions(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for stmt in EXTENSIONS_SQL:
            cursor.execute(stmt)


def drop_extensions(apps, schema_editor):
    # Extensions are shared across the DB; do not drop them from app migrations.
    return None


def create_index(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for stmt in INDEX_SQL:
            cursor.execute(stmt)


def drop_index(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP INDEX IF EXISTS conversations_compacted_segment_embedding_hnsw")


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0014_compacted_history_segment"),
    ]

    operations = [
        migrations.RunPython(create_extensions, drop_extensions),
        migrations.AddField(
            model_name="compactedhistorysegment",
            name="embedding",
            field=VectorField(dimensions=VECTOR_DIM, null=True, blank=True),
        ),
        migrations.RunPython(create_index, drop_index),
    ]
