# Generated by Django 5.1.15 on 2026-01-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0015_compacted_history_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrunmemoryitem',
            name='kind',
            field=models.CharField(choices=[('fact', 'Fact'), ('sop', 'SOP'), ('decision', 'Decision'), ('note', 'Note'), ('extracted_data', 'Extracted Data'), ('workflow_state', 'Workflow State'), ('context_snapshot', 'Context Snapshot')], max_length=24),
        ),
    ]
