# Generated by Django 5.1.15 on 2026-01-31 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_tenant_memory_configuration'),
        ('conversations', '0016_alter_agentrunmemoryitem_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMaintenanceJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('compact_history', 'Compact History')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=24)),
                ('run_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=10)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversations_conversation_maintenance_job',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='compactedhistorysegment',
            constraint=models.UniqueConstraint(fields=('conversation', 'start_message_id', 'end_message_id'), name='uniq_compacted_history_segment_bounds'),
        ),
        migrations.AddField(
            model_name='conversationmaintenancejob',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_maintenance_jobs', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='conversationmaintenancejob',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_jobs', to='conversations.conversation'),
        ),
        migrations.AddIndex(
            model_name='conversationmaintenancejob',
            index=models.Index(fields=['business_profile', 'status'], name='job_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmaintenancejob',
            index=models.Index(fields=['status', 'run_after'], name='job_status_run_after_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmaintenancejob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='job_status_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmaintenancejob',
            index=models.Index(fields=['conversation', 'created_at'], name='job_conv_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmaintenancejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('conversation', 'kind'), name='uniq_active_conversation_maintenance_job'),
        ),
    ]
