# Generated by Django 5.1.15 on 2026-01-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0017_conversationmaintenancejob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compactedhistorysegment',
            name='end_message_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='compactedhistorysegment',
            name='start_message_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
