# Generated by Django 5.1.15 on 2026-01-31

from __future__ import annotations

from django.db import migrations
from django.db.models import Q


def backfill_segment_message_times(apps, schema_editor) -> None:
    CompactedHistorySegment = apps.get_model("conversations", "CompactedHistorySegment")
    ConversationMessage = apps.get_model("conversations", "ConversationMessage")

    batch_size = 500
    qs = (
        CompactedHistorySegment.objects.filter(
            Q(start_message_sent_at__isnull=True) | Q(end_message_sent_at__isnull=True)
        )
        .order_by("compacted_at")
        .only("id", "start_message_id", "end_message_id")
    )

    while True:
        batch = list(qs[:batch_size])
        if not batch:
            break

        message_ids = {seg.start_message_id for seg in batch if seg.start_message_id} | {
            seg.end_message_id for seg in batch if seg.end_message_id
        }
        messages = ConversationMessage.objects.filter(id__in=list(message_ids)).values_list("id", "sent_at")
        sent_at_by_id = {mid: sent_at for mid, sent_at in messages}

        updated = []
        for seg in batch:
            start_sent = sent_at_by_id.get(seg.start_message_id)
            end_sent = sent_at_by_id.get(seg.end_message_id)
            changed = False
            if start_sent and not seg.start_message_sent_at:
                seg.start_message_sent_at = start_sent
                changed = True
            if end_sent and not seg.end_message_sent_at:
                seg.end_message_sent_at = end_sent
                changed = True
            if changed:
                updated.append(seg)

        if updated:
            CompactedHistorySegment.objects.bulk_update(
                updated,
                ["start_message_sent_at", "end_message_sent_at"],
                batch_size=batch_size,
            )


def reverse_backfill(apps, schema_editor) -> None:
    CompactedHistorySegment = apps.get_model("conversations", "CompactedHistorySegment")
    CompactedHistorySegment.objects.update(start_message_sent_at=None, end_message_sent_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0018_compactedhistorysegment_end_message_sent_at_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_segment_message_times, reverse_backfill),
    ]

