# Generated by Codex on 2026-02-02
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0053_alter_tenantmemoryconfiguration_default_archive_after_days_and_more"),
        ("conversations", "0019_backfill_compactedhistorysegment_message_times"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalTurn",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_turns",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_turns",
                        to="conversations.conversationmessage",
                    ),
                ),
                ("user_message", models.TextField(blank=True, default="")),
                (
                    "agent_profile",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_turns",
                        to="accounts.agentprofile",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=24,
                        choices=[
                            ("streaming", "Streaming"),
                            ("waiting_approval", "Waiting approval"),
                            ("finalizing", "Finalizing"),
                            ("finalized", "Finalized"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="streaming",
                    ),
                ),
                ("last_event_seq", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
                ("finalized_at", models.DateTimeField(null=True, blank=True)),
                ("run_after", models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
                ("lease_expires_at", models.DateTimeField(null=True, blank=True, db_index=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(default=dict, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "conversations_portal_turn",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="PortalTurnEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="conversations.portalturn",
                    ),
                ),
                ("seq", models.PositiveIntegerField()),
                ("type", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "conversations_portal_turn_event",
                "ordering": ("seq",),
            },
        ),
        migrations.AddField(
            model_name="conversationtoolapproval",
            name="turn",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turn_approvals",
                to="conversations.portalturn",
            ),
        ),
        migrations.AddIndex(
            model_name="portalturn",
            index=models.Index(fields=["conversation", "status"], name="portal_turn_conv_status_idx"),
        ),
        migrations.AddIndex(
            model_name="portalturn",
            index=models.Index(fields=["status", "run_after"], name="portal_turn_status_run_idx"),
        ),
        migrations.AddIndex(
            model_name="portalturn",
            index=models.Index(fields=["status", "lease_expires_at"], name="portal_turn_status_lease_idx"),
        ),
        migrations.AddIndex(
            model_name="portalturn",
            index=models.Index(fields=["conversation", "created_at"], name="portal_turn_conv_created_idx"),
        ),
        migrations.AddIndex(
            model_name="portalturnevent",
            index=models.Index(fields=["turn", "created_at"], name="portal_turn_event_time_idx"),
        ),
        migrations.AddIndex(
            model_name="portalturnevent",
            index=models.Index(fields=["turn", "type"], name="portal_turn_event_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="portalturnevent",
            constraint=models.UniqueConstraint(fields=("turn", "seq"), name="portal_turn_event_seq_unique"),
        ),
    ]
