# Generated by Django 5.1.15 on 2026-02-12 14:49

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Machine-friendly identifier key (e.g., email, phone, customer_id).', max_length=80)),
                ('display_name', models.CharField(help_text='Human-readable label shown in admin surfaces.', max_length=160)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('disabled', 'Disabled')], default='proposed', help_text='Activation status for retrieval guardrails.', max_length=24)),
                ('source', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='user', help_text='Whether this identifier was user-defined or proposed by AI.', max_length=16)),
                ('is_required', models.BooleanField(default=True, help_text='If true, retrieval must be scoped by this identifier when present.')),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier_schemas', to='accounts.businessprofile')),
            ],
            options={
                'db_table': 'accounts_identifier_schema',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='IdentifierColumnMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier_key', models.CharField(max_length=80)),
                ('normalized_column', models.CharField(db_index=True, max_length=255)),
                ('pattern_signature', models.CharField(blank=True, default='', max_length=255)),
                ('last_confidence', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier_memories', to='accounts.businessprofile')),
                ('identifier_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identifier_memories', to='knowledge.identifierschema')),
            ],
            options={
                'db_table': 'accounts_identifier_memory',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('agents', 'Agents Only'), ('business', 'Entire Business')], default='private', max_length=32)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_collections', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_knowledge_collection',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AgentCollectionAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional context about why access was granted.')),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_access_rules', to='accounts.agentprofile')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_collection_grants', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_access_rules', to='knowledge.knowledgecollection')),
            ],
            options={
                'db_table': 'accounts_agent_collection_grant',
                'ordering': ('-granted_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCollectionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_collection_links', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='knowledge.knowledgecollection')),
            ],
            options={
                'db_table': 'accounts_knowledge_collection_link',
                'ordering': ('position', 'added_at'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDriftSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_kind', models.CharField(choices=[('ingestion', 'Ingestion'), ('retrieval', 'Retrieval')], max_length=24)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_samples', to='accounts.businessprofile')),
            ],
            options={
                'db_table': 'accounts_knowledge_drift_sample',
                'ordering': ('-observed_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('entity_type', models.CharField(blank=True, default='', max_length=120)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('primary_label', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entities', to='accounts.businessprofile')),
            ],
            options={
                'db_table': 'accounts_knowledge_entity',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_raw', models.CharField(max_length=255)),
                ('alias_normalized', models.CharField(db_index=True, max_length=255)),
                ('alias_search_vector', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_aliases', to='accounts.businessprofile')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='knowledge.knowledgeentity')),
            ],
            options={
                'db_table': 'accounts_knowledge_alias',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFeedbackCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('expected_behavior', models.CharField(choices=[('alias_exact', 'Alias Path'), ('hybrid', 'Hybrid Search'), ('not_found', 'Not Found')], default='alias_exact', max_length=24)),
                ('expected_entities', models.JSONField(blank=True, default=list)),
                ('expected_aliases', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(default='feedback', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_cases', to='accounts.businessprofile')),
                ('conversation_feedback', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_case', to='conversations.conversationfeedback')),
            ],
            options={
                'db_table': 'accounts_knowledge_feedback_case',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('source_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_uid', models.CharField(blank=True, default='', help_text='Identifier for deduping integration resources (e.g., drive_file:sheet_gid).', max_length=255)),
                ('external_reference', models.CharField(blank=True, default='', max_length=255)),
                ('legacy_url', models.URLField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('file', 'File Upload'), ('link', 'External Link'), ('text', 'Manual Entry'), ('integration', 'Integration Sync'), ('embed', 'Embedded Content')], db_column='resource_type', default='file', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('active', 'Active'), ('failed', 'Failed'), ('archived', 'Archived')], default='pending', max_length=32)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('internal', 'Internal'), ('shared', 'Shared')], default='private', max_length=32)),
                ('language', models.CharField(blank=True, default='', max_length=32)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ingestion_metadata', models.JSONField(blank=True, default=dict)),
                ('retention_policy', models.JSONField(blank=True, default=dict, help_text='Optional rules for expiry or redaction.')),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_uploads', to='accounts.businessprofile')),
                ('collections', models.ManyToManyField(blank=True, related_name='knowledge_uploads', through='knowledge.KnowledgeCollectionLink', to='knowledge.knowledgecollection')),
                ('created_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_contributions', to='accounts.agentprofile')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='integrations.knowledgeintegration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_knowledge_upload',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('ingest', 'Initial Ingest'), ('embed', 'Embedding'), ('rebuild', 'Rebuild'), ('delete', 'Delete'), ('sync', 'Sync')], max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('deferred', 'Deferred'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('run_after', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_jobs', to='accounts.businessprofile')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='knowledge.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_ingestion_job',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='knowledgeentity',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='knowledge.knowledgeupload'),
        ),
        migrations.AddField(
            model_name='knowledgecollectionlink',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_links', to='knowledge.knowledgeupload'),
        ),
        migrations.CreateModel(
            name='KnowledgeAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_id_snapshot', models.UUIDField(blank=True, db_index=True, help_text='Snapshot of the upload UUID for retention when the upload is deleted.', null=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('ingested', 'Ingested'), ('read', 'Read'), ('exported', 'Exported'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('archived', 'Archived'), ('restored', 'Restored')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_audit_events', to='accounts.agentprofile')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_audit_events', to=settings.AUTH_USER_MODEL)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_audit_events', to='accounts.businessprofile')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='knowledge.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_audit_event',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='IdentifierColumnMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=255)),
                ('column_name', models.CharField(max_length=255)),
                ('column_normalized', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('disabled', 'Disabled')], default='proposed', max_length=24)),
                ('source', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='user', max_length=16)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_required', models.BooleanField(blank=True, default=None, help_text='Override for identifier.is_required. When true, queries for this upload must be scoped by this identifier; when false, it is optional for this upload.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier_columns', to='accounts.businessprofile')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='knowledge.identifierschema')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifier_columns', to='knowledge.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_identifier_column',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentKnowledgeAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional context about why access was granted.')),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_access_rules', to='accounts.agentprofile')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_knowledge_grants', to=settings.AUTH_USER_MODEL)),
                ('knowledge_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_access_rules', to='knowledge.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_agent_knowledge_grant',
                'ordering': ('-granted_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='accounts.businessprofile')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_chunk',
                'ordering': ('upload_id', 'chunk_index'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('storage_path', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=128)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_detail', to='knowledge.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_file',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('width', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('rotation', models.IntegerField(default=0)),
                ('text_density', models.FloatField(default=0.0)),
                ('has_ocr_content', models.BooleanField(default=False)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='knowledge.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_page',
                'ordering': ('upload_id', 'page_number'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadPageBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('list', 'List'), ('table', 'Table'), ('figure', 'Figure'), ('image', 'Image'), ('footer', 'Footer'), ('header', 'Header'), ('ocr_only', 'OCR Text'), ('other', 'Other')], default='paragraph', max_length=32)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True, default='')),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('section_heading', models.CharField(blank=True, default='', max_length=255)),
                ('heading_path', models.JSONField(blank=True, default=list)),
                ('detected_language', models.CharField(blank=True, default='', max_length=32)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='knowledge.knowledgeuploadpage')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_blocks', to='knowledge.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_page_block',
                'ordering': ('page_id', 'order_index'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadShadowChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_shadow_chunks', to='accounts.businessprofile')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_chunks', to='knowledge.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_shadow_chunk',
                'ordering': ('upload_id', 'chunk_index'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('section_heading', models.CharField(blank=True, default='', max_length=255)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('column_schema', models.JSONField(blank=True, default=list, help_text='Ordered schema describing each detected column.')),
                ('data_dictionary', models.JSONField(blank=True, default=dict, help_text='Optional metadata describing column semantics/normalization.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='knowledge.knowledgeuploadpage')),
                ('source_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='knowledge.knowledgeuploadpageblock')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='knowledge.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_table',
                'ordering': ('upload_id', 'order_index'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTableColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_index', models.PositiveIntegerField()),
                ('column_name', models.CharField(max_length=255)),
                ('column_normalized', models.CharField(db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_columns', to='accounts.businessprofile')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_columns', to='knowledge.knowledgeupload')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='knowledge.knowledgeuploadtable')),
            ],
            options={
                'db_table': 'accounts_knowledge_table_column',
                'ordering': ('table_id', 'column_index'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadTableRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='knowledge.knowledgeuploadtable')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_table_row',
                'ordering': ('table_id', 'row_index'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadTableCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_index', models.PositiveIntegerField()),
                ('column_key', models.CharField(blank=True, default='', max_length=160)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('normalized_value', models.JSONField(blank=True, default=dict, help_text='Parsed/typed representation (e.g., amount, currency).')),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='knowledge.knowledgeuploadtable')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='knowledge.knowledgeuploadtablerow')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_table_cell',
                'ordering': ('table_id', 'row_id', 'column_index'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_code', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('detected_by', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='knowledge.knowledgeupload')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='knowledge.knowledgeuploadpage')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='knowledge.knowledgeuploadtable')),
                ('table_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='knowledge.knowledgeuploadtablecell')),
                ('table_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='knowledge.knowledgeuploadtablerow')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_issue',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_detail', to='knowledge.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_text',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeUploadUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('normalized_host', models.CharField(blank=True, default='', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_detail', to='knowledge.knowledgeupload')),
            ],
            options={
                'db_table': 'accounts_knowledge_upload_url',
            },
        ),
        migrations.CreateModel(
            name='RAGEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], default='pass', max_length=8)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('latencies', models.JSONField(blank=True, default=dict)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('violations', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='accounts.businessprofile')),
            ],
            options={
                'db_table': 'accounts_rag_evaluation_run',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='identifierschema',
            index=models.Index(fields=['business_profile', 'status'], name='identifier_schema_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='identifierschema',
            constraint=models.UniqueConstraint(fields=('business_profile', 'key'), name='identifier_schema_unique_key'),
        ),
        migrations.AddIndex(
            model_name='identifiercolumnmemory',
            index=models.Index(fields=['business_profile', 'normalized_column'], name='identifier_memory_column_idx'),
        ),
        migrations.AddConstraint(
            model_name='identifiercolumnmemory',
            constraint=models.UniqueConstraint(fields=('business_profile', 'normalized_column', 'pattern_signature'), name='identifier_memory_unique_signature'),
        ),
        migrations.AddIndex(
            model_name='knowledgecollection',
            index=models.Index(fields=['business_profile', 'slug'], name='knowledge_coll_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgecollection',
            index=models.Index(fields=['business_profile', 'visibility'], name='knowledge_coll_vis_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgecollection',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('business_profile', 'slug'), name='knowledge_coll_slug_uniq'),
        ),
        migrations.AddConstraint(
            model_name='agentcollectionaccess',
            constraint=models.UniqueConstraint(fields=('agent_profile', 'collection'), name='agent_collection_unique'),
        ),
        migrations.AddIndex(
            model_name='knowledgedriftsample',
            index=models.Index(fields=['business_profile', 'sample_kind', 'observed_at'], name='knowledge_drift_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgealias',
            index=models.Index(fields=['business_profile', 'alias_normalized'], name='kn_alias_biz_norm_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgealias',
            index=models.Index(condition=models.Q(('alias_normalized__regex', '.{5,}')), fields=['alias_normalized'], name='kn_alias_norm_len_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgealias',
            index=django.contrib.postgres.indexes.GinIndex(fields=['alias_normalized'], name='kn_alias_norm_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='knowledgealias',
            index=django.contrib.postgres.indexes.GinIndex(fields=['alias_search_vector'], name='knowledge_alias_search_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='knowledgealias',
            constraint=models.UniqueConstraint(fields=('entity', 'alias_normalized'), name='knowledge_alias_unique_entity_alias'),
        ),
        migrations.AddIndex(
            model_name='knowledgefeedbackcase',
            index=models.Index(fields=['business_profile', 'is_active'], name='knowledge_feedback_active_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeupload',
            index=models.Index(fields=['business_profile', 'status'], name='upload_business_status_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeupload',
            index=models.Index(fields=['business_profile', 'source_type'], name='upload_business_source_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeupload',
            index=models.Index(fields=['business_profile', 'slug'], name='upload_business_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeupload',
            index=models.Index(fields=['integration', 'status'], name='upload_integration_status_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeupload',
            index=django.contrib.postgres.indexes.GinIndex(fields=['display_name'], name='upload_display_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='knowledgeupload',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('business_profile', 'slug'), name='knowledge_unique_business_slug'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestionjob',
            index=models.Index(fields=['business_profile', 'status'], name='knowledge_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestionjob',
            index=models.Index(fields=['upload', 'job_type'], name='knowledge_job_type_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestionjob',
            index=models.Index(fields=['status', 'run_after'], name='knowledge_job_run_after_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestionjob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='knowledge_job_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentity',
            index=models.Index(fields=['business_profile', 'entity_type'], name='knowledge_entity_type_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentity',
            index=models.Index(fields=['upload'], name='knowledge_entity_upload_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgecollectionlink',
            constraint=models.UniqueConstraint(fields=('collection', 'upload'), name='knowledge_coll_upload_uniq'),
        ),
        migrations.AddIndex(
            model_name='knowledgeauditevent',
            index=models.Index(fields=['upload', 'action'], name='knowledge_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeauditevent',
            index=models.Index(fields=['upload_id_snapshot', 'action'], name='kn_audit_upid_action_idx'),
        ),
        migrations.AddIndex(
            model_name='identifiercolumnmapping',
            index=models.Index(fields=['business_profile', 'column_normalized'], name='identifier_column_norm_idx'),
        ),
        migrations.AddIndex(
            model_name='identifiercolumnmapping',
            index=models.Index(fields=['business_profile', 'upload'], name='identifier_column_upload_idx'),
        ),
        migrations.AddConstraint(
            model_name='identifiercolumnmapping',
            constraint=models.UniqueConstraint(fields=('identifier', 'upload', 'column_normalized', 'sheet_name'), name='identifier_column_unique_scope'),
        ),
        migrations.AddConstraint(
            model_name='agentknowledgeaccess',
            constraint=models.UniqueConstraint(fields=('agent_profile', 'knowledge_upload'), name='agent_knowledge_unique'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadchunk',
            index=models.Index(fields=['upload', 'chunk_index'], name='knowledge_chunk_window_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadchunk',
            index=models.Index(fields=['business_profile', 'chunk_index'], name='kn_chunk_biz_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadchunk',
            index=models.Index(fields=['business_profile', 'upload'], name='kn_chunk_biz_upload_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeuploadchunk',
            constraint=models.UniqueConstraint(fields=('business_profile', 'upload', 'chunk_index'), name='knowledge_chunk_unique_index'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadpage',
            index=models.Index(fields=['upload', 'page_number'], name='knowledge_page_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeuploadpage',
            constraint=models.UniqueConstraint(fields=('upload', 'page_number'), name='knowledge_page_unique_number'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadpageblock',
            index=models.Index(fields=['upload', 'block_type'], name='knowledge_block_type_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadpageblock',
            index=models.Index(fields=['page', 'block_type'], name='knowledge_block_page_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeuploadpageblock',
            constraint=models.UniqueConstraint(fields=('page', 'order_index'), name='knowledge_block_unique_order'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadshadowchunk',
            index=models.Index(fields=['upload', 'chunk_index'], name='kn_shadow_chunk_window_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadshadowchunk',
            index=models.Index(fields=['business_profile', 'chunk_index'], name='kn_shadow_biz_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadshadowchunk',
            index=models.Index(fields=['business_profile', 'upload'], name='kn_shadow_biz_upload_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeuploadshadowchunk',
            constraint=models.UniqueConstraint(fields=('business_profile', 'upload', 'chunk_index'), name='knowledge_shadow_chunk_unique_index'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadtable',
            index=models.Index(fields=['upload', 'order_index'], name='knowledge_table_upload_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadtable',
            index=models.Index(fields=['page', 'order_index'], name='knowledge_table_page_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgetablecolumn',
            index=models.Index(fields=['business_profile', 'column_normalized'], name='knowledge_table_col_biz_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgetablecolumn',
            index=django.contrib.postgres.indexes.GinIndex(fields=['column_normalized'], name='knowledge_table_col_norm_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='knowledgetablecolumn',
            index=django.contrib.postgres.indexes.GinIndex(fields=['column_name'], name='knowledge_table_col_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='knowledgetablecolumn',
            constraint=models.UniqueConstraint(fields=('table', 'column_index'), name='knowledge_table_column_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeuploadtablerow',
            constraint=models.UniqueConstraint(fields=('table', 'row_index'), name='knowledge_table_row_unique_index'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadtablecell',
            index=models.Index(fields=['table', 'column_index'], name='knowledge_cell_column_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadtablecell',
            index=models.Index(fields=['column_key'], name='knowledge_cell_column_key_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadtablecell',
            index=django.contrib.postgres.indexes.GinIndex(fields=['raw_text'], name='knowledge_cell_raw_text_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='knowledgeuploadtablecell',
            constraint=models.UniqueConstraint(fields=('row', 'column_index'), name='knowledge_cell_unique_row_column'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadissue',
            index=models.Index(fields=['upload', 'severity'], name='knowledge_issue_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeuploadissue',
            index=models.Index(fields=['table', 'issue_code'], name='knowledge_issue_table_idx'),
        ),
        migrations.AddIndex(
            model_name='ragevaluationrun',
            index=models.Index(fields=['business_profile', 'slug'], name='rag_eval_business_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='ragevaluationrun',
            index=models.Index(fields=['status', 'created_at'], name='rag_eval_status_idx'),
        ),
    ]
