# Generated by Django 5.1.15 on 2026-02-19

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_remove_identifier_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeLexiconTerm",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "term_type",
                    models.CharField(
                        choices=[("entity", "Entity"), ("attribute", "Attribute")],
                        default="entity",
                        max_length=24,
                    ),
                ),
                ("canonical_text", models.CharField(max_length=255)),
                ("canonical_normalized", models.CharField(max_length=255)),
                (
                    "language_code",
                    models.CharField(
                        default="und",
                        help_text="BCP-47 language tag (e.g. en, ar, en-us). 'und' = undetermined.",
                        max_length=16,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.7,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("source", models.CharField(blank=True, default="manual", max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_lexicon_terms",
                        to="accounts.businessprofile",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_knowledge_lexicon_term",
                "ordering": ("term_type", "canonical_normalized"),
            },
        ),
        migrations.CreateModel(
            name="KnowledgeLexiconSynonym",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("synonym_text", models.CharField(max_length=255)),
                ("synonym_normalized", models.CharField(max_length=255)),
                (
                    "language_code",
                    models.CharField(
                        default="und",
                        help_text="BCP-47 language tag (e.g. en, ar, en-us).",
                        max_length=16,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.7,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("source", models.CharField(blank=True, default="manual", max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_lexicon_synonyms",
                        to="accounts.businessprofile",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synonyms",
                        to="knowledge.knowledgelexiconterm",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_knowledge_lexicon_synonym",
                "ordering": ("term_id", "synonym_normalized"),
            },
        ),
        migrations.AddIndex(
            model_name="knowledgelexiconterm",
            index=models.Index(fields=["business_profile", "term_type"], name="kn_lex_term_type_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgelexiconterm",
            index=models.Index(
                fields=["business_profile", "term_type", "language_code"],
                name="kn_lex_term_lang_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgelexiconterm",
            index=models.Index(
                fields=["business_profile", "is_active", "updated_at"],
                name="kn_lex_term_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgelexiconterm",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["canonical_normalized"],
                name="kn_lex_term_norm_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgelexiconterm",
            constraint=models.UniqueConstraint(
                fields=("business_profile", "term_type", "language_code", "canonical_normalized"),
                name="knowledge_lexicon_term_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgelexiconsynonym",
            index=models.Index(fields=["business_profile", "synonym_normalized"], name="kn_lex_syn_norm_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgelexiconsynonym",
            index=models.Index(
                fields=["business_profile", "is_active", "updated_at"],
                name="kn_lex_syn_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgelexiconsynonym",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["synonym_normalized"],
                name="kn_lex_syn_norm_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgelexiconsynonym",
            constraint=models.UniqueConstraint(
                fields=("term", "language_code", "synonym_normalized"),
                name="knowledge_lexicon_synonym_unique",
            ),
        ),
    ]
