# Generated by Django 5.1.15 on 2026-02-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_agentprofile_allowed_collections'),
        ('knowledge', '0004_knowledge_lexicon_foundation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgecollection',
            name='business_profile',
        ),
        migrations.RemoveField(
            model_name='knowledgecollection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='knowledgecollectionlink',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='knowledgeupload',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='knowledgecollectionlink',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='knowledgecollectionlink',
            name='upload',
        ),
        migrations.DeleteModel(
            name='AgentCollectionAccess',
        ),
        migrations.DeleteModel(
            name='KnowledgeCollection',
        ),
        migrations.DeleteModel(
            name='KnowledgeCollectionLink',
        ),
    ]
