# Generated by Codex on 2026-01-31

from __future__ import annotations

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallSession",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("objective", models.TextField()),
                ("call_type", models.CharField(max_length=32, choices=[("service", "Service"), ("marketing", "Marketing")], default="service", db_index=True)),
                ("language", models.CharField(max_length=8, default="en")),
                ("country", models.CharField(max_length=2, blank=True, default="", db_index=True)),
                ("to_phone_number", models.CharField(max_length=32)),
                ("from_phone_number", models.CharField(max_length=32, blank=True, default="")),
                ("twilio_call_sid", models.CharField(max_length=64, blank=True, default="", db_index=True)),
                ("twilio_stream_sid", models.CharField(max_length=64, blank=True, default="", db_index=True)),
                ("status", models.CharField(max_length=32, choices=[("queued", "Queued"), ("initiating", "Initiating"), ("ringing", "Ringing"), ("in_progress", "In Progress"), ("completed", "Completed"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="queued", db_index=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("consent_obtained", models.BooleanField(default=False, db_index=True)),
                ("consent_obtained_at", models.DateTimeField(blank=True, null=True)),
                ("consent_method", models.CharField(max_length=16, blank=True, default="")),
                ("recording_sid", models.CharField(max_length=64, blank=True, default="", db_index=True)),
                ("recording_url", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="CallEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=64, db_index=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("call_session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="voice.callsession")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["call_session", "created_at"], name="voice_calle_call_se_20f64c_idx"),
                    models.Index(fields=["call_session", "event_type"], name="voice_calle_call_se_cd95a7_idx"),
                ],
            },
        ),
    ]
