# Generated by Django 5.1.15 on 2026-02-12 14:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCountryPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(db_index=True, max_length=2, unique=True)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('service_calls_allowed', models.BooleanField(default=True)),
                ('marketing_calls_allowed', models.BooleanField(default=False)),
                ('recording_allowed', models.BooleanField(default=True)),
                ('recording_consent_required', models.BooleanField(default=True)),
                ('ai_disclosure_required', models.BooleanField(default=True)),
                ('allowed_weekdays', models.JSONField(blank=True, default=list)),
                ('allowed_call_time_start', models.TimeField(blank=True, null=True)),
                ('allowed_call_time_end', models.TimeField(blank=True, null=True)),
                ('policy_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trust_tier', models.CharField(choices=[('trial', 'Trial'), ('verified', 'Verified'), ('enterprise', 'Enterprise')], default='trial', max_length=24)),
                ('service_calls_enabled', models.BooleanField(default=False)),
                ('marketing_calls_enabled', models.BooleanField(default=False)),
                ('allowed_countries', models.JSONField(blank=True, default=list)),
                ('max_concurrent_calls', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_calls_per_day', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_call_duration_seconds', models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(30)])),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('default_language', models.CharField(default='en', max_length=8)),
                ('ai_disclosure_template', models.TextField(blank=True, default='')),
                ('ai_disclosure_template_ar', models.TextField(blank=True, default='')),
                ('recording_consent_required', models.BooleanField(default=True)),
                ('active_transport_provider', models.CharField(blank=True, choices=[('twilio', 'Twilio'), ('telnyx', 'Telnyx')], default='', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_configuration', to='accounts.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VoicePhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio'), ('telnyx', 'Telnyx')], default='twilio', max_length=24)),
                ('phone_number', models.CharField(max_length=32)),
                ('provider_sid', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('pending', 'Pending')], db_index=True, default='pending', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_phone_numbers', to='accounts.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objective', models.TextField()),
                ('call_type', models.CharField(choices=[('service', 'Service'), ('marketing', 'Marketing')], db_index=True, default='service', max_length=32)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound')], default='outbound', max_length=16)),
                ('language', models.CharField(default='en', max_length=8)),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=2)),
                ('context_items', models.JSONField(blank=True, default=list)),
                ('max_duration_seconds', models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(30)])),
                ('to_phone_number', models.CharField(max_length=32)),
                ('from_phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('transport_provider', models.CharField(blank=True, db_index=True, default='', max_length=24)),
                ('provider_call_sid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('provider_stream_sid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('twilio_call_sid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('twilio_stream_sid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('initiating', 'Initiating'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=32)),
                ('last_error', models.TextField(blank=True, default='')),
                ('queued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('run_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('consent_obtained', models.BooleanField(db_index=True, default=False)),
                ('consent_obtained_at', models.DateTimeField(blank=True, null=True)),
                ('consent_method', models.CharField(blank=True, default='', max_length=16)),
                ('stream_token', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('recording_sid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('recording_url', models.TextField(blank=True, default='')),
                ('recording_r2_bucket', models.CharField(blank=True, default='', max_length=128)),
                ('recording_r2_key', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('recording_r2_etag', models.CharField(blank=True, default='', max_length=128)),
                ('cost_estimate_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('cost_total_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('summary', models.TextField(blank=True, default='')),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('insights', models.JSONField(blank=True, default=dict)),
                ('post_processed', models.BooleanField(db_index=True, default=False)),
                ('post_processed_at', models.DateTimeField(blank=True, null=True)),
                ('post_processing_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_sessions', to='accounts.agentprofile')),
                ('business_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_sessions', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voice_call_sessions', to=settings.AUTH_USER_MODEL)),
                ('execution_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_transcripts', to='conversations.conversation')),
                ('initiating_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_voice_calls', to='conversations.conversation')),
                ('voice_phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_sessions', to='voice.voicephonenumber')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio'), ('telnyx', 'Telnyx'), ('deepgram', 'Deepgram'), ('elevenlabs', 'ElevenLabs')], max_length=24)),
                ('enabled', models.BooleanField(default=False)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('credentials_key_version', models.PositiveSmallIntegerField(default=1)),
                ('credentials_last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('credential_error_count', models.PositiveSmallIntegerField(default=0)),
                ('last_tested_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_provider_connections', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_provider_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_provider_connection',
                'ordering': ('provider',),
            },
        ),
        migrations.CreateModel(
            name='VoiceSuppressionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_suppression_entries', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voice_suppression_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_events', to='accounts.businessprofile')),
                ('call_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='voice.callsession')),
            ],
            options={
                'indexes': [models.Index(fields=['call_session', 'created_at'], name='voice_calle_call_se_20f64c_idx'), models.Index(fields=['call_session', 'event_type'], name='voice_calle_call_se_cd95a7_idx'), models.Index(fields=['business_profile', 'created_at'], name='voice_calle_busines_83f560_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoiceCallAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_session_id_snapshot', models.UUIDField(blank=True, db_index=True, help_text='Snapshot of the CallSession UUID for retention when the session is deleted.', null=True)),
                ('action', models.CharField(choices=[('policy_evaluated', 'Policy Evaluated'), ('policy_blocked', 'Policy Blocked'), ('disclosure_required', 'Disclosure Required'), ('consent_required', 'Consent Required')], max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_audit_events', to='accounts.agentprofile')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_audit_events', to=settings.AUTH_USER_MODEL)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_call_audit_events', to='accounts.businessprofile')),
                ('call_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='voice.callsession')),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['call_session', 'action'], name='voice_voice_call_se_853c4d_idx'), models.Index(fields=['call_session_id_snapshot', 'action'], name='voice_voice_call_se_f5b6bc_idx'), models.Index(fields=['business_profile', 'occurred_at'], name='voice_voice_busines_bef57c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='voicephonenumber',
            index=models.Index(fields=['business_profile', 'status'], name='voice_voice_busines_d37ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='voicephonenumber',
            index=models.Index(fields=['business_profile', 'phone_number'], name='voice_voice_busines_cb281b_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceproviderconnection',
            index=models.Index(fields=['business_profile', 'provider'], name='voice_voice_busines_a317f6_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceproviderconnection',
            index=models.Index(fields=['business_profile', 'enabled'], name='voice_voice_busines_1ec414_idx'),
        ),
        migrations.AddConstraint(
            model_name='voiceproviderconnection',
            constraint=models.UniqueConstraint(fields=('business_profile', 'provider'), name='voice_provider_business_provider_uniq'),
        ),
        migrations.AddIndex(
            model_name='voicesuppressionentry',
            index=models.Index(fields=['business_profile', 'created_at'], name='voice_voice_busines_165507_idx'),
        ),
        migrations.AddConstraint(
            model_name='voicesuppressionentry',
            constraint=models.UniqueConstraint(fields=('business_profile', 'phone_number'), name='voice_suppress_unique_number'),
        ),
    ]
