# Generated by Django 5.1.13 on 2026-01-31 19:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_tenantmemoryconfiguration_default_archive_after_days_and_more'),
        ('conversations', '0019_backfill_compactedhistorysegment_message_times'),
        ('voice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trust_tier', models.CharField(choices=[('trial', 'Trial'), ('verified', 'Verified'), ('enterprise', 'Enterprise')], default='trial', max_length=24)),
                ('service_calls_enabled', models.BooleanField(default=False)),
                ('marketing_calls_enabled', models.BooleanField(default=False)),
                ('allowed_countries', models.JSONField(blank=True, default=list)),
                ('max_concurrent_calls', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_calls_per_day', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_call_duration_seconds', models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(30)])),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('default_language', models.CharField(default='en', max_length=8)),
                ('ai_disclosure_template', models.TextField(blank=True, default='')),
                ('recording_consent_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoicePhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio')], default='twilio', max_length=24)),
                ('phone_number', models.CharField(max_length=32)),
                ('provider_sid', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('pending', 'Pending')], db_index=True, default='pending', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceSuppressionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='callevent',
            name='business_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_events', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='agent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_sessions', to='accounts.agentprofile'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callsession',
            name='business_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_sessions', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='context_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='callsession',
            name='cost_estimate_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='callsession',
            name='cost_total_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='callsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voice_call_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsession',
            name='direction',
            field=models.CharField(choices=[('outbound', 'Outbound')], default='outbound', max_length=16),
        ),
        migrations.AddField(
            model_name='callsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='execution_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_transcripts', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='initiating_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_voice_calls', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='max_attempts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='callsession',
            name='max_duration_seconds',
            field=models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='callsession',
            name='post_processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='callsession',
            name='post_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='queued_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='callsession',
            name='recording_r2_bucket',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='callsession',
            name='recording_r2_etag',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='callsession',
            name='recording_r2_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='callsession',
            name='run_after',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='stream_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='callevent',
            index=models.Index(fields=['business_profile', 'created_at'], name='voice_calle_busines_83f560_idx'),
        ),
        migrations.AddField(
            model_name='voiceconfiguration',
            name='business_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_configuration', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='voicephonenumber',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_phone_numbers', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='voice_phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_sessions', to='voice.voicephonenumber'),
        ),
        migrations.AddField(
            model_name='voicesuppressionentry',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_suppression_entries', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='voicesuppressionentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voice_suppression_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='voicephonenumber',
            index=models.Index(fields=['business_profile', 'status'], name='voice_voice_busines_d37ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='voicephonenumber',
            index=models.Index(fields=['business_profile', 'phone_number'], name='voice_voice_busines_cb281b_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesuppressionentry',
            index=models.Index(fields=['business_profile', 'created_at'], name='voice_voice_busines_165507_idx'),
        ),
        migrations.AddConstraint(
            model_name='voicesuppressionentry',
            constraint=models.UniqueConstraint(fields=('business_profile', 'phone_number'), name='voice_suppress_unique_number'),
        ),
    ]
