# Generated by Django 5.1.13 on 2026-01-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_voiceconfiguration_voicephonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='action_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='callsession',
            name='post_processing_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='callsession',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
