# Generated by Django 5.1.13 on 2026-01-31 20:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_tenantmemoryconfiguration_default_archive_after_days_and_more'),
        ('voice', '0003_callsession_action_items_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCountryPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(db_index=True, max_length=2, unique=True)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('service_calls_allowed', models.BooleanField(default=True)),
                ('marketing_calls_allowed', models.BooleanField(default=False)),
                ('recording_allowed', models.BooleanField(default=True)),
                ('recording_consent_required', models.BooleanField(default=True)),
                ('ai_disclosure_required', models.BooleanField(default=True)),
                ('allowed_weekdays', models.JSONField(blank=True, default=list)),
                ('allowed_call_time_start', models.TimeField(blank=True, null=True)),
                ('allowed_call_time_end', models.TimeField(blank=True, null=True)),
                ('policy_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='voiceconfiguration',
            name='ai_disclosure_template_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='VoiceCallAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_session_id_snapshot', models.UUIDField(blank=True, db_index=True, help_text='Snapshot of the CallSession UUID for retention when the session is deleted.', null=True)),
                ('action', models.CharField(choices=[('policy_evaluated', 'Policy Evaluated'), ('policy_blocked', 'Policy Blocked'), ('disclosure_required', 'Disclosure Required'), ('consent_required', 'Consent Required')], max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_audit_events', to='accounts.agentprofile')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_audit_events', to=settings.AUTH_USER_MODEL)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_call_audit_events', to='accounts.businessprofile')),
                ('call_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='voice.callsession')),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['call_session', 'action'], name='voice_voice_call_se_853c4d_idx'), models.Index(fields=['call_session_id_snapshot', 'action'], name='voice_voice_call_se_f5b6bc_idx'), models.Index(fields=['business_profile', 'occurred_at'], name='voice_voice_busines_bef57c_idx')],
            },
        ),
    ]
