# Generated by Django 5.1.13 on 2026-01-31

import datetime

from django.db import migrations


def seed_country_policies(apps, schema_editor) -> None:
    VoiceCountryPolicy = apps.get_model("voice", "VoiceCountryPolicy")

    seeded = [
        ("EG", "Africa/Cairo"),
        ("AE", "Asia/Dubai"),
        ("SA", "Asia/Riyadh"),
        ("QA", "Asia/Qatar"),
        ("KW", "Asia/Kuwait"),
        ("JO", "Asia/Amman"),
        ("OM", "Asia/Muscat"),
    ]

    weekdays = [0, 1, 2, 3, 4, 5, 6]
    start = datetime.time(9, 0)
    end = datetime.time(21, 0)

    for country, tz in seeded:
        VoiceCountryPolicy.objects.update_or_create(
            country=country,
            defaults={
                "timezone": tz,
                "is_active": True,
                "service_calls_allowed": True,
                "marketing_calls_allowed": False,
                "recording_allowed": True,
                "recording_consent_required": True,
                "ai_disclosure_required": True,
                "allowed_weekdays": weekdays,
                "allowed_call_time_start": start,
                "allowed_call_time_end": end,
                # Keep enforcement disabled by default; operators can enable
                # once country-specific rules are verified.
                "policy_config": {"version": 1, "seeded_by": "migration", "enforce_call_window": False},
            },
        )


def unseed_country_policies(apps, schema_editor) -> None:
    # We intentionally do not delete rows on rollback to preserve operator edits.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0004_voicecountrypolicy_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_country_policies, reverse_code=unseed_country_policies),
    ]
