# Generated by Django 5.1.13 on 2026-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0005_seed_voice_country_policies"),
    ]

    operations = [
        migrations.AddField(
            model_name="callsession",
            name="insights",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]

