# Generated by Django 5.1.13 on 2026-02-05 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0053_alter_tenantmemoryconfiguration_default_archive_after_days_and_more"),
        ("voice", "0006_callsession_insights"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceProviderConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("twilio", "Twilio"), ("deepgram", "Deepgram"), ("elevenlabs", "ElevenLabs")], max_length=24)),
                ("enabled", models.BooleanField(default=False)),
                ("credentials_encrypted", models.TextField(blank=True, default="")),
                ("credentials_key_version", models.PositiveSmallIntegerField(default=1)),
                ("credentials_last_rotated_at", models.DateTimeField(blank=True, null=True)),
                ("credential_error_count", models.PositiveSmallIntegerField(default=0)),
                ("last_tested_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="voice_provider_connections", to="accounts.businessprofile")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="voice_provider_connections", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "voice_provider_connection",
                "ordering": ("provider",),
                "indexes": [models.Index(fields=["business_profile", "provider"], name="voice_voice_busines_a317f6_idx"), models.Index(fields=["business_profile", "enabled"], name="voice_voice_busines_1ec414_idx")],
                "constraints": [models.UniqueConstraint(fields=("business_profile", "provider"), name="voice_provider_business_provider_uniq")],
            },
        ),
    ]
