# Generated by Django 5.1.14 on 2025-11-06 15:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_knowledgeupload'),
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('given_name', models.CharField(blank=True, max_length=120)),
                ('family_name', models.CharField(blank=True, max_length=120)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=40)),
                ('primary_address', models.JSONField(blank=True, default=dict)),
                ('record_origin', models.CharField(choices=[('ai_extracted', 'AI Extracted'), ('manual', 'Manual Entry'), ('import_csv', 'CSV Import'), ('import_contacts', 'Contacts Import'), ('system', 'System'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('record_state', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('placeholder', 'Placeholder')], default='active', max_length=32)),
                ('is_placeholder', models.BooleanField(default=False)),
                ('placeholder_key', models.CharField(blank=True, help_text="Identifier for grouping placeholder customers per business (e.g., 'default').", max_length=64)),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_interaction_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.agentprofile')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers_customer',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('customer', 'Customer'), ('ai_agent', 'AI Agent'), ('business', 'Business Owner'), ('system', 'System')], max_length=32)),
                ('activity_type', models.CharField(choices=[('message', 'Message'), ('task', 'Task'), ('note', 'Note'), ('status_change', 'Status Change'), ('workflow', 'Workflow'), ('case_update', 'Case Update'), ('other', 'Other')], default='other', max_length=32)),
                ('session_reference', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_activities', to='accounts.agentprofile')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_activities', to='accounts.businessprofile')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_activities', to='cases.case')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customers.customer')),
            ],
            options={
                'db_table': 'customers_activity',
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CustomerContactPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('address', 'Address'), ('social', 'Social'), ('messaging', 'Messaging'), ('other', 'Other')], max_length=24)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('normalized_value', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='customers.customer')),
            ],
            options={
                'db_table': 'customers_contact_point',
                'ordering': ('contact_type', 'label'),
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_type', models.CharField(choices=[('customer', 'Customer'), ('ai_agent', 'AI Agent')], max_length=32)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_notes', to='cases.case')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='customers.customer')),
            ],
            options={
                'db_table': 'customers_note',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business_profile', 'record_state'], name='customer_business_state_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business_profile', 'display_name'], name='customer_business_name_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['public_id'], name='customer_public_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('placeholder_key', ''), _negated=True), fields=('business_profile', 'placeholder_key'), name='customer_unique_placeholder'),
        ),
        migrations.AddIndex(
            model_name='customeractivity',
            index=models.Index(fields=['customer', 'occurred_at'], name='activity_customer_time_idx'),
        ),
        migrations.AddIndex(
            model_name='customeractivity',
            index=models.Index(fields=['case', 'occurred_at'], name='activity_case_time_idx'),
        ),
        migrations.AddIndex(
            model_name='customercontactpoint',
            index=models.Index(fields=['customer', 'contact_type'], name='contact_customer_type_idx'),
        ),
        migrations.AddIndex(
            model_name='customercontactpoint',
            index=models.Index(fields=['normalized_value'], name='contact_normalized_idx'),
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['customer', 'created_at'], name='note_customer_time_idx'),
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['case', 'created_at'], name='note_case_time_idx'),
        ),
    ]
