# Generated by Django 5.1.14 on 2026-05-17 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationDedupeKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dedupe_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'automations_dedupe_key',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused')], db_index=True, default='draft', max_length=24)),
                ('visibility', models.CharField(choices=[('initiator', 'Initiator'), ('managers', 'Managers'), ('workspace', 'Workspace')], default='initiator', max_length=24)),
                ('trigger_type', models.CharField(choices=[('schedule', 'Schedule')], db_index=True, max_length=24)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('source_config', models.JSONField(blank=True, default=dict)),
                ('destination_config', models.JSONField(blank=True, default=dict)),
                ('notification_config', models.JSONField(blank=True, default=dict)),
                ('review_mode', models.CharField(choices=[('none', 'None'), ('on_risk', 'On risk'), ('always', 'Always')], db_index=True, default='on_risk', max_length=24)),
                ('autonomy_mode', models.CharField(choices=[('suggest_only', 'Suggest only'), ('draft_for_approval', 'Draft for approval'), ('autonomous_with_policy', 'Autonomous with policy'), ('full_autonomy_explicit', 'Full autonomy explicit')], db_index=True, default='draft_for_approval', max_length=32)),
                ('instructions', models.JSONField(blank=True, default=dict)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('next_trigger_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='accounts.agentprofile')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='accounts.businessprofile')),
            ],
            options={
                'db_table': 'automations_automation',
                'ordering': ('-created_at',),
            },
        ),
    ]
