# Generated by Django 5.1.14 on 2026-05-17 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('automations', '0001_initial'),
        ('conversations', '0001_initial'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='Optional destination conversation for automation run results.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='automation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automation',
            name='email_account',
            field=models.ForeignKey(blank=True, help_text='Email account used by email-inbox automations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to='integrations.emailaccount'),
        ),
        migrations.AddField(
            model_name='automationdedupekey',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dedupe_keys', to='automations.automation'),
        ),
        migrations.AddField(
            model_name='automationdedupekey',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_dedupe_keys', to='accounts.businessprofile'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['business_profile', 'status'], name='auto_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['agent_profile', 'status'], name='auto_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['status', 'trigger_type', 'next_trigger_at'], name='auto_due_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['status', 'lease_expires_at'], name='auto_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['business_profile', 'created_at'], name='auto_biz_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='automation',
            constraint=models.UniqueConstraint(fields=('agent_profile', 'name'), name='auto_unique_agent_name'),
        ),
        migrations.AddIndex(
            model_name='automationdedupekey',
            index=models.Index(fields=['automation', 'created_at'], name='auto_dedupe_created_idx'),
        ),
        migrations.AddIndex(
            model_name='automationdedupekey',
            index=models.Index(fields=['business_profile', 'created_at'], name='auto_dedupe_biz_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationdedupekey',
            constraint=models.UniqueConstraint(fields=('automation', 'dedupe_key'), name='auto_dedupe_unique_key'),
        ),
    ]
