# Generated by Django 5.1.14 on 2025-11-06 15:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_knowledgeupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(db_index=True, editable=False, max_length=24, unique=True)),
                ('customer_reference', models.UUIDField(blank=True, db_index=True, help_text='Public identifier for the related customer. Replace with FK when the customer model is available.', null=True)),
                ('customer_snapshot', models.JSONField(blank=True, default=dict, help_text='Immutable customer details captured at creation time for quick access.')),
                ('title', models.CharField(help_text='Short, human-friendly summary of the case.', max_length=255)),
                ('description', models.TextField(help_text='AI generated case brief describing the situation.')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
                ('ai_diagnosis', models.TextField(blank=True, help_text='AI generated problem analysis.')),
                ('ai_actions_taken', models.TextField(blank=True, help_text='Actions executed automatically by the AI agent.')),
                ('ai_suggested_actions', models.JSONField(blank=True, default=list, help_text='Ordered list of recommendations for human follow-up.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional case metadata such as classification or routing hints.')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='accounts.agentprofile')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='accounts.businessprofile')),
            ],
            options={
                'db_table': 'cases_case',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseDocumentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_document_id', models.UUIDField(blank=True, help_text='Identifier pointing to the future documents service or storage record.', null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('document_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='cases.case')),
                ('knowledge_upload', models.ForeignKey(blank=True, help_text='Optional reference when the document originates from an existing knowledge upload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_document_links', to='accounts.knowledgeupload')),
            ],
            options={
                'db_table': 'cases_case_document_link',
                'ordering': ('-captured_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_reference', models.CharField(blank=True, help_text='Identifier linking to the underlying chat session or transcript.', max_length=64)),
                ('summary', models.TextField(help_text='Single-line description of the change or update.')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('customer', 'Customer'), ('agent', 'Agent'), ('system', 'System')], default='ai', max_length=32)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='cases.case')),
            ],
            options={
                'db_table': 'cases_case_history_entry',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_reference', models.CharField(blank=True, help_text='Identifier linking to the conversation session the message belongs to.', max_length=64)),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('ai', 'AI'), ('system', 'System')], max_length=16)),
                ('sender_display_name', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField()),
                ('content_type', models.CharField(default='text', help_text='Mime-like hint about the content (e.g., text, markdown, html).', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cases.case')),
            ],
            options={
                'db_table': 'cases_case_message',
                'ordering': ('sent_at', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['business_profile', 'status'], name='case_business_status_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority', 'status'], name='case_priority_status_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['started_at'], name='case_started_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocumentlink',
            index=models.Index(fields=['case', 'captured_at'], name='case_document_case_time_idx'),
        ),
        migrations.AddIndex(
            model_name='casehistoryentry',
            index=models.Index(fields=['case', 'occurred_at'], name='case_history_case_time_idx'),
        ),
        migrations.AddIndex(
            model_name='casemessage',
            index=models.Index(fields=['case', 'sent_at'], name='case_message_case_time_idx'),
        ),
        migrations.AddIndex(
            model_name='casemessage',
            index=models.Index(fields=['session_reference', 'sent_at'], name='case_message_session_idx'),
        ),
    ]
