# Generated by Django 5.1.14 on 2025-11-06 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_knowledgeupload'),
        ('cases', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Direct link to the customer if the interaction could be attributed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='case',
            name='customer_reference',
            field=models.UUIDField(blank=True, db_index=True, help_text='External identifier for cross-system linkage or legacy records.', null=True),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['customer', 'status'], name='case_customer_status_idx'),
        ),
    ]
