# Generated by Django 5.1.15 on 2026-02-12 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Direct link to the customer if the interaction could be attributed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='casedocumentlink',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='cases.case'),
        ),
    ]
