# Generated by Django 5.1.15 on 2026-02-12 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocumentlink',
            name='knowledge_upload',
            field=models.ForeignKey(blank=True, help_text='Optional reference when the document originates from an existing knowledge upload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_document_links', to='knowledge.knowledgeupload'),
        ),
        migrations.AddField(
            model_name='casehistoryentry',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casemessage',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cases.case'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['business_profile', 'status'], name='case_business_status_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['customer', 'status'], name='case_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority', 'status'], name='case_priority_status_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['started_at'], name='case_started_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocumentlink',
            index=models.Index(fields=['case', 'captured_at'], name='case_document_case_time_idx'),
        ),
        migrations.AddIndex(
            model_name='casehistoryentry',
            index=models.Index(fields=['case', 'occurred_at'], name='case_history_case_time_idx'),
        ),
        migrations.AddIndex(
            model_name='casemessage',
            index=models.Index(fields=['case', 'sent_at'], name='case_message_case_time_idx'),
        ),
        migrations.AddIndex(
            model_name='casemessage',
            index=models.Index(fields=['session_reference', 'sent_at'], name='case_message_session_idx'),
        ),
    ]
