# Generated by Django 5.1.14 on 2026-01-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_customer_alter_case_customer_reference_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Fix cases_case_document_link -> accounts_knowledge_upload (SET NULL)
            ALTER TABLE cases_case_document_link
            DROP CONSTRAINT IF EXISTS cases_case_document__knowledge_upload_id_02251f54_fk_accounts_;
            ALTER TABLE cases_case_document_link
            ADD CONSTRAINT cases_case_document__knowledge_upload_id_02251f54_fk_accounts_
            FOREIGN KEY (knowledge_upload_id) REFERENCES accounts_knowledge_upload(id)
            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
