# Generated by Django 5.1.14 on 2026-05-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agentic_tasks", "0001_initial"),
        ("conversations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agentictask",
            name="active_conversation",
            field=models.ForeignKey(blank=True, help_text="Current visible task session for manual and scheduled runs.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agentic_tasks", to="conversations.conversation"),
        ),
        migrations.AddField(
            model_name="agentictask",
            name="created_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_agentic_tasks", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name="agentictask",
            index=models.Index(fields=["business_profile", "status"], name="task_biz_status_idx"),
        ),
        migrations.AddIndex(
            model_name="agentictask",
            index=models.Index(fields=["agent_profile", "status"], name="task_agent_status_idx"),
        ),
        migrations.AddIndex(
            model_name="agentictask",
            index=models.Index(fields=["status", "schedule_enabled", "next_trigger_at"], name="task_due_idx"),
        ),
        migrations.AddIndex(
            model_name="agentictask",
            index=models.Index(fields=["status", "lease_expires_at"], name="task_lease_idx"),
        ),
        migrations.AddIndex(
            model_name="agentictask",
            index=models.Index(fields=["business_profile", "created_at"], name="task_biz_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentictask",
            constraint=models.UniqueConstraint(fields=("agent_profile", "name"), name="task_unique_agent_name"),
        ),
    ]
