"""initial setup

Revision ID: 7eabf356546b
Revises: 
Create Date: 2025-10-10 04:24:34.452138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eabf356546b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('search_terms', sa.ARRAY(sa.String(length=64)), server_default=sa.text('ARRAY[]::text[]'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^industry:[a-z0-9-]{2,50}$'", name=op.f('ck_industries_ck_industries_code_format')),
    sa.CheckConstraint('char_length(label) BETWEEN 2 AND 120', name=op.f('ck_industries_ck_industries_label_length')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_industries'))
    )
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('auth_provider', sa.String(length=32), server_default='password', nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("auth_provider IN ('password','google')", name=op.f('ck_users_ck_users_auth_provider_allowed')),
    sa.CheckConstraint('char_length(first_name) BETWEEN 1 AND 80', name=op.f('ck_users_ck_users_first_name_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('businesses',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('industry_code', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("industry_code ~ '^industry:[a-z0-9-]{2,50}$'", name=op.f('ck_businesses_ck_businesses_industry_code_format')),
    sa.CheckConstraint('char_length(name) BETWEEN 2 AND 120', name=op.f('ck_businesses_ck_businesses_name_length')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_businesses_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['industry_code'], ['industries.code'], name=op.f('fk_businesses_industry_code_industries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_businesses'))
    )
    op.create_index('ix_businesses_industry_code', 'businesses', ['industry_code'], unique=False)
    op.create_table('industry_niches',
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('industry_code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('search_terms', sa.ARRAY(sa.String(length=64)), server_default=sa.text('ARRAY[]::text[]'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^niche:[a-z0-9-]{2,100}$'", name=op.f('ck_industry_niches_ck_industry_niches_code_format')),
    sa.CheckConstraint('char_length(label) BETWEEN 2 AND 120', name=op.f('ck_industry_niches_ck_industry_niches_label_length')),
    sa.ForeignKeyConstraint(['industry_code'], ['industries.code'], name=op.f('fk_industry_niches_industry_code_industries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_industry_niches'))
    )
    op.create_index('ix_industry_niches_industry_code', 'industry_niches', ['industry_code'], unique=False)
    op.create_table('agents',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.Enum('SALES', 'SUPPORT', 'RESEARCH', 'SUCCESS', 'MARKETING', name='agent_role_enum'), nullable=False),
    sa.Column('tone', sa.Enum('FRIENDLY', 'PROFESSIONAL', 'CASUAL', 'FORMAL', 'EMPATHETIC', 'PLAYFUL', name='agent_tone_enum'), nullable=False),
    sa.Column('escalation_rule', sa.Enum('NEVER', 'ON_FALLBACK', 'ON_NEGATIVE_SENTIMENT', 'ON_HIGH_VALUE', 'ALWAYS', name='escalation_rule_enum'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(name) BETWEEN 2 AND 80', name=op.f('ck_agents_ck_agents_name_length')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_agents_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_agents_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index('ix_agents_business_id', 'agents', ['business_id'], unique=False)
    op.create_table('business_niches',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('niche_code', sa.String(length=96), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("niche_code ~ '^niche:[a-z0-9-]{2,50}$'", name=op.f('ck_business_niches_ck_business_niches_code_format')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_niches_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['niche_code'], ['industry_niches.code'], name=op.f('fk_business_niches_niche_code_industry_niches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('business_id', 'niche_code', name=op.f('pk_business_niches'))
    )
    op.create_index('ix_business_niches_business_id', 'business_niches', ['business_id'], unique=False)
    op.create_table('knowledge_items',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('FILE', 'URL', 'TEXT', name='knowledge_source_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', name='knowledge_status_enum'), server_default='pending', nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_name IS NULL OR char_length(display_name) <= 120', name=op.f('ck_knowledge_items_ck_knowledge_items_display_name_length')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_knowledge_items_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_knowledge_items_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_items'))
    )
    op.create_index('ix_knowledge_items_business_status', 'knowledge_items', ['business_id', 'status'], unique=False)
    op.create_table('registration_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('current_step', sa.Enum('BUSINESS_PROFILE', 'AGENT_SETUP', 'KNOWLEDGE_UPLOADS', 'COMPLETED', name='registration_step_enum'), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text("now() + interval '7 days'"), nullable=False),
    sa.Column('steps_completed', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_steps', sa.SmallInteger(), server_default=sa.text('4'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_registration_sessions_ck_registration_sessions_expiry_after_created')),
    sa.CheckConstraint('steps_completed BETWEEN 0 AND total_steps', name=op.f('ck_registration_sessions_ck_registration_sessions_steps_range')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_registration_sessions_business_id_businesses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_registration_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_sessions'))
    )
    op.create_index('ix_registration_sessions_user_id', 'registration_sessions', ['user_id'], unique=False)
    op.create_table('user_business_memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'AGENT', name='membership_role_enum'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_user_business_memberships_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_business_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'business_id', name=op.f('pk_user_business_memberships'))
    )
    op.create_index('ix_user_business_memberships_business_role', 'user_business_memberships', ['business_id', 'role'], unique=False)
    op.create_table('agent_traits',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('trait_code', sa.Enum('CONCISE', 'DETAILED', 'CURIOUS', 'PATIENT', 'PROACTIVE', 'DIRECT', 'CREATIVE', name='agent_trait_enum'), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_traits_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'trait_code', name=op.f('pk_agent_traits'))
    )
    op.create_table('knowledge_item_files',
    sa.Column('knowledge_item_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=128), nullable=True),
    sa.CheckConstraint("content_type IS NULL OR lower(content_type) = ANY (ARRAY['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.google-apps.document','application/vnd.google-apps.spreadsheet'])", name=op.f('ck_knowledge_item_files_ck_knowledge_item_files_content_type_allowed')),
    sa.CheckConstraint('size_bytes BETWEEN 1 AND 20971520', name=op.f('ck_knowledge_item_files_ck_knowledge_item_files_size_range')),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], name=op.f('fk_knowledge_item_files_knowledge_item_id_knowledge_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_item_id', name=op.f('pk_knowledge_item_files'))
    )
    op.create_table('knowledge_item_texts',
    sa.Column('knowledge_item_id', sa.UUID(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.CheckConstraint('char_length(text_content) BETWEEN 1 AND 200000', name=op.f('ck_knowledge_item_texts_ck_knowledge_item_texts_length')),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], name=op.f('fk_knowledge_item_texts_knowledge_item_id_knowledge_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_item_id', name=op.f('pk_knowledge_item_texts'))
    )
    op.create_table('knowledge_item_urls',
    sa.Column('knowledge_item_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.CheckConstraint("url LIKE 'https://%%'", name=op.f('ck_knowledge_item_urls_ck_knowledge_item_urls_https_only')),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], name=op.f('fk_knowledge_item_urls_knowledge_item_id_knowledge_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_item_id', name=op.f('pk_knowledge_item_urls'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_item_urls')
    op.drop_table('knowledge_item_texts')
    op.drop_table('knowledge_item_files')
    op.drop_table('agent_traits')
    op.drop_index('ix_user_business_memberships_business_role', table_name='user_business_memberships')
    op.drop_table('user_business_memberships')
    op.drop_index('ix_registration_sessions_user_id', table_name='registration_sessions')
    op.drop_table('registration_sessions')
    op.drop_index('ix_knowledge_items_business_status', table_name='knowledge_items')
    op.drop_table('knowledge_items')
    op.drop_index('ix_business_niches_business_id', table_name='business_niches')
    op.drop_table('business_niches')
    op.drop_index('ix_agents_business_id', table_name='agents')
    op.drop_table('agents')
    op.drop_index('ix_industry_niches_industry_code', table_name='industry_niches')
    op.drop_table('industry_niches')
    op.drop_index('ix_businesses_industry_code', table_name='businesses')
    op.drop_table('businesses')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('industries')
    # ### end Alembic commands ###
