# Generated by Django 5.1.15 on 2026-04-10 21:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('merged', 'Merged')], default='active', max_length=24)),
                ('source', models.CharField(blank=True, default='manual', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('website_domain_normalized', models.CharField(blank=True, db_index=True, max_length=255)),
                ('primary_phone', models.CharField(blank=True, max_length=40)),
                ('primary_phone_normalized', models.CharField(blank=True, db_index=True, max_length=40)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_companies', to='accounts.businessprofile')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_crm_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_company',
                'ordering': ('name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CrmContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('merged', 'Merged')], default='active', max_length=24)),
                ('source', models.CharField(blank=True, default='manual', max_length=64)),
                ('display_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_email_normalized', models.CharField(blank=True, db_index=True, max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=40)),
                ('primary_phone_normalized', models.CharField(blank=True, db_index=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_contacts', to='accounts.businessprofile')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_crm_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_contact',
                'ordering': ('display_name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CrmActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('imported', 'Imported'), ('merged', 'Merged'), ('note_added', 'Note Added'), ('archived', 'Archived'), ('restored', 'Restored'), ('other', 'Other')], default='other', max_length=32)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('import', 'Import'), ('system', 'System')], default='system', max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to=settings.AUTH_USER_MODEL)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_activities', to='accounts.businessprofile')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.crmcompany')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.crmcontact')),
            ],
            options={
                'db_table': 'crm_activity',
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CrmContactCompanyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_title', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_contact_company_links', to='accounts.businessprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='crm.crmcompany')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='crm.crmcontact')),
            ],
            options={
                'db_table': 'crm_contact_company_link',
                'ordering': ('-is_primary', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CrmExternalIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('contact', 'Contact'), ('company', 'Company')], max_length=16)),
                ('source_system', models.CharField(max_length=64)),
                ('source_account_ref', models.CharField(blank=True, max_length=128)),
                ('external_object_type', models.CharField(blank=True, default='record', max_length=64)),
                ('external_id', models.CharField(max_length=255)),
                ('external_label', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_external_identities', to='accounts.businessprofile')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='crm.crmcompany')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='crm.crmcontact')),
            ],
            options={
                'db_table': 'crm_external_identity',
                'ordering': ('source_system', 'external_object_type', 'external_id'),
            },
        ),
        migrations.CreateModel(
            name='CrmFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_object', models.CharField(choices=[('contact', 'Contact'), ('company', 'Company')], max_length=16)),
                ('key', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('long_text', 'Long Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Datetime'), ('select', 'Select'), ('multi_select', 'Multi Select'), ('object', 'Object'), ('object_list', 'Object List')], max_length=24)),
                ('required', models.BooleanField(default=False)),
                ('searchable', models.BooleanField(default=False)),
                ('filterable', models.BooleanField(default=False)),
                ('pii', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_field_definitions', to='accounts.businessprofile')),
            ],
            options={
                'db_table': 'crm_field_definition',
                'ordering': ('target_object', 'label'),
            },
        ),
        migrations.CreateModel(
            name='CrmFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('search_text', models.TextField(blank=True, default='')),
                ('exact_text', models.CharField(blank=True, default='', max_length=255)),
                ('number_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('datetime_value', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_field_values', to='accounts.businessprofile')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='crm.crmcompany')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='crm.crmcontact')),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='crm.crmfielddefinition')),
            ],
            options={
                'db_table': 'crm_field_value',
                'ordering': ('field_definition__label', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CrmImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=24)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('run_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=10)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_import_jobs', to='accounts.businessprofile')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_import_job',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CrmDuplicateSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('contact', 'Contact'), ('company', 'Company')], max_length=16)),
                ('record_id', models.UUIDField(blank=True, null=True)),
                ('candidate_record_id', models.UUIDField()),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('incoming_snapshot', models.JSONField(blank=True, default=dict)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ignored', 'Ignored'), ('merged', 'Merged')], default='open', max_length=16)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_duplicate_suggestions', to='accounts.businessprofile')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_suggestions', to='crm.crmimportjob')),
            ],
            options={
                'db_table': 'crm_duplicate_suggestion',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CrmImportRowResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('duplicate', 'Duplicate'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=24)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('contact_id', models.UUIDField(blank=True, null=True)),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('duplicate_of_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_results', to='crm.crmimportjob')),
            ],
            options={
                'db_table': 'crm_import_row_result',
                'ordering': ('row_number',),
            },
        ),
        migrations.CreateModel(
            name='CrmImportSourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=16)),
                ('file', models.FileField(upload_to='crm/imports/%Y/%m/%d')),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('column_snapshot', models.JSONField(blank=True, default=list)),
                ('sample_rows', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_import_source_files', to='accounts.businessprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_import_source_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_import_source_file',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='crmimportjob',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='crm.crmimportsourcefile'),
        ),
        migrations.CreateModel(
            name='CrmImportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_import_templates', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_import_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_import_template',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='crmimportjob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='crm.crmimporttemplate'),
        ),
        migrations.CreateModel(
            name='CrmMergeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('contact', 'Contact'), ('company', 'Company')], max_length=16)),
                ('survivor_record_id', models.UUIDField()),
                ('merged_record_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_merge_events', to='accounts.businessprofile')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_merge_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_merge_event',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CrmNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='accounts.businessprofile')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.crmcompany')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.crmcontact')),
            ],
            options={
                'db_table': 'crm_note',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='crmcompany',
            index=models.Index(fields=['business_profile', 'status'], name='crm_company_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcompany',
            index=models.Index(fields=['business_profile', 'name'], name='crm_company_biz_name_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcompany',
            index=models.Index(fields=['business_profile', 'website_domain_normalized'], name='crm_company_biz_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcontact',
            index=models.Index(fields=['business_profile', 'status'], name='crm_contact_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcontact',
            index=models.Index(fields=['business_profile', 'display_name'], name='crm_contact_biz_name_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcontact',
            index=models.Index(fields=['business_profile', 'primary_email_normalized'], name='crm_contact_biz_email_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcontact',
            index=models.Index(fields=['business_profile', 'primary_phone_normalized'], name='crm_contact_biz_phone_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('primary_email_normalized', ''), _negated=True), fields=('business_profile', 'primary_email_normalized'), name='crm_contact_unique_email_per_biz'),
        ),
        migrations.AddIndex(
            model_name='crmactivity',
            index=models.Index(fields=['business_profile', 'occurred_at'], name='crm_activity_biz_occ_idx'),
        ),
        migrations.AddIndex(
            model_name='crmactivity',
            index=models.Index(fields=['contact', 'occurred_at'], name='crm_activity_contact_occ_idx'),
        ),
        migrations.AddIndex(
            model_name='crmactivity',
            index=models.Index(fields=['company', 'occurred_at'], name='crm_activity_company_occ_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcontactcompanylink',
            index=models.Index(fields=['business_profile', 'is_primary'], name='crm_ctco_biz_primary_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmcontactcompanylink',
            constraint=models.UniqueConstraint(fields=('contact', 'company'), name='crm_contact_company_unique'),
        ),
        migrations.AddIndex(
            model_name='crmexternalidentity',
            index=models.Index(fields=['business_profile', 'record_type'], name='crm_extid_biz_type_idx'),
        ),
        migrations.AddIndex(
            model_name='crmexternalidentity',
            index=models.Index(fields=['contact', 'source_system'], name='crm_extid_contact_idx'),
        ),
        migrations.AddIndex(
            model_name='crmexternalidentity',
            index=models.Index(fields=['company', 'source_system'], name='crm_extid_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmexternalidentity',
            constraint=models.UniqueConstraint(fields=('business_profile', 'source_system', 'source_account_ref', 'external_object_type', 'external_id'), name='crm_external_identity_unique_per_source'),
        ),
        migrations.AddIndex(
            model_name='crmfielddefinition',
            index=models.Index(fields=['business_profile', 'target_object'], name='crm_fdef_biz_target_idx'),
        ),
        migrations.AddIndex(
            model_name='crmfielddefinition',
            index=models.Index(fields=['business_profile', 'archived'], name='crm_fdef_biz_arch_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmfielddefinition',
            constraint=models.UniqueConstraint(fields=('business_profile', 'target_object', 'key'), name='crm_field_definition_unique_key'),
        ),
        migrations.AddIndex(
            model_name='crmfieldvalue',
            index=models.Index(fields=['business_profile', 'field_definition'], name='crm_field_value_biz_field_idx'),
        ),
        migrations.AddIndex(
            model_name='crmfieldvalue',
            index=models.Index(fields=['field_definition', 'exact_text'], name='crm_field_value_exact_text_idx'),
        ),
        migrations.AddIndex(
            model_name='crmfieldvalue',
            index=models.Index(fields=['field_definition', 'number_value'], name='crm_field_value_number_idx'),
        ),
        migrations.AddIndex(
            model_name='crmfieldvalue',
            index=models.Index(fields=['field_definition', 'date_value'], name='crm_field_value_date_idx'),
        ),
        migrations.AddIndex(
            model_name='crmfieldvalue',
            index=models.Index(fields=['field_definition', 'datetime_value'], name='crm_field_value_datetime_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmfieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('contact__isnull', False)), fields=('field_definition', 'contact'), name='crm_field_value_unique_contact_field'),
        ),
        migrations.AddConstraint(
            model_name='crmfieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('field_definition', 'company'), name='crm_field_value_unique_company_field'),
        ),
        migrations.AddIndex(
            model_name='crmduplicatesuggestion',
            index=models.Index(fields=['business_profile', 'status'], name='crm_dupe_biz_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmduplicatesuggestion',
            constraint=models.UniqueConstraint(fields=('business_profile', 'record_type', 'import_job', 'source_row_number', 'candidate_record_id'), name='crm_duplicate_suggestion_unique_row'),
        ),
        migrations.AddConstraint(
            model_name='crmimportrowresult',
            constraint=models.UniqueConstraint(fields=('job', 'row_number'), name='crm_import_row_result_unique_row'),
        ),
        migrations.AddConstraint(
            model_name='crmimporttemplate',
            constraint=models.UniqueConstraint(fields=('business_profile', 'name'), name='crm_import_template_unique_name'),
        ),
        migrations.AddIndex(
            model_name='crmimportjob',
            index=models.Index(fields=['business_profile', 'status'], name='crm_import_job_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='crmimportjob',
            index=models.Index(fields=['status', 'run_after'], name='crm_impjob_status_run_idx'),
        ),
        migrations.AddIndex(
            model_name='crmimportjob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='crm_impjob_status_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='crmmergeevent',
            index=models.Index(fields=['business_profile', 'record_type'], name='crm_merge_event_biz_type_idx'),
        ),
        migrations.AddIndex(
            model_name='crmnote',
            index=models.Index(fields=['business_profile', 'created_at'], name='crm_note_biz_created_idx'),
        ),
        migrations.AddIndex(
            model_name='crmnote',
            index=models.Index(fields=['contact', 'created_at'], name='crm_note_contact_created_idx'),
        ),
        migrations.AddIndex(
            model_name='crmnote',
            index=models.Index(fields=['company', 'created_at'], name='crm_note_company_created_idx'),
        ),
    ]
