from django.urls import path

from . import views
from . import mcp_connections
from . import oauth
from . import email_oauth
from . import integration_oauth
from . import chat_portal_files
from . import agent_runs
from . import voice_calls
from . import voice_providers
from apps.crm import api_views as crm_api_views
from .chat_portal import (
    bootstrap_session,
    create_portal_session,
    events,
    list_portal_sessions,
    messages_endpoint,
    portal_tool_approval,
    portal_agent_run_approval,
    portal_agent_run_user_input,
    portal_agent_request_update,
    portal_tool_history,
    portal_email_discard_draft,
    portal_email_send_draft,
    portal_turn_create,
    portal_turn_events,
    portal_turn_cancel,
    resolve_portal_handle,
    submit_csat,
    submit_feedback,
)

from apps.api import health_views

app_name = "api"

urlpatterns = [
    # Health check endpoints (updated from placeholder)
    path("health/", health_views.health_check, name="health"),
    path("health/ready/", health_views.readiness_check, name="readiness"),
    path("health/live/", health_views.liveness_check, name="liveness"),
    path("agents/", views.agents_collection, name="agents-list"),
    path("agents/<uuid:agent_id>/", views.agent_detail_view, name="agents-detail"),
    path("agents/<uuid:agent_id>/capabilities/", views.agent_capabilities_view, name="agents-capabilities"),
    path(
        "agents/<uuid:agent_id>/knowledge-access/",
        views.agent_knowledge_access_view,
        name="agents-knowledge-access",
    ),
    path("agents/<uuid:agent_id>/run-specs/", agent_runs.agent_run_specs_collection, name="agent-run-specs"),
    path(
        "agents/<uuid:agent_id>/run-specs/<uuid:spec_id>/",
        agent_runs.agent_run_spec_detail,
        name="agent-run-spec-detail",
    ),
    path("agents/<uuid:agent_id>/runs/", agent_runs.agent_runs_collection, name="agent-runs"),
    path("agents/<uuid:agent_id>/runs/<uuid:run_id>/", agent_runs.agent_run_detail, name="agent-run-detail"),
    path("agents/<uuid:agent_id>/runs/<uuid:run_id>/events/", agent_runs.agent_run_events, name="agent-run-events"),
    path("agents/<uuid:agent_id>/runs/<uuid:run_id>/cancel/", agent_runs.agent_run_cancel, name="agent-run-cancel"),
    path("agents/<uuid:agent_id>/runs/<uuid:run_id>/user-input/", agent_runs.agent_run_user_input, name="agent-run-user-input"),
    path("agents/<uuid:agent_id>/runs/<uuid:run_id>/approval/", agent_runs.agent_run_approval, name="agent-run-approval"),
    path("agents/<uuid:agent_id>/runs/<uuid:run_id>/resume/", agent_runs.agent_run_resume, name="agent-run-resume"),
    path("agents/<uuid:agent_id>/automations/", agent_runs.agent_automations_collection, name="agent-automations"),
    path(
        "agents/<uuid:agent_id>/automations/<uuid:automation_id>/",
        agent_runs.agent_automation_detail,
        name="agent-automation-detail",
    ),
    path(
        "agents/<uuid:agent_id>/automations/<uuid:automation_id>/trigger/",
        agent_runs.agent_automation_trigger,
        name="agent-automation-trigger",
    ),
    path("agents/<uuid:agent_id>/watchers/", agent_runs.agent_watchers_collection, name="agent-watchers"),
    path(
        "agents/<uuid:agent_id>/watchers/<uuid:watcher_id>/",
        agent_runs.agent_watcher_detail,
        name="agent-watcher-detail",
    ),
    path(
        "agents/<uuid:agent_id>/watchers/<uuid:watcher_id>/trigger/",
        agent_runs.agent_watcher_trigger,
        name="agent-watcher-trigger",
    ),
    path(
        "webhooks/automations/<uuid:automation_id>/<slug:token>/",
        agent_runs.automation_webhook_trigger,
        name="automation-webhook-trigger",
    ),
    path("register/sessions/", views.start_registration, name="register-start"),
    path(
        "register/sessions/<uuid:session_id>/business/",
        views.update_business_profile,
        name="register-business",
    ),
    path(
        "register/businesses/<uuid:business_id>/agent/",
        views.configure_agent,
        name="register-agent",
    ),
    path(
        "register/businesses/<uuid:business_id>/uploads/",
        views.finalize_uploads,
        name="register-uploads",
    ),
    path("chat/portal/resolve/<slug:business_slug>/<slug:agent_slug>/", resolve_portal_handle, name="chat-portal-resolve"),
    path("chat/portal/sessions/", bootstrap_session, name="chat-portal-session"),
    path("chat/portal/sessions/list/", list_portal_sessions, name="chat-portal-sessions-list"),
    path("chat/portal/sessions/create/", create_portal_session, name="chat-portal-sessions-create"),
    path("chat/portal/files/upload/", chat_portal_files.portal_file_upload, name="chat-portal-files-upload"),
    path(
        "chat/portal/files/<uuid:file_id>/download/",
        chat_portal_files.portal_file_download,
        name="chat-portal-files-download",
    ),
    path(
        "chat/portal/files/<uuid:file_id>/download-url/",
        chat_portal_files.portal_file_download_url,
        name="chat-portal-files-download-url",
    ),
    path("chat/turns/", portal_turn_create, name="chat-turns-create"),
    path("chat/turns/<uuid:turn_id>/events/", portal_turn_events, name="chat-turns-events"),
    path("chat/turns/<uuid:turn_id>/cancel/", portal_turn_cancel, name="chat-turns-cancel"),
    path("chat/portal/tools/approve/", portal_tool_approval, name="chat-portal-tools-approve"),
    path("chat/portal/runs/approval/", portal_agent_run_approval, name="chat-portal-runs-approval"),
    path("chat/portal/runs/user-input/", portal_agent_run_user_input, name="chat-portal-runs-user-input"),
    path("chat/portal/agent-requests/update/", portal_agent_request_update, name="chat-portal-agent-requests-update"),
    path("chat/portal/tools/history/", portal_tool_history, name="chat-portal-tools-history"),
    path("chat/portal/email/send-draft/", portal_email_send_draft, name="chat-portal-email-send-draft"),
    path("chat/portal/email/discard-draft/", portal_email_discard_draft, name="chat-portal-email-discard-draft"),
    path("chat/messages/", messages_endpoint, name="chat-messages"),
    path("chat/events/", events, name="chat-events"),
    path("chat/csat/", submit_csat, name="chat-csat"),
    path("chat/feedback/", submit_feedback, name="chat-feedback"),
    path("knowledge/documents/", views.knowledge_documents_collection, name="knowledge-documents-list"),
    path("knowledge/documents/<uuid:document_id>/status/", views.knowledge_document_status, name="knowledge-documents-status"),
    path("knowledge/documents/<uuid:document_id>/", views.knowledge_document_detail, name="knowledge-documents-detail"),
    path(
        "knowledge/documents/<uuid:document_id>/download/",
        views.knowledge_document_download,
        name="knowledge-documents-download",
    ),
    path("knowledge/documents/scrape/", views.knowledge_document_scrape, name="knowledge-documents-scrape"),
    path("knowledge/documents/preview-csv/", views.knowledge_document_preview_csv, name="knowledge-documents-preview-csv"),
    path("integrations/", views.integrations_collection, name="integrations-collection"),
    path(
        "integrations/<uuid:integration_id>/sheets/",
        views.integration_sheets_collection,
        name="integrations-sheets",
    ),
    path("integrations/google/start/", views.start_google_drive_oauth, name="integrations-google-start"),
    path("integrations/google/callback/", views.google_drive_oauth_callback, name="integrations-google-callback"),
    path("integrations/google/resources/", views.google_drive_resources, name="integrations-google-resources"),
    path("integrations/google/resources/save/", views.google_drive_save_resources, name="integrations-google-resources-save"),
    path("integrations/google/sync/", views.google_drive_sync_now, name="integrations-google-sync"),
    path("crm/contacts/", crm_api_views.crm_contacts_collection, name="crm-contacts"),
    path("crm/contacts/<uuid:contact_id>/", crm_api_views.crm_contact_detail, name="crm-contact-detail"),
    path("crm/contacts/<uuid:contact_id>/merge/", crm_api_views.crm_contact_merge, name="crm-contact-merge"),
    path("crm/contacts/<uuid:contact_id>/notes/", crm_api_views.crm_contact_notes_collection, name="crm-contact-notes"),
    path("crm/contacts/<uuid:contact_id>/company-links/", crm_api_views.crm_contact_company_links_collection, name="crm-contact-company-links"),
    path("crm/contacts/<uuid:contact_id>/company-links/<uuid:company_id>/", crm_api_views.crm_contact_company_link_detail, name="crm-contact-company-link-detail"),
    path("crm/companies/", crm_api_views.crm_companies_collection, name="crm-companies"),
    path("crm/companies/<uuid:company_id>/", crm_api_views.crm_company_detail, name="crm-company-detail"),
    path("crm/companies/<uuid:company_id>/merge/", crm_api_views.crm_company_merge, name="crm-company-merge"),
    path("crm/companies/<uuid:company_id>/notes/", crm_api_views.crm_company_notes_collection, name="crm-company-notes"),
    path("crm/field-definitions/", crm_api_views.crm_field_definitions_collection, name="crm-field-definitions"),
    path("crm/field-definitions/<uuid:field_definition_id>/", crm_api_views.crm_field_definition_detail, name="crm-field-definition-detail"),
    path("crm/imports/sources/", crm_api_views.crm_import_sources_collection, name="crm-import-sources"),
    path("crm/imports/templates/", crm_api_views.crm_import_templates_collection, name="crm-import-templates"),
    path("crm/imports/jobs/", crm_api_views.crm_import_jobs_collection, name="crm-import-jobs"),
    path("crm/imports/jobs/<uuid:job_id>/", crm_api_views.crm_import_job_detail, name="crm-import-job-detail"),
    path("crm/duplicates/", crm_api_views.crm_duplicate_suggestions_collection, name="crm-duplicate-suggestions"),
    path("crm/duplicates/<uuid:suggestion_id>/", crm_api_views.crm_duplicate_suggestion_detail, name="crm-duplicate-suggestion-detail"),
    path("mcp/connections/", mcp_connections.mcp_connections_collection, name="mcp-connections"),
    path("mcp/connections/<uuid:connection_id>/", mcp_connections.mcp_connection_detail, name="mcp-connection-detail"),
    path("mcp/connections/<uuid:connection_id>/test/", mcp_connections.mcp_connection_test, name="mcp-connection-test"),
    path("mcp/connections/<uuid:connection_id>/agents/", mcp_connections.mcp_connection_agents, name="mcp-connection-agents"),
    path("mcp/connections/<uuid:connection_id>/tools/", mcp_connections.mcp_connection_tools, name="mcp-connection-tools"),
    path("mcp/controls/tools/", mcp_connections.mcp_controls_tools, name="mcp-controls-tools"),
    path("mcp/agents/approval-defaults/", mcp_connections.mcp_agent_approval_defaults, name="mcp-agent-approval-defaults"),
    path("oauth/start/<str:provider_key>/<str:marketplace_key>/", oauth.oauth_start, name="oauth_start"),
    path("oauth/callback/<str:provider_key>/", oauth.oauth_callback, name="oauth_callback"),
    path("oauth/refresh/<uuid:connection_id>/", oauth.oauth_refresh, name="oauth_refresh"),
    path("email/oauth/start/<str:provider_key>/", email_oauth.email_oauth_start, name="email_oauth_start"),
    path("email/oauth/callback/<str:provider_key>/", email_oauth.email_oauth_callback, name="email_oauth_callback"),
    path("email/oauth/disconnect/<str:provider_key>/", email_oauth.email_oauth_disconnect, name="email_oauth_disconnect"),
    path("email/oauth/tools/<str:provider_key>/", email_oauth.email_oauth_tools, name="email_oauth_tools"),
    path("integrations/oauth/start/<str:integration_type>/", integration_oauth.integration_oauth_start, name="integration_oauth_start"),
    path("integrations/oauth/callback/<str:integration_type>/", integration_oauth.integration_oauth_callback, name="integration_oauth_callback"),
    path("integrations/oauth/disconnect/<str:integration_type>/", integration_oauth.integration_oauth_disconnect, name="integration_oauth_disconnect"),
    path("integrations/oauth/tools/<str:integration_type>/", integration_oauth.integration_oauth_tools, name="integration_oauth_tools"),

    # Voice calls (Phase 1)
    path("voice/providers/", voice_providers.voice_providers_collection, name="voice-providers"),
    path(
        "voice/providers/<str:provider>/",
        voice_providers.voice_provider_detail,
        name="voice-provider-detail",
    ),
    path(
        "voice/providers/<str:provider>/test/",
        voice_providers.voice_provider_test,
        name="voice-provider-test",
    ),
    path("voice/calls/", voice_calls.voice_calls_collection, name="voice-calls"),
    path("voice/calls/<uuid:call_id>/", voice_calls.voice_call_detail, name="voice-call-detail"),
    path("voice/calls/<uuid:call_id>/events/", voice_calls.voice_call_events, name="voice-call-events"),
    path("voice/calls/<uuid:call_id>/hangup/", voice_calls.voice_call_hangup, name="voice-call-hangup"),
]
