# Generated by Django 5.1.15 on 2026-02-12 14:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='McpConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, default='', max_length=160)),
                ('source_type', models.CharField(choices=[('marketplace', 'Marketplace'), ('manual', 'Manual')], default='manual', max_length=24)),
                ('marketplace_key', models.CharField(blank=True, default='', help_text='Optional identifier for a curated marketplace entry.', max_length=80)),
                ('server_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=16)),
                ('auth_type', models.CharField(choices=[('none', 'No auth'), ('bearer', 'Bearer token'), ('header', 'Custom header')], default='none', max_length=16)),
                ('default_approval_mode', models.CharField(choices=[('auto', 'Auto-approve all'), ('approve_writes', 'Approve write operations'), ('approve_all', 'Approve all operations')], default='approve_writes', help_text='Default approval behavior for tools from this connection.', max_length=24)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('credentials_key_version', models.PositiveSmallIntegerField(default=1)),
                ('credentials_last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('credential_error_count', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connections', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_mcp_connection',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AgentMcpToolSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(help_text="The remote tool name from the MCP server (e.g., 'create_issue').", max_length=255)),
                ('operation_type', models.CharField(choices=[('read', 'Read (safe)'), ('write', 'Write (requires approval)'), ('unknown', 'Unknown (treat as write)')], default='unknown', help_text='Classification: read (safe) or write (needs approval).', max_length=16)),
                ('approval_mode', models.CharField(blank=True, choices=[('auto', 'Auto-approve all'), ('approve_writes', 'Approve write operations'), ('approve_all', 'Approve all operations')], help_text='Override the agent default for this tool. NULL = inherit.', max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tool_settings', to='accounts.agentprofile')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tool_settings', to='mcp.mcpconnection')),
            ],
            options={
                'db_table': 'accounts_agent_mcp_tool_setting',
                'ordering': ('tool_name',),
            },
        ),
        migrations.CreateModel(
            name='McpConnectionAgentOptOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opted_out_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_opt_outs', to='accounts.agentprofile')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_opt_outs', to='mcp.mcpconnection')),
                ('opted_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_opt_out_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_mcp_connection_opt_out',
                'ordering': ('-opted_out_at',),
            },
        ),
        migrations.CreateModel(
            name='McpConnectionAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_id_snapshot', models.UUIDField(blank=True, db_index=True, help_text='Snapshot of the connection UUID for retention when the connection is deleted.', null=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('enabled', 'Enabled'), ('disabled', 'Disabled'), ('agent_opted_out', 'Agent Opted Out'), ('agent_opted_in', 'Agent Opted In'), ('tool_approved', 'Tool Approved'), ('tool_denied', 'Tool Denied')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_audit_events', to=settings.AUTH_USER_MODEL)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_audit_events', to='accounts.businessprofile')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='mcp.mcpconnection')),
            ],
            options={
                'db_table': 'accounts_mcp_connection_audit_event',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='McpConnectionTestJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('trigger', models.CharField(blank=True, default='', max_length=48)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('run_after', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connection_test_jobs', to='accounts.businessprofile')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_jobs', to='mcp.mcpconnection')),
            ],
            options={
                'db_table': 'mcp_connection_test_job',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='McpConnectionToolSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(help_text="The remote tool name from the MCP server (e.g., 'create_issue').", max_length=255)),
                ('operation_type', models.CharField(choices=[('read', 'Read (safe)'), ('write', 'Write (requires approval)'), ('unknown', 'Unknown (treat as write)')], default='unknown', help_text='Classification: read (safe) or write (needs approval).', max_length=16)),
                ('approval_mode', models.CharField(blank=True, choices=[('auto', 'Auto-approve all'), ('approve_writes', 'Approve write operations'), ('approve_all', 'Approve all operations')], help_text='Override the connection default. NULL = inherit from connection.', max_length=24, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of what this tool does.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_settings', to='mcp.mcpconnection')),
            ],
            options={
                'db_table': 'accounts_mcp_connection_tool_setting',
                'ordering': ('tool_name',),
            },
        ),
        migrations.CreateModel(
            name='McpToolOutputArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_call_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('tool_event_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('invoked_tool', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('tool_id', models.CharField(blank=True, db_index=True, default='', max_length=240)),
                ('remote_connection_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('remote_connection_name', models.CharField(blank=True, default='', max_length=240)),
                ('remote_tool', models.CharField(blank=True, default='', max_length=240)),
                ('status', models.CharField(blank=True, default='', max_length=48)),
                ('is_error', models.BooleanField(default=False)),
                ('request', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tool_output_artifacts', to='conversations.conversation')),
            ],
            options={
                'db_table': 'mcp_tool_output_artifact',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='mcpconnection',
            index=models.Index(fields=['business_profile', 'status'], name='mcp_conn_business_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpconnection',
            index=models.Index(fields=['business_profile', 'slug'], name='mcp_conn_business_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='mcpconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('business_profile', 'slug'), name='mcp_conn_slug_unique'),
        ),
        migrations.AddIndex(
            model_name='agentmcptoolsetting',
            index=models.Index(fields=['agent_profile', 'connection'], name='agt_mcp_tool_agent_conn_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmcptoolsetting',
            index=models.Index(fields=['connection', 'tool_name'], name='agt_mcp_tool_conn_tool_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentmcptoolsetting',
            constraint=models.UniqueConstraint(fields=('agent_profile', 'connection', 'tool_name'), name='agent_mcp_tool_setting_unique'),
        ),
        migrations.AddIndex(
            model_name='mcpconnectionagentoptout',
            index=models.Index(fields=['connection', 'opted_out_at'], name='mcp_conn_opt_out_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpconnectionagentoptout',
            index=models.Index(fields=['agent_profile', 'opted_out_at'], name='mcp_agent_opt_out_idx'),
        ),
        migrations.AddConstraint(
            model_name='mcpconnectionagentoptout',
            constraint=models.UniqueConstraint(fields=('connection', 'agent_profile'), name='mcp_conn_agent_opt_out_unique'),
        ),
        migrations.AddIndex(
            model_name='mcpconnectionauditevent',
            index=models.Index(fields=['connection', 'action'], name='mcp_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpconnectionauditevent',
            index=models.Index(fields=['connection_id_snapshot', 'action'], name='mcp_audit_snap_action_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpconnectiontestjob',
            index=models.Index(fields=['status', 'run_after'], name='mcp_test_job_run_after_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpconnectiontestjob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='mcp_test_job_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpconnectiontestjob',
            index=models.Index(fields=['connection', 'status'], name='mcp_test_job_conn_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpconnectiontestjob',
            index=models.Index(fields=['business_profile', 'status'], name='mcp_testjob_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpconnectiontoolsetting',
            index=models.Index(fields=['connection', 'operation_type'], name='mcp_tool_op_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='mcpconnectiontoolsetting',
            constraint=models.UniqueConstraint(fields=('connection', 'tool_name'), name='mcp_tool_setting_unique'),
        ),
        migrations.AddIndex(
            model_name='mcptooloutputartifact',
            index=models.Index(fields=['conversation', 'created_at'], name='mcp_artifact_conv_created_idx'),
        ),
    ]
